### ISSUE TITLE
Hair not rendering properly on CPU 

### ISSUE THREAD

**Issue by matthewv1998** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#105]
hair is not rendering properly on CPU, with cpu and gpu half of the image renders. normally while the other half is black. 
![cpu + gpu ](https://user-images.githubusercontent.com/61604229/96773345-3b416e80-1399-11eb-9488-f28a0445cb9f.png)
(cpu and gpu) 
![cpu ](https://user-images.githubusercontent.com/61604229/96773499-7774cf00-1399-11eb-93e8-755ff9650662.png)
(cpu)
![gpu ](https://user-images.githubusercontent.com/61604229/96774060-52349080-139a-11eb-91ee-3255e6065b7c.png)
(gpu)

[fur .zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5418361/fur.zip)
two systems were texted and both shared the same issue 
1st system 
3600
32gb ram
5600xt
500gb ssd 
2nd system 
1700
16gb ram
5700 
1tb hdd 
Blender version 2.90.1 
RPR version 2.5.1
same issue on RPR 2.4

**Comment by bsavery** [comment]
Hi there.  What is the Render quality setting you have?  Is it the same in RPR 2.0?

**Comment by matthewv1998** [comment]
> Hi there. What is the Render quality setting you have? Is it the same in RPR 2.0?

render quality is full, it should be noted that this borks up with cycles nodes the most. and i cant speak for RPR 2.0 as i cant get it to install.

**Comment by matthewv1998** [comment]
Another note, uber PBR does this, but it makes itself much less obvious.

**Comment by bsavery** [comment]
Hmmm so we see this as fixed in RPR 2.0. What's the error there installing that?

**Comment by matthewv1998** [comment]
It just wont register as installed, it doesnt exist to blender 2.8 or 2.79 no matter what i tried.

**Comment by bsavery** [comment]
Hi @matthewv1998 .  The latest RPR plugin doesn't support blender 2.79.  What's the error installing?

**Comment by bsavery** [comment]
Will verify fixed @arozghon

**Comment by bsavery** [comment]
Fixed with latest build.
