### ISSUE TITLE
Hybrid renderers are not working in my laptop

### ISSUE THREAD

**Issue by abcd-4278** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#108]
I have a GTX 1050 (non ti) (notebook).
Blender freezes when I select Low, Medium or High rendering method. The RPR 2.0 and Full works seamlessly

**Comment by bsavery** [comment]
This might have been covered in another issue.  What is your vram?
Hybrid is limited to > 4gb cards

**Comment by abcd-4278** [comment]
More than 4GB? I have exactly 4GB vram.
