### ISSUE TITLE
2.0 Experimental Renderer Artifacts

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#11]
Running into lots of rendering artifacts when using RPR 2.0 experimental renderer even in simple scenes.

See in the video I made here:

Rendering Artifacts:
https://youtu.be/uo3uSafRFPk?t=669

RPR version:
2.4.11

Blender Version:
2.82a

System:
AMD Ryzen 3960x Threadripper
Radeon VII (x2)
64GB RAM
Gigabyte Auros 1TB M.2 NVME SSD

**Comment by bsavery** [comment]
Thanks.  In general it's good to attach scenes to bug reports.  However I am going to close this because we are aware in RPR 2.0 and fixed it already.  Subscribe to this repo for updates when we upload new builds.  Unless you're interested in compiling from source!

**Comment by danthefatman09** [comment]
@bsavery can you send me a link to instructions on how I might be able to compile or use the recent patches? I would like to use the patches, etc. to utilize rpr 2.0 but do not know how to.

**Comment by bsavery** [comment]
Hi @danthefatman09 .  To build you'd need python, git and to follow the instructions here:  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon

in the readme.  
Basically you'd want to follow the instructions there, and run 
python build.py from the command line.  

If you're on macOS you'd run ./build_osx.sh

**Comment by bsavery** [comment]
Let me know if/when you get stuck.

**Comment by djtutorials** [comment]
Hi bsavery-

I am totally stuck on this. This is the second time I tried to sit down and figure this out- when running the build.py, I am getting a series of errors. A lot of the instructions are kind of written in a way that developers would know what is going on so please forgive me for my ignorance in this... Here is the error I am getting when trying to run the build.py:

Traceback (most recent call last):
  File "rpr.py", line 149, in <module>
    '__rpr', 'pyrprwrap.py', 'pyrprwrap_make.py', abi_mode)
  File "rpr.py", line 41, in export
    write_api(api_desc_fpath, f, abi_mode)
  File "rpr.py", line 114, in write_api
    api = pyrprapi.load(api_desc_fpath)
  File "src\pyrprapi.py", line 183, in load
    loader = json.load(open(fpath),
FileNotFoundError: [Errno 2] No such file or directory: 'src\\pyrprwrapapi.json'
Traceback (most recent call last):
  File "C:\BLENDER_ADDONS\prorender\dev\RadeonProRenderBlenderAddon-master (1)\RadeonProRenderBlenderAddon-master\build.py", line 43, in <module>
    subprocess.check_call([sys.executable, 'rpr.py'])
  File "C:\Users\danie\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\danie\\AppData\\Local\\Programs\\Python\\Python37\\python.exe', 'rpr.py']' returned non-zero exit status 1.


Sorry if this is an obvious thing. Please help if you can.

-DJ

**Comment by djtutorials** [comment]
Hi all-

I discovered the weekly builds so I can use that for the time being. Would very much like to help in looking at code/etc. though.

-Dan

**Comment by ardraeiss** [comment]
Hello @djtutorials , I'm going to check the build process again on a fresh OS to see if anything is missing from build readme.
