### ISSUE TITLE
Blender Windows Store - ProRender install/activation issue

### ISSUE THREAD

**Issue by Dprasni** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#111]
System Information
Operating system:
Graphics card:

Blender Version
Broken: (example: 2.90.1, 3e85bb34d0d7)
Worked: (on a normall install installed from the windows MSI file)

Short description of error
The windows store version of blender gives off errors when activating ProRender renderer

Exact steps for others to reproduce the error
Based on the default startup or an attached .blend file (as simple as possible).

https://dev-files.blender.org/file/data/jjrawwa63fi4zvk57om4/PHID-FILE-rptqvs2aefb2bkwsef6x/image.png

Download windows store blender and activate prorender v2.5.17

**Comment by bnagirniak** [comment]
Thank you for report, this is our known issue, we'll be working to fix this.

**Comment by bsavery** [comment]
@bnagirniak will investigate more.

**Comment by marc-hopkins** [comment]
My same issue was resolved by uninstalling and then re-installing blender.

**Comment by bnagirniak** [comment]
This issue is fixed in #269
