### ISSUE TITLE
RPR 2.5.20 texture filtering/resolution issue

### ISSUE THREAD

**Issue by MakramDaou** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#116]
Just did a quick render test with the pre-release 2.5.20 in Blender 2.90 and noticed some strange texture filtering/res issue (an 8K diffuse map in this case) is overly pixelated:

RPR 2 (Full):
![Screenshot 2020-10-30 235433](https://user-images.githubusercontent.com/46979415/97763641-80d60800-1b0c-11eb-8d4f-3416ad7b9ad5.jpg)
Cycles:
![Screenshot 2020-10-30 235348](https://user-images.githubusercontent.com/46979415/97763913-56d11580-1b0d-11eb-961b-38425a402772.jpg)

RPR (Legacy):
![Screenshot 2020-10-31 000810](https://user-images.githubusercontent.com/46979415/97763883-40c35500-1b0d-11eb-9d91-be3a8d593d23.jpg)

RPR 2 (Full):
![Screenshot 2020-10-30 235300](https://user-images.githubusercontent.com/46979415/97763670-9814f580-1b0c-11eb-8998-07fa49b98f2e.jpg)
Cycles:
![Screenshot 2020-10-30 235322](https://user-images.githubusercontent.com/46979415/97763686-a95e0200-1b0c-11eb-962e-bb444d71fbf4.jpg)

Specs:
Windows 10 2004
i7 6700K
32GB
Radeon VII (latest Pro drivers)
Blender 2.9

Mak

**Comment by bsavery** [comment]
Thanks.  We're working on it.

**Comment by bsavery** [comment]
I claim this is fixed now.  Please reopen if necessary.
