### ISSUE TITLE
Prorender for Blender v2.4.11 rpr Image Texture node not working in non-full modes

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#12]
The rpr image texture node assigned from the AMD Radeon Prorender Materials library seems to have issues when switching to High, Medium and Low settings.

Video showing issues:
https://youtu.be/uo3uSafRFPk?t=1141

Workaround:
Switch rpr image texture nodes to Blender image texture nodes.

RPR Version: 2.4.11

Blender version: 2.82a

System:
AMD Ryzen 3960x Threadripper
Radeon VII (x2)
64GB RAM
Gigabyte Auros 1TB M.2 NVME SSD

**Comment by ardraeiss** [comment]
I see, thank you for the report.
