### ISSUE TITLE
RPR GPU Rendering Shows Nothing

### ISSUE THREAD

**Issue by BumpierZulu9930** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#128]
When rendering with a GPU, nothing is shown:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/33190165/98796103-9963ed80-243d-11eb-8d68-2cd896546a50.png">
Hybrid rendering shows little chunks:
<img width="613" alt="Screen Shot 2020-11-11 at 1 09 00 PM" src="https://user-images.githubusercontent.com/33190165/98796182-b3053500-243d-11eb-9aa1-27137bc661a8.png">

While CPU rendering works normally:
<img width="613" alt="Screen Shot 2020-11-11 at 1 08 43 PM" src="https://user-images.githubusercontent.com/33190165/98796232-c0baba80-243d-11eb-8969-be94ce8f90f4.png">

I've been able to recreate this issue with a factory reset Blender, after restarting Blender, after restarting my system, and after completely reinstalling the plugin. I wish I could provide a log of some sort, but I do not know how to obtain such a log.

Information:
OS version: macOS Mojave 10.14.6
CPU: 2.5 GHz Intel Core i7
GPU: AMD Radeon R9 M370X 2 GB
RPR Version: 2.5.22
Blender version(s): 2.83.6 LTS, 2.91 Beta, and 2.92 Alpha
Rendering mode: Full (Legacy works fine)

**Comment by bsavery** [comment]
Hi there.  I don't think we tested this particular GPU in macOS.  Is this on a 15" macbook pro?

**Comment by BumpierZulu9930** [comment]
Yes, I am using a 2015 15" MacBook Pro.

**Comment by bsavery** [comment]
Thanks.  So right now we're recommending Mojave users to use legacy mode.  Sorry for the inconvenience.
