### ISSUE TITLE
Prorender for Blender v2.4.11 Rendering bug when switching from Full to Medium/High

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#13]
When jumping between Full to Medium or High settings, occasionally the renderer will represent the Low settings instead of Medium or High.

Video showing issue:
https://youtu.be/uo3uSafRFPk?t=451

Workaround:
Switch to Low, then to Medium/High

RPR version:
2.4.11

Blender Version:
2.82a

System:
AMD Ryzen 3960x Threadripper
Radeon VII (x2)
64GB RAM
Gigabyte Auros 1TB M.2 NVME SSD

**Comment by bsavery** [comment]
We think this is fixed, verifying @arozghon

**Comment by ARozghon** [comment]
will check it

**Comment by bnagirniak** [comment]
It is fixed
