### ISSUE TITLE
Noise texture not supported yet

### ISSUE THREAD

**Issue by SimonLuoshiping** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#135]
Incorrect RPR Bump Map node result 
bump still not repaired
![1](https://user-images.githubusercontent.com/56295798/99475619-e7bb4400-2989-11eb-975e-01ec96cf49cb.png)
![2](https://user-images.githubusercontent.com/56295798/99475626-e9850780-2989-11eb-9687-60caf866886a.png)

MAC   11.0.1     Radeon Pro 580X

**Comment by bsavery** [comment]
Please attach a scene.

**Comment by djtutorials** [comment]
@bsavery 
You can recreate this using a simple default cube and noise texture.

Here is the legacy:
![image](https://user-images.githubusercontent.com/65964807/99576658-20115100-298f-11eb-8a0e-a7f1847be9be.png)

Here is Full 2.0:
![image](https://user-images.githubusercontent.com/65964807/99576707-30c1c700-298f-11eb-9414-64725f0a92a6.png)

**Comment by bsavery** [comment]
Please understand developers are not artists.  It's saving us a bunch of time to just attach a scene vs a screenshot!

**Comment by djtutorials** [comment]
Here is a session for you:
https://drive.google.com/file/d/1iG_XCrk7dhLHuuSFpatpodyRz0fGdCpA/view?usp=sharing

**Comment by ARozghon** [comment]
Thank you for your request. Noise node not supported yet by Full render

**Comment by bsavery** [comment]
I'm going to change the title to "noise texture node supported" ok?

**Comment by bsavery** [comment]
We are working on this now.

**Comment by bsavery** [comment]
FYI we support the noise texture in RPR 2 now, so I will close this, but we are adding more noise features / options in the near future
