### ISSUE TITLE
ProRender for Blender Windows v2.5.3 Adapt Viewport Resolution not accessible

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#138]
Hello!

I have been meaning to mention this- it appears that the viewport adapt viewport resolution is now not available in the Full (2.0) but available in the Legacy renderer but doesn't seem to do anything.

You guys are doing an amazing job on this engine. The render speed and clarity in the 2.0 renderer is astounding. Thank you!

![image](https://user-images.githubusercontent.com/65964807/99577240-ea209c80-298f-11eb-9347-46c9b881e18e.png)

**Comment by bsavery** [comment]
In RPR2 we actually scale down the resolution while the viewport is changing (this is the blocky view when moving the camera), but we haven't done the full viewport scaling yet.

**Comment by bnagirniak** [comment]
Adapt viewport resolution for Full render mode is in our nearest plans. It'll be coming soon.

**Comment by bsavery** [comment]
Fixed in latest builds (see weekly releases)
