### ISSUE TITLE
AMD ProRender for Blender Windows v2.5.3 Adaptive Subdivision not available on Full or Legacy

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#139]
Not sure if this is a coming feature or not but I thought I would mention it. The adaptive subdivision button appears to not be in both the Legacy and Full modes. If this is coming or has been moved somewhere else, please let me know!
![image](https://user-images.githubusercontent.com/65964807/99577549-61eec700-2990-11eb-8f90-d8e5ded6e1fe.png)

**Comment by bsavery** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/blob/master/Changelog.md#known-issues Should be in known issues!
