### ISSUE TITLE
Prorender for Blender V2.4.11Experimental 2.0 Renderer Can't select CPU rendering device

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#14]
When switching to Full Experimental renderer, the option to select the CPU as rendering device is disabled.

Video showing issue:
https://youtu.be/uo3uSafRFPk?t=571

RPR Version: 2.4.11

Blender version: 2.82a

System:
AMD Ryzen 3960x Threadripper
Radeon VII (x2)
64GB RAM
Gigabyte Auros 1TB M.2 NVME SSD

**Comment by bsavery** [comment]
BTW you have a great system setup!  We'll get this fixed.

**Comment by djtutorials** [comment]
> BTW you have a great system setup! We'll get this fixed.

Thank you! The motherboard is the ASROCK TRX40 Creator too. One day I will have 4 GPUs....

**Comment by bsavery** [comment]
See my comment in the other issue, I fixed the UI.  If you switch to full (rpr 1.0) select CPU + GPU then back it should work.
