### ISSUE TITLE
Empty materials in that seem unused render pink "unknown"

### ISSUE THREAD

**Issue by bsavery** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#141]
https://cloud.blender.org/p/gallery/5f4d1791cc1d7c5e0e8832d4 example

**Comment by bsavery** [comment]
example "metal_shiny" material

**Comment by ARozghon** [comment]
![image](https://user-images.githubusercontent.com/68949117/99796586-6d7bf280-2b36-11eb-975f-814a14247bb9.png)
shiny metal not connected to shader output in Shader editor

**Comment by ARozghon** [comment]
do we need to change "purple error"?

**Comment by bsavery** [comment]
These are "empty" materials.  Somehow Blender handles them correctly.  We do this error material where maybe we shouldn't

**Comment by bsavery** [comment]
So more update.  EEVEE acts like we do.  I'm not sure what's right or wrong here and don't feel strongly one way or another.
