### ISSUE TITLE
Medium render mode not working on switching (4GB VRAM)

### ISSUE THREAD

**Issue by abcd-4278** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#143]
Hi, In the new release, the Low and High quality render mode are finally working on my laptop (4GB VRAM), but the medium render mode is not working due to some reasons. Blender quickly closes, but I somehow managed to take a screenshot of the debugging.
Here it is:
![radeon prorender medium render](https://user-images.githubusercontent.com/70913031/99906868-7bc93a80-2cff-11eb-8f01-4a3d3e7e20f5.png)

I want to say thanks for improving this nice rendering engine so far.

**Comment by bsavery** [comment]
Did you enable the "low memory" mode available when you select medium / high render modes?  This is specifically for cards like yours.

**Comment by abcd-4278** [comment]
OK I've got some pretty interesting results. When I use the **medium render mode at first** (enabling 4GB VRAM), then rendering actually works and if I then **change to any OpenCL render mode** (Full and Legacy) and **back again to medium**, then also the rendering works.
But If I **choose another render mode at first**  OR   **I first select the medium render mode** and then **change to any of the other Vulkan render modes** (Low and High) and **back again to medium**, then rendering doesn't work



Please apologize for my bad English. I hope you understood what I tried to say.
Also I needed to keep rotating or moving my viewport, otherwise the hybrid render modes crashed most of the time

**Comment by bsavery** [comment]
Ok.  I think the "mode switching problem" is the same as this?  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/29

**Comment by abcd-4278** [comment]
Well no, It was happening when I was rendering the default cube. I tried to test on the paviliion scene, but there the all the hybrid render modes were crashing after a few switching which I think is due the the low memory of my GPU.

**Comment by bsavery** [comment]
Ok so I'm going to close this issue which I claim is fixed in #212 Other issues with hybrid are handled in other linked ones.
