### ISSUE TITLE
Full performance 3X slower than legacy mode

### ISSUE THREAD

**Issue by Aliprandini** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#145]
Something wrong with "Full" mode VS "Legacy".
In almost scenes with the same min. & max. samples there Full mode is 3X slower than legacy mode. In some scenarios it make useless RX 5700 XT (metal) even compare to 8-core intel processor with Cycles CPU.

OS X: Big Sur.
RX 5700 XT
3.0.2 RPR + Blender 2.91b

**Comment by MakramDaou** [comment]
You can't really compare Full & Legacy render times with the same sample settings. Full (RPR2) has way better ray conversion which results in less noise than legacy with the same number of samples. For example Full @ 500 sample will get better result than Legacy @ 2000 samples. Also Full doesn't support adaptive sampling yet (min/max) so it's always rendering the max number of samples that you setup in the render settings.
