### ISSUE TITLE
Prorender 3.0 Official release Tri-Planar Normal Map Issue

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#147]
The tri-planar mapping node works well with other nodes, however, it appears that when mapping to a normal mapping node, the normal map is attempting to use the UV coordinates instead of the designated Triplanar coordinates. I'm fairly certain this is a similar issue or paired with the Anistropic issue I previously reported.

Normal Map Image view through texture node:
![image](https://user-images.githubusercontent.com/65964807/100313851-496f4580-2f6a-11eb-861c-cff15b714879.png)

View through the Normal Map node (You can see the creasing):
![image](https://user-images.githubusercontent.com/65964807/100313909-6277f680-2f6a-11eb-92f5-5aa133b6701f.png)

Blender File:
https://drive.google.com/drive/folders/1j3CCB2bP-hTuNuucYbqtEFE86E7iG73d?usp=sharing

System:
Windows 10
Blender 2.9
Ryzen 3960x
Radeon Vii (x2)
64GB RAM

**Comment by ardraeiss** [comment]
Confirmed. Thank you for the scene.

**Comment by bsavery** [comment]
Hi @djtutorials can you retry this?

**Comment by bsavery** [comment]
@djtutorials or use the "box" mapping on the Image texture node since we support that now in latest build
