### ISSUE TITLE
Full Experimental rendering uses 50% of the CPU during rendering

### ISSUE THREAD

**Issue by MakramDaou** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#15]
I don't know if this is a bug or how RPR2.0 is supposed to work but rendering in Full experimental mode is a lot slower than Full. More importantly its using half of the CPU ressources (while using less GPU resources that RPR 1) when rendering is set to only be done on the GPU.

See screens below

Specs: Windows10 1909, 
i7 6700K, 
32GB Ram, 
Radeon VII
500GB NVMe M2

Full Experimental:
![rpr2gpu](https://user-images.githubusercontent.com/46979415/82948202-a5e4ae80-9fa1-11ea-887e-b5a9cbb7ab90.jpg)
![rpr2gpu2](https://user-images.githubusercontent.com/46979415/82948249-bbf26f00-9fa1-11ea-9ac5-ecfb9a1accbc.jpg)

Full:
![rpr1GPU](https://user-images.githubusercontent.com/46979415/82948370-f3611b80-9fa1-11ea-8077-2d363d9cf162.jpg)

**Comment by AtsushiYoshimura0302** [comment]
@MakramDaou 
Hi, Thank you for reporting.
First, Windows Task Manager can't catch the truth GPU occupancy by OpenCL. So you can forget the GPU usage on Task Manager.

And CPU usage could be higher than 1.0 so far even if you just use GPU rendering. There are optimization rooms on future releases, the CPU usage differences come from the 2.0 new architectures which include less GPU memory usage on high-resolution rendering, etc.

**Comment by MakramDaou** [comment]
@AtsushiYoshimura0302 
You're welcome. 
That's what  was suspecting but good to have confirmation (new out-of-core architecture requiring more CPU).
Hopefully the other issue I reported (https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/4) will be fixed soon.

Cheers

**Comment by AtsushiYoshimura0302** [comment]
Also, I'll check it.

Best

**Comment by bsavery** [comment]
Hi there.  I think it's just a UI issue (that it's greyed out when RPR 2.0 is enabled.)  If you switch to "Full" (rpr 1.0) select CPU + GPU then switch back it should render with both.  Either way, the linked PR fixes the UI.

**Comment by MakramDaou** [comment]
@bsavery 
My "issue" was/is that RPR2.0 uses half the CPU resources even when set to only GPU rendering. But as @AtsushiYoshimura0302 said this may very well be related to the out-of-core nature of 2.0.

**Comment by bsavery** [comment]
I see.  Yes @AtsushiYoshimura0302 says is true and makes sense.

**Comment by bsavery** [comment]
So if you feel this is settle, please close!
