### ISSUE TITLE
Transparency setting is not working - Radeon ProRender for Blender 3.0

### ISSUE THREAD

**Issue by Aloris041** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#150]
In Blender v2.83.9
Transparency setting is not working (Render Properties->Film->Transparent Background).

I use RadeonProRenderForBlender_3.0.2_Windows.zip
In 2.5.1 it works.

Photo - https://ibb.co/VjSDn35

**Comment by bsavery** [comment]
Hi.  I'm going to close this as it's a duplicate of https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/72

Please subscribe to that issue for updates.
