### ISSUE TITLE
ProRender 3.0 High setting throws error after render is complete Environment Lighting

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#153]
Hi All,

High setting throws an error after render completes. This seems to only happen if you have an environment light IBL image map used in the render scene.

Steps to reproduce:
Open default cube
Add environment light IBL
Switch render mode to High
Render Image

Snapshot:
![image](https://user-images.githubusercontent.com/65964807/101085538-6b695900-3564-11eb-8e56-1c783b54fa35.png)

File:
https://drive.google.com/drive/folders/1J-2sxJXQP8l9tRjU48btUV0AKdr33JqL?usp=sharing

System:
OS- Windows 10
Blender: 2.91
ProRender: 3.0 Release
GPU: Radeon VII x 2
CPU: Threadripper 3960x
RAM: 64GB
Drive: 1TB Auros M.2 NVME

**Comment by bsavery** [comment]
Thanks.  I can see that here too.  You can disable the "Anonymous usage statistics" for now as a workaround.

**Comment by bdjonesca** [comment]
I see Low Med and High all throw an error in the render view but not in editor/preview render. And, in preview render the object positions all rise (in Z)  and do not match a selected objects outline position in the Camera view, this is not true when not using the camera object

**Comment by ardraeiss** [comment]
What do you mean exactly by "Preview render"? In Blender Preview means the Material/Light/World settings tab Preview panel.
Did you mean "Viewport Shading" mode "Material Preview"/"Rendered" modes?

**Comment by bdjonesca** [comment]
Sorry, I came from the C4D world prior to moving to Blender when 2.8 came out. My comment should read -
"I see Low Med and High all throw an error in the Render window (F12 render) but not in Viewport:Viewport Shading/Rendered." **- This is still true**
"And, in Viewport:Viewport Shading/Rendered the object positions all rise (in Z) and do not match a selected objects outline position in the Camera view, this is not true when not using the camera object.
**- this is *not* still true at least with a quick test in 3.0.9 or it takes a series of actions to cause and I can't repeat it now.**

**Comment by bnagirniak** [comment]
This bug will be fixed at core hybrid side, hybrid team is notified about this issue.

**Comment by bnagirniak** [comment]
Fixed in #212
