### ISSUE TITLE
3.0.8 - Denoiser error - Render grey

### ISSUE THREAD

**Issue by Dprasni** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#155]
![image](https://user-images.githubusercontent.com/46623153/101243454-d059b600-3700-11eb-9ce7-234cea6fd45f.png)
![image](https://user-images.githubusercontent.com/46623153/101243472-e5364980-3700-11eb-8cd3-ee3ec90bce74.png)

The following error is displayed when turning denoiser on - "Machine Learning" AOV checkbox on/off (both same resault)

RPR - Full (and Legacy also)
Global illumination

Blender 2.91 Stable Release standalone installer

**Comment by bsavery** [comment]
What os and gpu

**Comment by Dprasni** [comment]
Sorry forgot to write that down, its

W10 20H2 - RX 5700 XT

**Comment by ARozghon** [comment]
Hi, could you share this scene, if possible, we will recheck this issue on the same GPU and try to reproduce the same bug. 

Thank you

**Comment by Dprasni** [comment]
[struts_prorender.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5651455/struts_prorender.zip)

The exact GPU is RX 5700 XT Sapphire Nitro+

**Comment by ARozghon** [comment]
![image](https://user-images.githubusercontent.com/68949117/101338480-b3022480-3885-11eb-84b1-69ca9723e40c.png)
no errors from my side with Legacy and Full

**Comment by Dprasni** [comment]
Hmmm weird,

Im running Adrenalin 2020 Edition 20.11.3 , perhaps this helps ?

**Comment by bnagirniak** [comment]
Probably problem is in drivers, I'll ask ML denoiser team for more info.

**Comment by MattGrdinic** [comment]
Hi all, have something similar, only I get a **black screen** on final render when using the "Machine Learning" denoiser  (viewport is unaffected). This happened with the legacy versions and now with the newest versions of each as of late December 2020. Running macOS Catalina with a 5600 XT. 

The terminal shows what I assume is the standard calling path:

INFO: Using Metal device: AMD Radeon RX 5600 XT
[MSG  @RIF]: Loading model: /Users/matt/Library/Application Support/Blender/2.91/scripts/addons/rprblender/data/models/denoise_c3_hdr_gamma_2.5.pb

For what it's worth, the mention of hdr in the model seems a bit odd, as I do not run an HRD screen. Probably nothing, but wanted to note. 

Also, this behavior is independent of the scene being rendered, materials, etc. To recreate I can simply create a single plane and render.

**Comment by bsavery** [comment]
Are you using the "color only" option checked or not?
