### ISSUE TITLE
2D projection on 3D object doesn't work

### ISSUE THREAD

**Issue by Aliprandini** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#162]
RPR 3.0.9 / Blender 2.9x
Big Sur / 5700 XT

None of the methods to project 2D image on object with a 3D texture vector works, beside Flat method.
![Screenshot 2020-12-12 at 12 31 47](https://user-images.githubusercontent.com/73755453/101979375-1a4d1980-3c76-11eb-9075-e903b95275b8.png)

**Comment by ardraeiss** [comment]
Image Texture projection options other than "Flat" aren't support yet.
Supporting them is in future plans.
