### ISSUE TITLE
When will be resolve  textures issues with transparency on an object surfaces? When will be transparent background rendering with RPR 2?

### ISSUE THREAD

**Issue by Aliprandini** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#163]
1) When will be resolve  textures issues with transparency on an object surfaces? There are a lot of issues with textures transparency like pixelating, color stepping etc.

![Screenshot 2020-12-12 at 12 34 25](https://user-images.githubusercontent.com/73755453/101979595-c3484400-3c77-11eb-9461-e82f93746dd6.png)

2) When will be transparent background rendering with RPR 2? Transparent Background option works only with RPR Legacy mode at this moment.

RPR 3.0.9 / Big Sur / 5700 XT / Blender 2.9x

**Comment by ardraeiss** [comment]
What is exactly the material nodes setup you are using?

**Comment by Aliprandini** [comment]
> What is exactly the material nodes setup you are using?

[RyzenGraphic_27_prorender.blend.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5688320/RyzenGraphic_27_prorender.blend.zip)

**Comment by ardraeiss** [comment]
Ouch. It crashed my Blender on load... even without RPR plugin.

**Comment by Aliprandini** [comment]
And what I should to do? There was an official AMD .blend file while Ryzen advertisement. So, RPR developer couldn't open official AMD .blend file? Why I haven't this problems?

![Screenshot 2020-12-14 at 21 13 52](https://user-images.githubusercontent.com/73755453/102112551-4cff3980-3e51-11eb-9a98-fb0779478245.png)

Legacy mode do edge render correct, while "Full mode" render a lot of artefacts. 

Btw, If i have "Background Override" option with an .PNG file (any scenes), I have the same artefacts problem on background (color stepping/color bending) in "Full mode" but none of those in Legacy.

**Comment by ardraeiss** [comment]
The correct Blender version to open the source scene is 2.92.0 Alpha.
Blender 2.90/2.91 can't load it.

**Comment by ardraeiss** [comment]
As for the issues with the "fire loop" image itself - work is in progress.
