### ISSUE TITLE
Add support for Principled Volume to RPR2

### ISSUE THREAD

**Issue by aledbrown** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#164]
One of the new features in Blender 2.91 is a very nifty Volume to Mesh Modifier which allows for extremely simple volume object creation from any existing mesh shapes.

Will this type of volume render be added to RPRv2? At the moment it renders as an invisible object. It does not crash but does not show anything.

I have attached a sample .blend file. This was setup with RPRv2 (plug in v3.0.9 dev) but is set to Cycles to demonstrate how it works. Switching engine back to RPR yields no render.

[Volume to Mesh RPR2 Test.blend.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5683403/Volume.to.Mesh.RPR2.Test.blend.zip)

This is Cycles:
<img width="1352" alt="cycles" src="https://user-images.githubusercontent.com/690500/101989297-55ac1000-3c97-11eb-8cdc-9f5fab8aff29.png">

This is RPRv2 (plug v3.0.9):
<img width="1352" alt="rpr" src="https://user-images.githubusercontent.com/690500/101989301-5e9ce180-3c97-11eb-8067-59d9dddb126a.png">

Yes, I was going to make a Snowman! Sample file was renamed ;)

**Comment by bsavery** [comment]
So the main thing I think is we need to add support for Volumes in rpr2.  This should work in legacy mode yes?

**Comment by bsavery** [comment]
Should be supported in the next version of RPR.  But the modified should work with other shaders.

**Comment by ARozghon** [comment]
available in RPR 3.2.2 (core 2.4.4) and will be improved with core 2.2.5 and later
