### ISSUE TITLE
Blender crashes when using ProRender

### ISSUE THREAD

**Issue by hmandal** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#173]
- ProRender version: 3.0.8
- Blender version: 2.91.0
- OS: Windows 10.0.19042.685
- Issue existing in open/closed github issues: false

### ProRender configuration:
- Rendering Engine: Radeon ProRender
- RPR Render Quality: Low (same issue with all other choices too)
- Render Mode: Global Illumination (same issue with all other modes too)
- Render Devices: AMD Radeon HD 8600M Series
- Use 4GB memory: true
- (Rest all setting are the default ones)

### Steps to reproduce:
1. File -> New -> General
2. Set Rendering Engine to Radeon ProRender
3. Observe AMD Radeon HD 8600M Series is checked by default
4. Set viewport shading mode to Rendered
5. Blender crashes.

### Observation:
- Blender crashes on trying to render in Rendered mode or using F12.
- In viewport shading solid mode it works fine.
- In viewport shading wireframe mode blender doesn't crash but I don't see proper wireframe.
![image](https://user-images.githubusercontent.com/6329485/102924190-18c1f380-44b7-11eb-9c3d-27dd682fed0b.png)
![image](https://user-images.githubusercontent.com/6329485/102924294-473fce80-44b7-11eb-874a-a362f730c475.png)
![image](https://user-images.githubusercontent.com/6329485/102924355-68a0ba80-44b7-11eb-9152-e7e85a55c5df.png)
![image](https://user-images.githubusercontent.com/6329485/102924393-7d7d4e00-44b7-11eb-9011-c4d280b57da6.png)

Here's the crash video:
https://user-images.githubusercontent.com/6329485/102925373-414aed00-44b9-11eb-8e90-e81a6f96869f.mp4

### Expected behaviour:
Blender should render the scene properly using ProRender.

Please find the attached log file from %TEMP% using regular Blender exe

[blender.crash.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5731536/blender.crash.txt)

Logs generated using blender_debug_log.cmd:
[blender_system_info.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5731555/blender_system_info.txt)
[blender_debug_output.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5731556/blender_debug_output.txt)

Logs generated using blender_debug_gpu.cmd:
[blender_system_info.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5731560/blender_system_info.txt)
[blender_debug_output.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5731561/blender_debug_output.txt)

**Comment by bnagirniak** [comment]
Look like your hardware isn't supported. Supported hardware is listed here https://www.amd.com/en/technologies/radeon-prorender-blender.
Does ProRender works in CPU mode?
