### ISSUE TITLE
Live preview freezes when changing material properties

### ISSUE THREAD

**Issue by 4nker** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#174]
In Windows 10.. When live viewport render is set to Full, and changes are made to materials quickly.. sometimes Blender freezes. If left, it does not become responsive again.

**Comment by bsavery** [comment]
I will claim that with the latest changes (download weekly beta release) to improve the viewport speed this is much better.  Notice that if you get to > 32 samples there is a bit of a lag because after 32 samples it adds 32 samples per "pass".
