### ISSUE TITLE
Blender crashes when rendering with certain passes enabled

### ISSUE THREAD

**Issue by nate-brs** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#179]
_macOS Big Sur 11.2 Beta, Blender 2.91.0, RPR 3.0.15, "Full" method (no problem in "Legacy")_

When rendering with certain passes enabled, Blender crashes after building the scene. No problem in viewport render.
Default scene used, with the default Principled converted to Uber. Default render settings too.
Here's a list (checked) of the passes that cause crashes:
![unknown](https://user-images.githubusercontent.com/60856369/104215757-823f7d00-5439-11eb-82df-cf932ae9c476.png)

**Comment by bsavery** [comment]
Please try latest version.  Seems to be working now
