### ISSUE TITLE
UV are totally Offset when i turn into Full rendering

### ISSUE THREAD

**Issue by Notorious-69** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#18]
Hi AMD fam' !

Big problem since 2.3.4 version, the UV are totally offset.

I using RPR on Blender.
My PC hardware : Windows, RX580, Ryzen 7 2700 3.9Ghz, 16GB ram

FULL : ![image](https://user-images.githubusercontent.com/65624014/83018199-2bf60900-a025-11ea-9a13-78205e400fc9.png)

HIGH : 
![image](https://user-images.githubusercontent.com/65624014/83018345-6bbcf080-a025-11ea-85e9-37517aacbb6d.png) don't look at the interior texture

EDIT SCENE : https://we.tl/t-MBDIwQMzIN

**Comment by bsavery** [comment]
Can you attach a scene?  This might be hard to reproduce.  Remember us developers aren't artists!

**Comment by Notorious-69** [comment]
Message Edited

**Comment by bsavery** [comment]
Hi There.  We looked it seems this is fixed in RPR 2.0, and it must have been around in RPR 1.0 for a while.  Unfortunately I think we're trying to focus forward now.  Can you use RPR 2.0?

**Comment by Notorious-69** [comment]
Yeah problem are here since 2.3.4 version.

CAn u send me the 2.0 RPR ?

**Comment by bsavery** [comment]
the latest build has it available on windows.  Select Full (experimental) mode in the render settings

**Comment by Notorious-69** [comment]
Answers you in discord, but maybe you prefer here ?

**Comment by bsavery** [comment]
Hi @Notorious-69 I have said a few times here to try this in rpr 2.0.  If you download the latest in https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases and install that, switch the render mode to RPR 2.0

**Comment by Notorious-69** [comment]
Hi bsavery

I have test in rpr 2.0 but I have few other problem of luminosit.

No worry I continue to render with cycles :(

**Comment by bsavery** [comment]
Can you post those issues with luminosity??  Otherwise I'm closing this issue.
