### ISSUE TITLE
Pro Render Crashes After Enabled

### ISSUE THREAD

**Issue by clownbaby666** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#189]
Hardware:
iMac (Late 2017)
OS High Sierra 10.13.6
Razor Core X eGPU
Sapphire Vega 56

ProRender: 3.08

Attempted on Blender 2.9 and 2.83 (default set up)

Issue: 
Zip file will install but as soon as plug in is enabled, app immediately crashes 100% of the time. 

Others having this issue as well, dated 1 and 2 weeks ago:
https://community.amd.com/t5/blender-discussions/blender-crashes-every-time-i-try-to-enable-rpr/td-p/382730

Are there other versions of ProRender to resort to in the meanwhile?

**Comment by bsavery** [comment]
We only support macOS mojave and later.  Sorry.
