### ISSUE TITLE
High RAM usage compared to Cycles

### ISSUE THREAD

**Issue by amanda-santini** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#191]
Hi!

I've been doing some testing with this render engine and I'm absolutely loving it. 
However, I have one complaint: It uses way too much RAM compared to Cycles.

I've gathered two examples. The fist is an old scene of mine, and the other a more recent scene. In both examples, RAM consumption is *at least* twice as big as Cycles.

Scene 1 - Cycles 64 samples https://i.imgur.com/mZ1s84h.jpg
RAM consumption (Blender): 1.7 GB https://i.imgur.com/4vwsKhG.jpg

Scene 1 - Radeon Pro Render https://i.imgur.com/4wTA5yH.jpg
RAM consumption (Blender): 3 to 3.5 GB: https://i.imgur.com/gfjsXVL.jpg

------------------------------------------------

This trend is seen across all the projects I try to render with RadeonPro.

------------------------------------------------

Scene 2: Cycles: https://i.imgur.com/3tAA7Ry.jpg
Ram consumption: 1.7 GB https://i.imgur.com/pT3nJce.jpg

Scene 2: Radeon Pro: https://i.imgur.com/BBukmWN.jpg
RAM consumption: 3.5 GB https://i.imgur.com/QkYzEgY.jpg

-------------------------------------------------

However, it doesn't end there. On this second scene, if I cancel the render or let it finish 100%, RAM consumption can go as high as 10 GB https://i.imgur.com/hIZKAnt.jpg

-------------------------------------------------

I'm using mostly the default render settings.

My PC:

Intel i5 3470
AMD RX 570 4 GB
16 GB of DDR3 RAM

Is there anything I can do to keep the same render quality but reduce RAM consumption?

**Comment by amanda-santini** [comment]
Perhaps it's worth noting that Radeon Pro doesn't use much of my VRAM, only around 25%.
Maybe if more memory was shifted towards VRAM, RAM consumption wouldn't be too high?

https://i.imgur.com/Zo5JOn7.png

**Comment by bsavery** [comment]
Hi Amanda.  

Thanks for the interest!  So part of this is due to Cycles being built in to Blender where we are not.  Blender with cycles built in is using a lot of the data directly from Blender, whereas ProRender we have to translate from Blender to ProRender (as do all render addons).  So in essence there could be 2 copies.  

That said if you think there's a scene where we're using too much please send the scene.  

There is one more option too which is useful if you have a batch render you want to do.  You can export a .rpr file (File-> export) and then render it with a command line utility we have following this instructions:  https://radeon-pro.github.io/RadeonProRenderDocs/en/sdk/command_line_tools.html This would allow you to close blender and save the "double" memory.

**Comment by amanda-santini** [comment]
Hi @bsavery !
Thank you for responding.

Awh, that's too bad. I'm hoping someday your amazing render can be integrated into Blender by default.

Cheers,
Amanda

**Comment by bsavery** [comment]
Hey @amanda-santini if you can attach that scene that is using 10gb of ram though I'd like to take a look!

**Comment by amanda-santini** [comment]
Hey @bsavery . Sadly that scene is not available for download. I'm back on Linux and now it used even more RAM, almost maximizing my 16 GB and then crashing.

I'll do some testing with some older scenes and will reply here with both Cycles and Radeon Pro versions.

![image](https://user-images.githubusercontent.com/3147833/106535699-92e19100-64d5-11eb-9b85-6a3838312be1.png)

**Comment by amanda-santini** [comment]
@bsavery Any way I can privately send you two files?

**Comment by amanda-santini** [comment]
In the mean time:

Scene in Cycles: 1.9 GB of RAM https://i.imgur.com/0gwQIJ4.png
Render result: https://i.imgur.com/xKfD5ut.png

Scene in Radeon Pro: 3 GB of RAM https://i.imgur.com/72MMKRD.png
Render result: https://i.imgur.com/3zO6EDW.jpg

Somehow the denoiser isn't working on Linux.

**Comment by bsavery** [comment]
> @bsavery Any way I can privately send you two files?

ah sorry!  My email is brian dot savery at AMD.com

**Comment by bsavery** [comment]
another thing I want to mention is that if you're rendering at huge resolution I would expect RPR to use much more memory.  We allocate the whole frame buffer where Cycles does just tiles.  You can turn on tiled rendering in our settings though.

**Comment by RisingUpGames** [comment]
Sorry but I don't have the option to enable tiled rendering. It's greyed out. 
![image](https://user-images.githubusercontent.com/29588715/107429824-28e37000-6b03-11eb-975d-c9979fbe82b5.png)

**Comment by amanda-santini** [comment]
Sorry but I don't have the option to enable tiled rendering. It's greyed out.
![image](https://user-images.githubusercontent.com/3147833/107429981-5c25ff00-6b03-11eb-9edf-7a46e6b95845.png)

**Comment by bsavery** [comment]
Using the latest from https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.0.26 will allow this.

**Comment by amanda-santini** [comment]
Still not possible, only if I use "Legacy" quality instead of full.
https://www.youtube.com/watch?v=nwJI_RlY2g8

And if I try to render the scene I sent you, using Legacy, the same memory behavior is observed (see image bellow)
![image](https://user-images.githubusercontent.com/3147833/107433831-a6f64580-6b08-11eb-9390-2bd0c5fa881e.png)

**Comment by bsavery** [comment]
Hi Amanda.  please check the version in that "about" section.  If you don't see tile render available you don't have the latest version.  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/pull/182 Merged a few weeks ago enables tiled rendering.  

On windows it seems you have to disable the old plugin, restart blender, uninstall and then reinstall.  (This is a blender bug btw that you have to do this).

**Comment by amanda-santini** [comment]
Hey @bsavery , thank you for your time, I really appreciate it. It worked.

Sadly RAM consumption is too high for me, even with tiled rendering.
Unfortunately, I don't think RPR is going to be my choice of render, at least not until I have way more RAM.
Other than that, I really love it and would be proud to use it on a daily basis.
But for now I need to stick with Cycles and Eevee as they consume less memory and don't need external commands.

Cheers!

**Comment by bsavery** [comment]
Thanks for taking a look and sending a test case!  We'll improve where we can.
