### ISSUE TITLE
Bi-Directional Path-Tracing support?

### ISSUE THREAD

**Issue by maskerman** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#195]
Hello,
     I've been doing some testing with this render engine and the result seems better than cycles.
     However, I have one question: Are there any planned provide "Bi-Directional Path-Tracing" in rpb? cycles onlye has "Path tracing", but it's not good when used in "Interior decoration".

**Comment by bsavery** [comment]
Hi there!  Good question.

So the problem you're describing is basically how do we solve "hard" light paths.  Stuff like this:  
![image](https://user-images.githubusercontent.com/1892220/106294110-9d650780-6203-11eb-819d-2909709ce259.png)

Forward path tracing will eventually solve these with random samples but it will take a LONG time to do.  This is a problem we want to solve better in ProRender.  Bi-directional path tracing is one technique but there are others as well.  

So to answer your question, yes, this is something we are looking to address in the future, but might be later this year at earliest, and may not necessarily be bi-directional path tracing.

**Comment by maskerman** [comment]
Thanks a lot! hope we can see it ASAP.
