### ISSUE TITLE
Why I can't use low/medium/hight render mode?

### ISSUE THREAD

**Issue by maskerman** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#196]
![image](https://user-images.githubusercontent.com/2068759/106351786-52d5af00-6319-11eb-800f-aaf967ce6dff.png)
Fist I use amd 3800x+rtx2060 super, and when I test them, rbp report create context error. then I use 3800x+6800xt , but rbp report the same error.

How to solve it? 
![image](https://user-images.githubusercontent.com/2068759/106351959-7ea56480-631a-11eb-8a6a-baed5ce51a2a.png)

blender: 2.90
prorender version:3.0.23
os :win10 1909

[rprblender.log.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5897649/rprblender.log.txt)

**Comment by bsavery** [comment]
Can you attach a scene?

**Comment by maskerman** [comment]
[4.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5901304/4.zip) here is a scene. open it ,then select rendermode 'low' ,then render it, rbp will report a error.

**Comment by bsavery** [comment]
Ah ok this is the same as https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/153

Disable statistics as mentioned in that thread.

**Comment by maskerman** [comment]
But I tried this method and nothing changed.
![image](https://user-images.githubusercontent.com/2068759/107104903-b488a280-685e-11eb-939f-1cb4f1ead691.png)

**Comment by bsavery** [comment]
Technically that is a different error so I wouldn't say "Nothing changed".  But we'll look into it

**Comment by bnagirniak** [comment]
Fixed in #212
