### ISSUE TITLE
Mirror reflection doesn't reflect correctly

### ISSUE THREAD

**Issue by Flameboo** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#198]
I have a question regarding the Mirror material built in pro render library or even the one I generated by myself. If you look at the right side, there are some mirrors on the wall and the problem with it, I can’t seem to find a solution to make it crystal clear just like what mirror supposed to be. I tried it on a new file but the problem still persist. I tested it and the far monkey from the plane got blurred out than the close one, which I believe it should not behave like that.
![Screenshot (5)](https://user-images.githubusercontent.com/78478666/106737192-3c567e80-65cb-11eb-81ea-ce7380b76c98.png)
![Screenshot (6)](https://user-images.githubusercontent.com/78478666/106737201-3eb8d880-65cb-11eb-8644-17ee2d5b8dd4.png)

**Comment by bsavery** [comment]
Try setting diffuse weight to 0.  Mirrors normally don't have diffuse.

**Comment by Flameboo** [comment]
> Try setting diffuse weight to 0. Mirrors normally don't have diffuse.

Tried everything including that

**Comment by bsavery** [comment]
I see, I can see this a bit too, It seems sharper with "legacy" mode.  Will look into it more.

**Comment by maskerman** [comment]
Is there any progress ? I try the latest version, It seems nothing changed...

**Comment by bsavery** [comment]
Which version did you test?  The newer one should have fixes for reflections with 0 roughness

**Comment by bsavery** [comment]
Should be fixed in latest version.  Please reopen if you still see it.
