### ISSUE TITLE
Texture issues still persist with PRP 2

### ISSUE THREAD

**Issue by Aliprandini** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#200]
Texture issues still persist with PRP 2 under windows 10 or Big Sur.
Blender 2.92 / 5700XT

![untitled2](https://user-images.githubusercontent.com/73755453/106898634-df171600-670d-11eb-9a8b-db3d06453551.jpg)
[RyzenGraphic_27_prorender.blend.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5925950/RyzenGraphic_27_prorender.blend.zip)

**Comment by bsavery** [comment]
Thanks.  We're still improving a few texture related items in the renderer 2.0

**Comment by ARozghon** [comment]
was checking the current scene with RPR 3.1 and results: and this issue not fixed yet
![image](https://user-images.githubusercontent.com/68949117/113308198-9bf0b200-930e-11eb-8135-4438fe956c69.png)

**Comment by bsavery** [comment]
I actually think this relates to another issue someone reported.  Is the texture an sRGB?  Someone mentioned applying a gamma to the alpha channel.  It might be the case that alpha is not color corrected.

**Comment by bsavery** [comment]
So it appears the issue is that color mapping is not applied to the alpha channel.  As a workaround use a gamma correction on the alpha channel.  We'll look at in our core textures though.

**Comment by bsavery** [comment]
Should be fixed in latest version.  Please reopen if observed
