### ISSUE TITLE
Crash on Flatpak Blender 2.91 under Ubuntu 20.10 and AMD-GPU Mesa

### ISSUE THREAD

**Issue by iandol** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#203]
When I try to activate the 3.0.8 plugin I get a python error where the last line is:

```
OSError: libGL.so: cannot open shared object file
```
![Screenshot from 2021-02-09 16-01-52](https://user-images.githubusercontent.com/153905/107333519-91752180-6af0-11eb-9de5-8f370f11603d.png)

AMD's open source drivers are installed. I know Ubuntu 20.10 is not on the supported OS list (https://radeon-pro.github.io/RadeonProRenderDocs/en/plugins/blender/installation.html), so perhaps I just need to wait until you support Ubuntu above 18.04, or should it work even if not officially supported?

GPU: Radeon Pro WX5100 
Kernel: Linux cog5 5.10.3-051003-lowlatency #202012261630 SMP PREEMPT Sat Dec 26 16:39:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bsavery** [comment]
It sounds like a driver issue.  libGL should come with the driver.  How did you install it?

**Comment by iandol** [comment]
I'm using upstream AMD-GPU MESA (which comes with Ubuntu), though I use the latest version via oibaf PPA:

https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers

These are suggested by the AMD release notes https://www.amd.com/en/support/kb/release-notes/rn-amdgpu-unified-linux-20-45 

Blender is installed via Flatpak. And I downloaded V3.0.8 of the BlenderAddon from this github repo.

**Comment by bsavery** [comment]
So we're looking for OpenGL libs which should be installed but are not on your system for some reason.  

You will need to run https://askubuntu.com/questions/629692/how-to-install-libgl-files 

sudo apt-get install libgl1-mesa-glx

**Comment by meetdilip** [comment]
> So we're looking for OpenGL libs which should be installed but are not on your system for some reason.
> 
> You will need to run https://askubuntu.com/questions/629692/how-to-install-libgl-files
> 
> sudo apt-get install libgl1-mesa-glx

Hi, I tried this command and then attempted to enable ProRender through Preferences. It threw an error before and after shutdown + start.  #243 is my report, the current error is 

![Screenshot from 2021-04-02 21-22-33](https://user-images.githubusercontent.com/6965443/113431776-e6029200-93f9-11eb-88cb-1d1c0106f02e.png)

after running 

`sudo apt-get install libgl1-mesa-glx`

Thanks.

**Comment by bsavery** [comment]
hmm, so that error is still saying there is no libGL on your system (at least in the system libraries).

**Comment by meetdilip** [comment]
Is there anything we can do ?

**Comment by NPDan87** [comment]
Modules Installed (rprblender) from '/home/npdan/Downloads/RadeonProRenderForBlender_3.1.0_Ubuntu20.Release_March_2021.zip' into '/home/npdan/.config/blender/2.92/scripts/addons'
2021-04-03 12:14:22,453 INFO rpr.engine.init [140333140054528]:  RPR Core version: 2.2.1 build 0x924e5459
2021-04-03 12:14:22,472 INFO rpr.engine.init [140333140054528]:  Image Filters version 1.6.1 build 0xe4886697
2021-04-03 12:14:22,474 INFO rpr.default [140333140054528]:  rprsdk_bin_path: /home/npdan/.config/blender/2.92/scripts/addons/rprblender
Traceback (most recent call last):
  File "/home/npdan/Downloads/stable/blender-2.92.0-linux64/2.92/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/npdan/.config/blender/2.92/scripts/addons/rprblender/__init__.py", line 51, in <module>
    from .engine.viewport_engine import ViewportEngine
  File "/home/npdan/.config/blender/2.92/scripts/addons/rprblender/engine/viewport_engine.py", line 33, in <module>
    from rprblender.utils import gl
  File "/home/npdan/.config/blender/2.92/scripts/addons/rprblender/utils/gl.py", line 25, in <module>
    gl = cdll.LoadLibrary('libGL.so')
  File "/home/npdan/Downloads/stable/blender-2.92.0-linux64/2.92/python/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/home/npdan/Downloads/stable/blender-2.92.0-linux64/2.92/python/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libGL.so: cannot open shared object file: No such file or directory

same issue even after installing multiple attempts of libgl1 packages

**Comment by DagerD** [comment]
You can try to install following packages:

**Comment by DagerD** [comment]
You can try to install following packages:
```
libegl-dev (1.3.2-1~ubuntu0.20.04.1)
libgl-dev (1.3.2-1~ubuntu0.20.04.1)
libgl1-mesa-dev (20.2.6-0ubuntu0.20.04.1)
libgles-dev (1.3.2-1~ubuntu0.20.04.1)
libgles1 (1.3.2-1~ubuntu0.20.04.1)
libglvnd-dev (1.3.2-1~ubuntu0.20.04.1)
libglx-dev (1.3.2-1~ubuntu0.20.04.1)
libopengl-dev (1.3.2-1~ubuntu0.20.04.1)
libopengl0 (1.3.2-1~ubuntu0.20.04.1)
```

**Comment by NPDan87** [comment]
> 
> 
> You can try to install following packages:
> 
> ```
> libegl-dev (1.3.2-1~ubuntu0.20.04.1)
> libgl-dev (1.3.2-1~ubuntu0.20.04.1)
> libgl1-mesa-dev (20.2.6-0ubuntu0.20.04.1)
> libgles-dev (1.3.2-1~ubuntu0.20.04.1)
> libgles1 (1.3.2-1~ubuntu0.20.04.1)
> libglvnd-dev (1.3.2-1~ubuntu0.20.04.1)
> libglx-dev (1.3.2-1~ubuntu0.20.04.1)
> libopengl-dev (1.3.2-1~ubuntu0.20.04.1)
> libopengl0 (1.3.2-1~ubuntu0.20.04.1)
> ```

Thanks im not sure wich one did it but its working again for me thanks
