### ISSUE TITLE
Install just crashes Blender

### ISSUE THREAD

**Issue by rastarr** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#205]
Uninstalled a previous 2.x version and restarted Blender 2.91

Installed v3.08 of this plugin. As soon as I click the enabled checkbox, Blender crashes.

Does anyone have any ideas? Are there previous versions available to try?

**Comment by bsavery** [comment]
That's a bit odd.  What's your OS version and hardware?  I think there is some issue known if installing Blender from the steam store.  

Also:
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.0.26 is latest

**Comment by rastarr** [comment]
Thanks for the reply,

Running macOS 10.14.6
Intel i7, 64GB Ram and Radeon RX580 with 8G Ram.
The RadeonProRenderForBlender_3.0.26_MacOS.zip didn't install either (but I also d/l'd a RadeonProRenderForBlender_3.0.8_MacOS.zip initially)

Still crashes unfortunately with that v3.0.26 version


> That's a bit odd. What's your OS version and hardware? I think there is some issue known if installing Blender from the steam store.
> 
> Also:
> https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.0.26 is latest

**Comment by bsavery** [comment]
See this issue:  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/194

We don't currently support mojave, we might add in the future.

**Comment by bsavery** [comment]
Unfortunately we can't support mojave at this point due to drivers.  Sorry
