### ISSUE TITLE
In certain situations, Normal map is not applied

### ISSUE THREAD

**Issue by Conxt** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#209]
When the following conditions are met simultaneously, the Normal map gets disregarded:

- Refraction and Subsurface are disabled;
- A node is a source to the Normal map through a Bump node;
- The _same_ node is a source, directly or indirectly, to some other maps of the same shader (listed below).

The list of conflicting maps:

- Diffuse Weight
- Diffuse Color
- Backscatter Weight
- Reflection Metalness (Reflection Use Shader Normal disabled)
- Reflection IoR (Reflection Use Shader Normal disabled)
- Coating IoR
- Coating Thickness
- Coating Transmission Color
- Sheen Weight
- Sheen Color
- Sheen Tint
- Emission Weight

The test scene is attached: [Normal_mapping.blend.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6012481/Normal_mapping.blend.zip)

**Comment by bnagirniak** [comment]
Thank you, we'll look this issues.

**Comment by bsavery** [comment]
@arozghon

**Comment by ARozghon** [comment]
Bump and normal nodes works correct with all separate Normal channels in Uber Shader

**Comment by bsavery** [comment]
@Conxt Please check on latest with https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.1.0 and reopen if still an issue.
