### ISSUE TITLE
Non install

### ISSUE THREAD

**Issue by Ingapambi** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#210]
Prorender doesn't install.

Blender 2.93 Imac Pro Vega 64, Big Sur, RPR downloaded 3 days ago. 

When will Python 3.90 be adopted? The error msg included the inference this may be the cause.

**Comment by bsavery** [comment]
Yes. To be honest Blender institute is being _overeager_ adopting Python 3.9.  

Any plugin that is built for Python3.7 (all of them before this change) and use Python c-extensions will not load in the current Blender 2.93.  IMO this is them who broke this not us.  Python 3.7 is the standard in the VFX industry.  https://vfxplatform.com/ and now to support Blender 2.93 and 2.8X and 2.92 we have to build against multiple versions of python!

Anyway sorry for the rant.  By the time Blender 2.93 is out officially we will support it, but until then please complain to Blender not us ;) We were surprised by this change too!

**Comment by Ingapambi** [comment]
Oh hey, I have no complaints. I feel shafted by the Institute as well; a real disappointment.
 You guys are great.

Thanks.

**Comment by bsavery** [comment]
I wouldn't go so far as to say "shafted" but it's a decision that's hard to understand
