### ISSUE TITLE
Can't enable add-on in preferences in Blender 2.83, 2.91 or 2.92 on Mac 10.14.6

### ISSUE THREAD

**Issue by igitalot** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#214]
Trying to install the add-on, problem is the same if I try it in Blender 2.91 and 2.93 (below).  In 2.83 after clicking the Install Add-on on the ProRender zip file it doesn't even show up in the Add-ons list so I have no chance to try to enable it.

- I go to Blender preferences and click Install...
- I locate the "RadeonProRenderForBlender_3.0.8_MacOS.zip" file that I downloaded and click Install Add-on button
- it shows up in the add-ons list
- I click its checkbox to enable it Blender disappears immediately and I get a dialog "Blender quite unexpectedly"
- I click the "Report..." option and  a "Problem Report for Blender" log window appears.
The report is long but perhaps this first part is relevant/helpful (is ProRender incompatible with 10.14?) 
"System Integrity Protection: enabled
Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_CRASH (SIGKILL)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
Termination Reason:    DYLD, [0x4] Symbol missing
Dyld Error Message:
  Symbol not found: _objc_opt_new
  Referenced from: /Users/USER/Library/Application Support/Blender/*/libTahoe64.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
"

I saw someone saying they fixed a similar problem by putting a "Blender" folder in /Applications so I tried that but same problem.
I do not have Blender in /Application but in a different location/folder I created for apps I've installed, in case that's relevant.

I have no idea what else to try...any suggestions?

**Comment by Aliprandini** [comment]
Forget about mac os 10.14.x

The developers shouldn't spend time on the old version of OSX with bad metal/video drivers. Go to Catalina or Big Sur

**Comment by Aliprandini** [comment]
Also, go to GitHub release page: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases

Try to install latest developer version of RPR. 
The 3.0.8 seems the old version.

**Comment by igitalot** [comment]
Thanks for the reply & tip.  I downloaded RadeonProRenderForBlender_3.0.26_MacOS.zip and tried it on Blender 2.83, 2.91 and 2.92 it gives the same problem, after installing the zip file, when I click to Enable it Blender disappears.

**Comment by igitalot** [comment]
unfortunately I can't immediately upgrade my Mac OS since I depend on some legacy software which stops working in Mac OS > 10.14.  I hope to migrate away from the old software but it will take a while.

**Comment by bsavery** [comment]
Unfortunately as others noted we no longer support macOS 10.14.  Sorry.

**Comment by igitalot** [comment]
I looked through all the sys requirements I could before beginning this install and thought I was ok but apparently not.

The main entry page for AMD Radeon Pro Renderer,
https://www.amd.com/en/technologies/radeon-prorender-blender
says, "macOS® High Sierra 10.13.3 and up (10.13.4 required for external GPU support)"

And on the release notes for RPR,
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/blob/master/Changelog.md
it talks about using Mojave which although not a direct endorsement for 10.14.x did make me think it would work.

It would be good to update those pages for other people who might still have Mojave to save them the frustration and time loss trying to make it work.

**Comment by bsavery** [comment]
We'll update them.  Thanks.

**Comment by alanholding** [comment]
Just bumping as had the same situation as the OP and the system requirements on https://www.amd.com/en/technologies/radeon-prorender-blender are still showing as "macOS® High Sierra 10.13.3 and up (10.13.4 required for external GPU support)".
