### ISSUE TITLE
Unable to enable plugin on 2.92 , Getting WinError 126

### ISSUE THREAD

**Issue by mburger89** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#216]
Hi I getting an error when attempting to enable the Blender plugin on  blender 2.92. here is a screen shot of the error:
![Screenshot 2021-03-08 002409](https://user-images.githubusercontent.com/7642850/110297225-19433400-7fa8-11eb-833f-15e94a9ebf71.png)

and when I try to remove it I get another error this time in the blender console log this screenshot has the above error and the remove error.
![Screenshot 2021-03-08 003813](https://user-images.githubusercontent.com/7642850/110297472-5e676600-7fa8-11eb-9bbb-f1ac4f39f180.png)

I am on Windows 10 home 64 bit, with and amd cpu and gpu

Any help would be greatly appreciated. Thanks!

**Comment by ardraeiss** [comment]
Currently the addon removal in Windows OS should be done in two steps:
1) Disable addon in Preferences. Save settings. Close Blender application.
2) Open Blender again, remove the disabled addon from Preferences.
That should help you with the second issue.

**Comment by mburger89** [comment]
Thanks that didn't work as the plugin was never able to be active. I ended up just removing it from blender via powershell.

**Comment by ardraeiss** [comment]
@mburger89 what addon version are you using?

For removal: the step 1 could be skipped if addon is not active. Unless you've tried to activate it in the same Blender instance, in that case the Windows locks library files causing this error.

**Comment by mburger89** [comment]
@ardraeiss  The version is 3.0.8 

Tried installing again and still seeming the same errors. To remove the plugin I have found that navigating via powershell to the folder where addons are stored and running remove-item seems to be the only way I can remove it currently.

**Comment by mburger89** [comment]
Thanks @bnagirniak I got a fresh install from blender.org and now everything appears to be working!
