### ISSUE TITLE
Problem with tiled rendering

### ISSUE THREAD

**Issue by homeworker** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#228]
Those are 2 previews of the rendering with and without tiled rendering. I also tried with one GPU (the integrated Intel and the nvidia).
I'm using blender 2.92 on windows 10 and the latest beta RPR 3.0.31.

![non-tiled](https://user-images.githubusercontent.com/4161571/111613270-9fe4e600-87de-11eb-9060-b349f3ee6aa2.jpg)
![with-tiled](https://user-images.githubusercontent.com/4161571/111613276-a07d7c80-87de-11eb-9c9e-9453bee98143.jpg)

**Comment by bnagirniak** [comment]
This bug is fixed
