### ISSUE TITLE
3.08 and Materials Library 2.0 Crash my machine

### ISSUE THREAD

**Issue by fredfx1957** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#230]
Using with Blender 2.92

Yesterday I installed RPR 3.08 and the updated materials library 2.0 and it just brings my machine to its knees. 
It seems to work for a little while but the way it updates the screen when in Material Preview or Rendered doesn't look normal as it updates from the center of the viewport in a square wipe. Most of the time it locks up the machine and then brings me back to the login window. Sometimes it just hangs and the only way out is to power off the machine. 

I would happily post the crash logs if someone tells me how to find them. 
In the mean time, how do you roll back? I previously had RPR 2.x (don't know the exact one) and I'd love to roll back the version of RPR and the materials library. Can someone point me to it?

My machine configuration is below.

Help! 

best,

Fred

macOS 10.15.7 (19H524)
Model Name:	Mac Pro
Model Identifier:	MacPro7,1
Processor Name:	16-Core Intel Xeon W
Processor Speed:	3.2 GHz
Number of Processors:	1
Total Number of Cores:	16
Memory:	96 GB
Chipset Model:	AMD Radeon Pro Vega II
Type:	GPU
VRAM (Total):	32 GB

**Comment by bsavery** [comment]
Hi @fredfx1957 Can you try the latest release here:  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.1.0

**Comment by fredfx1957** [comment]
> Hi @fredfx1957 Can you try the latest release here: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.1.0


Using with Blender Version 2.92.0 (2.92.0 2021-02-25)
I installed 3.10 and I'm having the same kinds of problems. It just completely locks up my machine Same conditions as the previous issue. 

I would happily post the crash logs if someone tells me how to find them.


My machine configuration is below.

Help!

best,

Fred

macOS 10.15.7 (19H524)
Model Name: Mac Pro
Model Identifier: MacPro7,1
Processor Name: 16-Core Intel Xeon W
Processor Speed: 3.2 GHz
Number of Processors: 1
Total Number of Cores: 16
Memory: 96 GB
Chipset Model: AMD Radeon Pro Vega II
Type: GPU
VRAM (Total): 32 GB
