### ISSUE TITLE
RPR 3.0.33 Principled Hair Node Not Working?

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#231]
Hello!

I was informed via social media that the Principled Hair shader was supported in the new 3.0.33 weekly build however it appears not to be selectable as a node in the shader editor and when "forcing" the node, it appears to not be working. Any insight?

See image below:
![image](https://user-images.githubusercontent.com/65964807/112070598-3c82ed00-8b2b-11eb-81bd-3f053154d523.png)

Link to example file:
https://drive.google.com/file/d/1EsOa5ANerzGOVmAMsud4goACC-4BftDL/view?usp=sharing

System:
Windows 10
Blender: 2.92.0
64GB RAM
CPU: AMD 3960x
GPU: RTX 3090

**Comment by ardraeiss** [comment]
Hello.
The support for this node was added in the addon version 3.0.35.
The weekly build was done using 3.0.33 version so it missed that feature. It will be released soon. Here is what your scene looks like on the 5500 XT
![image](https://user-images.githubusercontent.com/2946319/112190132-c5765300-8c15-11eb-87e4-7322ac9b4577.png)

**Comment by djtutorials** [comment]
Thank you so much for clarifying! I'm looking forward to this update- thanks so much.

-DJ

**Comment by bsavery** [comment]
Sorry that was me leading you on, I thought the Friday auto builds already had this change.
