### ISSUE TITLE
OSError: [WinError 127] The specified procedure could not be found

### ISSUE THREAD

**Issue by marc-hopkins** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#235]
Traceback (most recent call last):
  File ..\Blender\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File ..\Blender\rprblender\__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File ..\Blender\rprblender\engine\__init__.py", line 139, in <module>
    import rprblender.utils.helper_lib
  File ..\Blender\rprblender\utils\helper_lib.py", line 174, in <module>
    init()
  File ..\Blender\rprblender\utils\helper_lib.py", line 63, in init
    lib = ctypes.cdll.LoadLibrary(str(lib_path))
  File ..\Blender\2.92\python\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File ..\Blender\2.92\python\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found

**Comment by bsavery** [comment]
Please add OS and Blender version details.  Which Plugin version are you using?  Also note the other issues about builds from the windows store or steam.

**Comment by marc-hopkins** [comment]
Sorry forgot to add the other information.
I'm on Windows 10 Pro using Blender 2.92 and even updated to the new RPR 3.1.0 and it is still giving an identical error dump. I uninstalled, reinstalled , closed blender ... reopened and tried to enable it.

**Comment by bsavery** [comment]
Where are you getting blender from?  Steam or downloading directly from blender.org?

Also can you check if you possibly have a 32 bit builds of blender or windows?

**Comment by bsavery** [comment]
Same issue as #111

**Comment by marc-hopkins** [comment]
I was able to resolve the issue by uninstalling and re-installing a fresh copy of blender. Seems I had a bad install of the blender 2.92.  But just wanted to follow up and let you know because I down load directly from Blender.org. It works now with the re-install. 👍 

> Same issue as #111
