### ISSUE TITLE
RPR 3.1.0 vs Cycles Principled Hair Color Rendering Discrepancies

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#238]
Hi All!

Very excited to see the principled hair shader in the newest build! I have noticed that the shader isn't quite a 1:1 match to Cycles in how it is calculating hair coloring, more specifically using the Melanin Concentration setting. It is definitely a huge improvement to the older method of hair coloring in this engine but I am wondering if there will be or is expected to be a 1:1 match to Cycles?

Cycles
![image](https://user-images.githubusercontent.com/65964807/112536601-ee5c2c80-8d6a-11eb-83c1-46b6f7aafe56.png)

RPR 3.1
![image](https://user-images.githubusercontent.com/65964807/112536761-18adea00-8d6b-11eb-8a63-cf67f8f14343.png)

You should be able to use the project file here for testing:
https://drive.google.com/file/d/1EsOa5ANerzGOVmAMsud4goACC-4BftDL/view?usp=sharing

System:
Windows 10
Blender 2.92
AMD 3960x Threadripper
Nvidia RTX 3090
64GB RAM
GEN4 1TB NVME M.2 SSD

**Comment by bsavery** [comment]
Not sure about the look if it's what you're going for but am I wrong that I like the RPR one more? ;)

**Comment by bsavery** [comment]
We'll take a look though!

**Comment by djtutorials** [comment]
@bsavery it definitely looks neat! :) I am just having trouble getting a regular realistic brown hair color with the melanin concentration settings. Some of the other settings like coat, random color and tint seem to not quite be working as well. Not sure if you guys will be able to look into that but thanks for checking!

**Comment by bsavery** [comment]
@VascoPi

**Comment by bsavery** [comment]
@djtutorials please try latest builds
