### ISSUE TITLE
SSS radius ignored in both Uber shader and principled BSDF

### ISSUE THREAD

**Issue by strangerman8791** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#239]
Hello!
I was testing the new RPR blender addon 3.1.0 and the viewport feels buttery smooth, and the principled hair shader looks awesome saving the color mismatching with cycles, nice improvement!

I realized that SSS radius is consistently ignored in both RPR Uber shader and Principled shader:
![imagen](https://user-images.githubusercontent.com/67149207/112669314-dc0fea80-8e5f-11eb-877b-0181acd7f003.png)
![imagen](https://user-images.githubusercontent.com/67149207/112669475-0cf01f80-8e60-11eb-8b05-2b706785f592.png)
![imagen](https://user-images.githubusercontent.com/67149207/112669977-a0c1eb80-8e60-11eb-938f-ecc81f75c20b.png)

I haven't made principledBSDF screencaps but it's the same, looks like SSS radius is not working, I could say neither is subsurface direction. Something happened there.
I'm using Blender version 2.92 stable for testing.

This is the sample file:
[chimpo_RPR.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6213415/chimpo_RPR.zip)
Steps:
Try to change the radius values, nothing will change. Same for the principledBSDF.
Please let me know if you need more info. I've tested this feature in previous versions and it always behaved this way, but judging by the documentation pictures it should introduce some visible changes.

Thanks!

**Comment by bsavery** [comment]
We should have an update coming in early may which will address this!

**Comment by iaian7** [comment]
Sorry, didn't see this post when I made my report! https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/307

Of note in my documentation: radius worked in dev build 3.1.16 but the direction setting was broken. In dev build 3.1.25, neither setting is operational.
