### ISSUE TITLE
ProRender 3.1.0 crashes in Blender 2.92.0 due to viewport denoising

### ISSUE THREAD

**Issue by DaveWoodCom** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#241]
Just installed ProRender 3.1.0 in Blender 2.92.0, on macOS Big Sur 11.2.3.

Setting the ViewPort render engine to ProRender initiates a render of the image where you can see it doing it's 128 iterations, then it says 'Denoising', then it crashes with the following error:

```
ERROR | RIF call ContextExecuteCommandQueue(<pyrprimagefilters.Context object at 0x13c978a10>, <pyrprimagefilters.CommandQueue object at 0x13c8d2150>, <cdata 'void *' NULL>, <cdata 'void *' NULL>,  <cdata 'void *' NULL>) returned error code <-21> with error message: ''. Please see logs for more details.
```

Changing the Noise Threshold from the default 0.05 to either 0, or 1, causes Blender itself to crash.

This is a Mac Pro with an AMD Radeon Pro W5700X 16 GB GPU.

Blender crash log and Blender system info attached.

<img width="776" alt="ProRenderErrorMessage" src="https://user-images.githubusercontent.com/1012467/113095465-786c2100-91c1-11eb-96d9-4fdc8c8fa12b.png" />

[system-info.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6233995/system-info.txt)
[BlenderProRendererCrashLog.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6233996/BlenderProRendererCrashLog.txt)

**Comment by bsavery** [comment]
Please disable in the viewport settings "Viewport denoising and upscaling" for now.
