### ISSUE TITLE
Prorender 3.0.1 crashes in Blender when attempting to setup textures

### ISSUE THREAD

**Issue by Jeducious** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#242]
## To reproduce
Simply add a texture with a texture input node, and mapping node. The texture I use is a checker texture. I connect the texture to a vector displacement node, then the displacement node to the material displacement output socket.

Upon attempting to change the scale of the checker texture, Blender crashes. It doesn't crash straight away though. It takes a few changes or slides of the scale input to the checker texture node to provoke the crash.

I have also witnessed a crash when changing the scale input of the vector displacement node. It seems it doesn't like scales. 

One last observation, it seems that this is pointing towards displacement not working. I have managed to get a couple of examples to work and show displacement, but the mesh is not displaced, it appears to be bump mapped only, looking at a silhouette, I can see that the displacements are not actual mesh tesselation. The docs suggest that ProRender supports subdivision similar to cycles? [The docs I refer to are here.](https://radeon-pro.github.io/RadeonProRenderDocs/en/plugins/blender/subdivision.html)
If this is the case, then I would bet there is something screwy going on with displacement as the crash only seems to happen when there is a displacement node hooked up to the material output displacement socket. 

## Output in powershell where blender started
```
PS C:\Program Files\Blender Foundation\Blender 2.92> ./blender.exe
Read prefs: C:\Users\CrowdRender\AppData\Roaming\Blender Foundation\Blender\2.92\config\userpref.blend
2021-04-01 21:49:30,207 INFO rpr.engine.init [5572]:  RPR Core version: 2.1.7 build 0x1e13f70e
2021-04-01 21:49:30,216 INFO rpr.engine.init [5572]:  Image Filters version 1.6.1 build 0xe4886697
2021-04-01 21:49:30,218 INFO rpr.default [5572]:  rprsdk_bin_path: C:\Users\CrowdRender\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\rprblender
2021-04-01 21:49:38,362 INFO rpr.utils.user_settings [5572]:  Automatic save user preferences...
Writing userprefs: 'C:\Users\CrowdRender\AppData\Roaming\Blender Foundation\Blender\2.92\config\userpref.blend' ok
2021-04-01 21:49:38,371 INFO rpr.utils.user_settings [5572]:  Automatic save user preferences...
Writing userprefs: 'C:\Users\CrowdRender\AppData\Roaming\Blender Foundation\Blender\2.92\config\userpref.blend' ok
2021-04-01 21:49:38,379 INFO rpr.utils.user_settings [5572]:  Automatic save user preferences...
Writing userprefs: 'C:\Users\CrowdRender\AppData\Roaming\Blender Foundation\Blender\2.92\config\userpref.blend' ok
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x000002B034330FC2
Module  :
Thread  : 00000b64
Writing: C:\Users\CROWDR~1\AppData\Local\Temp\blender.crash.txt
PS C:\Program Files\Blender Foundation\Blender 2.92>
```

## Bender crash file
[blender.crash.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6243091/blender.crash.txt)

## sysinfo file
[system-info.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6243094/system-info.txt)

**Comment by bsavery** [comment]
Hey @Jeducious Are you on 3.0.1 or the just released 3.1.0?  Can you check with that too?

**Comment by Jeducious** [comment]
Yo, I am on 3.0.1, I downloaded it a few days ago from the main site for ProRender... I think? 

Can you confirm the URL for the current most up to date release? I'll test that for sure :)

**Comment by Jeducious** [comment]
Hi, never mind found it. Downloaded it from [here](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.1.0).

Yes it still crashes, also still has the issue of displacement not actually producing a deformed mesh. You can see this in this short video I made which shows the crash, and another interesting issue where the rendered viewport suddenly goes black which I did not notice in 3.0.1.
Blender's overlay is still there, but the rendered view is gone, replaced with black. Also intermittent, as you'll see in the video.

[link to download mov file  of crash](https://www.dropbox.com/s/9ysat7gi3xj21vs/Screen%20Recording%202021-04-03%20crash%20in%20RPR.mov?dl=1)

**Comment by ardraeiss** [comment]
@Jeducious to see the displacement instead of Bump you have to change settings in Material tab. Material -> Displacement -> Displacement method, from the default "Bump only" value to "Displacement only".

Is the Object tab -> Subdivision enabled?

Also, could you please try to disable the Render tab -> Sampling -> Viewport & Preview Sampling -> Viewport Denoising and Upscaling and try to reproduce this crash again?

**Comment by Jeducious** [comment]
Ok, displacement, sort of works, yes, I was missing the setting, so silly of me, sorry. I did notice that the textures coordinates don't all work though. I guess that is a separate ticket? If not, I'll make one!

**Comment by Jeducious** [comment]
OK, in 3.1.0, the crash doesn't seem to be happening anymore, so closing this ticket now.
