### ISSUE TITLE
RPR Blender 3.1.0 Ubuntu 20 - not able to install 

### ISSUE THREAD

**Issue by meetdilip** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#243]
I downloaded the following plugin for Blender to use in **Ubuntu 20.04.** But I am unable to install in both `2.83` and `2.91` in Ubuntu 20.04

**RadeonProRenderForBlender_3.1.0_Ubuntu20.Release_March_2021.zip**

It gives this error while trying to enable using Preferences > Install

![Screenshot from 2021-04-02 19-25-12](https://user-images.githubusercontent.com/6965443/113422480-6f11cd00-93ea-11eb-9ee9-186512d485d0.png)

But I am able to install it in both Blender `2.83` and `2.91`. It would be nice if someone can help me with this. 

My PC specifications are

> OS: Ubuntu 20.04.2 LTS x86_64 
> Kernel: 5.8.0-48-generic 
> Packages: 2243 (dpkg), 16 (snap) 
> Shell: bash 5.0.17 
> Resolution: 1366x768 
> DE: GNOME 
> WM: Mutter 
> Terminal: gnome-terminal 
> CPU: AMD A6-6400K APU (2) @ 3.900GHz 
> GPU: AMD ATI Radeon HD 8470D 
> Memory: 2645MiB / 7148MiB

**Comment by bsavery** [comment]
See the libGL issue in #203
