### ISSUE TITLE
This blend file with RPR Blender addon 3.1.0 - possible mem leak leading to eventual system hang

### ISSUE THREAD

**Issue by Jeducious** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#245]
Ok, so, after testing 3.1.0 noticed that if the Adapt Viewport Resolution and Viewport Denoising and Upscaling options are set, then the RAM consumed by the parent blender process begins to increase as the viewport is updated and re-rendered, eventually leading to a complete system hang. 

Turning off these options the RAM usage is stable. 

I started Blender a second time and this time turned off the two options mentioned above, then changed my view to the material preview. 

All was fine, then I turned on just the Viewport Denoising and Upscaling option. I got an immediate RAM spike which I had not had using the system without this option in the rendered viewport, with no RAM increases so far, and plenty of rendering in the viewport done. 
<img width="1440" alt="RAM usgae increase when using Viewport Denoising and Upscaling" src="https://user-images.githubusercontent.com/34228929/113459537-92c42a00-9461-11eb-9feb-70624789e83d.png">

[sierpinski Tetrahedra_3.blend.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6251471/sierpinski.Tetrahedra_3.blend.zip)

**Comment by Jeducious** [comment]
Update, switched from material preview to rendered view, pretty much an immediate system hang. 

System works fine so long as I don't enable the Viewport Denoising and Upscaling option

**Comment by bnagirniak** [comment]
Should be fixed with #280
