### ISSUE TITLE
Never been able to get ProRender and Blender working on a Mac Pro

### ISSUE THREAD

**Issue by ethank** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#247]
Has anyone had any luck getting ProRender working on a Mac Pro without crashing? 

With just a cube it'll start and viewport render, but after that more often than not I get either a hall of windows or the WindowServer / GPU crashes. 

Attached is the WindowServer crash and System Report 

Mac Pro
macOS Big Sur 11.3
AMD Radeon Pro Vega II
192 GB RAM

[WindowServer_2021-04-02-160108_Ethans-Mac-Pro.crash.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6251545/WindowServer_2021-04-02-160108_Ethans-Mac-Pro.crash.zip)

**Comment by Jeducious** [comment]
Yes, but not on Big Sur, and not on a Mac Pro, using catalina on a macbook pro late 2015 model, intel CPU, eGPU RX5700XT, works really well with the eGPU.

**Comment by bsavery** [comment]
See #241 disable the viewport denoising option in viewport settings.  There's an issue with the upscaler on macOS.

**Comment by bsavery** [comment]
(closing as duplicate of #241 unless that doesn't work reopen)
