### ISSUE TITLE
RPR 3.1.0 Windows 10 Crash if texture in "Environment light" is 4k or higher

### ISSUE THREAD

**Issue by Masterblop** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#250]
How to reproduce:
-Open blender;
-In render engine set to RadeonProRender;
-In render quality set to Low (or medium or high);
-In world properties, under Environment light insert a environment texture 4k or higher;
-Press render button.
It start rendering but crash blender and video driver

Software:
Windows 10 Pro
Blender 2.92.0 (installed in Steam)
RadeonProRender 3.1.0

Hardware:
AMD Ryzen 7 1700
AMD Radeon Pro WX 5100
32 GB of Ram

**Comment by bsavery** [comment]
Hmm, so I don't see this (on my Rx 6900 XT).  You might want to try enabling the "Use low memory" option

**Comment by Masterblop** [comment]
> 
> 
> Hmm, so I don't see this (on my Rx 6900 XT). You might want to try enabling the "Use low memory" option
Hi bsavery,
I tried it and I got the same result, even with the portable version of Blender

**Comment by Jeducious** [comment]
could not reproduce, for system info, see [system-info.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6432329/system-info.txt)

I also have a win 10 system, Blender 2.92, RPR 3.1.0

@Masterblop any chance you could upload the blend file that is doing this? That way it could be checked if its your system or the blend file?

**Comment by Masterblop** [comment]
The blend file is the common "new file" or the file you find when blender starts.

I am attaching the "system info" file: 
[system-info.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6432923/system-info.txt)

**Comment by janvollgod** [comment]
can confirm, there is something wrong with image based lightning. 

Tested on both of my Workstations 

Blender 2.92
System: Win 10 
CPU :  Ryzen 5900 / 5950 
GPU : RTX 3070 / 3090 
RAM:  64 GB / 64 GB 
RPR 3.1.0 - set to GPU Rendering, no denoise, High

Get default cube. Apply some random RPR Material. Add a Cam, World Setting IBL pick some nice 4k HDRI from HH, switch in viewport from preview to Raytracing ---> Result crash to desktop
Same as above, World Settings use Skylight, set Texture Quality to high, switch in Viewport to raytrace --> result crash

With Renderdevice set to CPU, the results are the same. It has to do with the HDRI size. If i choose "low" in the World setting with Skylight, i can render in Viewport without crash. "high" instantly crashes to desktop.

**Comment by Jeducious** [comment]
@Masterblop hmmmm, ok, well, have you modified your default/startup scene at all?
