### ISSUE TITLE
Crash on enabled Viewport denoising in Blender 2.92

### ISSUE THREAD

**Issue by odil24** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#251]
I tried to enable then to go Viewport rendering after max samples stoping render goes Denoisng but with this error:
http://postimg.cc/kRmP4fqS

**Comment by seanr** [comment]
In my case, it actually crashed Blender entirely; the only crash output I could locate is attached - I hope it tells others more than it tells me. 🤣 

[Stage 9 - TLE Engineering - ProRender.crash.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6267901/Stage.9.-.TLE.Engineering.-.ProRender.crash.txt)

**Comment by bsavery** [comment]
(note the fix in #254 Is not MacOS only.

**Comment by odil24** [comment]
> 
> 
> (note the fix in #254 Is not MacOS only.

Hi. I edited myself this line and all are works fine now! :)
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/pull/254/commits/e835849320367a49614a1809d6f56dde0958449c
