### ISSUE TITLE
adaptative sampling with CPU+GPU causing noise discrepancy

### ISSUE THREAD

**Issue by GabrielG0** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#252]
First of all, I have to say, Pro Render is awesone.
It makes good results, is fast and the denoise and upscale are very plausible.
 But this channel is for issues, so, let's begin.

 Since when adaptative sampling was enabled is RPR2 i've been experiencing a ciscrepancy between CPU and GPU when both where enable, setting noise threshold to 0 fix it.

and the images

on (with threshold 0,03)
![on](https://user-images.githubusercontent.com/69019054/113759888-fc576900-96eb-11eb-8dd0-2d358c9e443b.png)

off (with threshold 0,00)
![off](https://user-images.githubusercontent.com/69019054/113760304-71c33980-96ec-11eb-851b-c231956c7e1a.jpg)

and with diferents exposures to make it easier to see

on
![on+exposure1](https://user-images.githubusercontent.com/69019054/113760457-a33c0500-96ec-11eb-9723-b6113d5b73e1.jpg)
![on+exposure2](https://user-images.githubusercontent.com/69019054/113760472-a931e600-96ec-11eb-92ce-41976c563f87.jpg)

off
![off+exposure1](https://user-images.githubusercontent.com/69019054/113760507-b058f400-96ec-11eb-81e5-b519ab1617ff.jpg)
![off+exposure2](https://user-images.githubusercontent.com/69019054/113760527-b51da800-96ec-11eb-86f9-23f8e6b1e434.jpg)

and the scene

[adaptative test.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6266827/adaptative.test.zip)

OS: Windows 10 20H2
Blender Version: 2.92
RPR Plugin Version: 3,1,0
CPU: Ryzen 5 1600
Ram: 16 Gb
GPU: Rx 550 4gb
GPU Driver Version: 21,2,3 (newer has a bug, already reported)

**Comment by djtutorials** [comment]
I have also noticed this issue.

**Comment by bsavery** [comment]
Thanks!  Yes we are working on this on the CPU side.

**Comment by GabrielG0** [comment]
3.1.10 have rpr sdk 2.2.2 (this version have a fix)
thank you for everyone!!!
