### ISSUE TITLE
Are Nodes used for Machine Learning denoiser in Compositing editor?

### ISSUE THREAD

**Issue by odil24** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#257]
Is RPR using node for denoising or self-based not-visible option for denosing? The reason for asking is when I goto Compositing node there is LightGroup node and when I delete and just add Render layers connect with Output image it doesnt denoise.

**Comment by bsavery** [comment]
No we do not use the compositing nodes for denoising.
