### ISSUE TITLE
RPR 3.1.0 blender crash on Viewport Shading mode

### ISSUE THREAD

**Issue by rmybld** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#258]
Hi  
I had a problem with Viewport Shading materials and rendered mode, they crashed my blender. I decide to upgrade all versions of my configuration now I use Blender 2.92 and RPR 3.0.1 But I have the same problem with last versions.

My setup Macbook Pro 2,6 GHz Intel Core i7 16 Go DDR4 with a AMD Radeon Pro 5300M 4 Go.

On render properties : 
- RPR : activate 
- CPU : disable 
- AMD Radeon Pro 5300M : activate 
- Separate viewport and preview… : disable

On View layers properties 
- RPR Denoiser : disable 

Tested with render engine Cycles and I have no problem but my CPU don't like it !  

<img width="1598" alt="Capture d’écran 2021-04-10 à 18 43 35" src="https://user-images.githubusercontent.com/2410380/114277712-aad11600-9a2c-11eb-8f5d-7bb24ab477e7.png">

More logs 

```
I0410 18:32:22.095481 532901376 blender_python.cpp:194] Debug flags initialized to:
CPU flags:
  AVX2       : True
  AVX        : True
  SSE4.1     : True
  SSE3       : True
  SSE2       : True
  BVH layout : EMBREE
  Split      : False
CUDA flags:
  Adaptive Compile : False
OptiX flags:
  CUDA streams : 1
OpenCL flags:
  Device type    : ALL
  Debug          : False
  Memory limit   : 0
2021-04-10 18:32:22,325 INFO rpr.engine.init [4827868672]:  RPR Core version: 2.2.1 build 0x924e5459
2021-04-10 18:32:22,340 INFO rpr.engine.init [4827868672]:  Image Filters version 1.6.1 build 0xe4886697
2021-04-10 18:32:22,342 INFO rpr.default [4827868672]:  rprsdk_bin_path: /Users/rmybld/Library/Application Support/Blender/2.92/scripts/addons/rprblender
2021-04-10 18:32:22,608 INFO rpr.material_library [4827868672]:  Material library located at /Users/Shared/RadeonProRender/MaterialLibrary/2.0.0/Xml
Switching to fully guarded memory allocator.
Blender 2.92.0
Build: 2021-02-25 09:27:51 Darwin Release
argv[0] = /Applications/Blender.app/Contents/MacOS/Blender
argv[1] = --debug
argv[2] = --debug-cycles
Read prefs: /Users/rmybld/Library/Application Support/Blender/2.92/config/userpref.blend
read file 
  Version 280 sub 39 date unknown hash unknown
Read blend: /Users/rmybld/Desktop/Blender/update tests/untitled.blend
read file /Users/rmybld/Desktop/Blender/update tests/untitled.blend
  Version 292 sub 15 date 2021-02-24 16:25 hash 02948a2cab44
[MSG  @RIF]: Loaded RIF API version: 1.6.1.0xe4886697
INFO: Using Metal device: AMD Radeon Pro 5300M
[MSG  @RIF]: Loaded RIF API version: 1.6.1.0xe4886697
INFO: Using Metal device: AMD Radeon Pro 5300M
[MSG  @RIF]: Loaded RIF API version: 1.6.1.0xe4886697
INFO: Using Metal device: AMD Radeon Pro 5300M
[MSG  @RIF]: Loaded RIF API version: 1.6.1.0xe4886697
INFO: Using Metal device: AMD Radeon Pro 5300M
[MSG  @RIF]: Loading model: /Users/rmybld/Library/Application Support/Blender/2.92/scripts/addons/rprblender/data/models/denoise_c9_hdr_gamma_2.5_f16.onnx
INFO: Model info: 
 domain: 
 ir_version: 6
 producer_name: AMD
 producer_version: 
 version: 0
 opset domain: opset version11

[MSG  @RIF]: Loading model: /Users/rmybld/Library/Application Support/Blender/2.92/scripts/addons/rprblender/data/models/esrgan-05x3x32-278391.pb
[ERROR@RIF]: RIF_ERROR_OUT_OF_VIDEO_MEMORY at file /Users/admin/JN/WS/RadeonProImageProcessor_Build/src/AIFilters.cpp line 620
2021-04-10 18:32:52,248 ERROR rpr.viewport_engine [123145517936640]:  RIF call ContextExecuteCommandQueue(<pyrprimagefilters.Context object at 0x13b91f890>, <pyrprimagefilters.CommandQueue object at 0x13b91f6d0>, <cdata 'void *' NULL>, <cdata 'void *' NULL>, <cdata 'void *' NULL>) returned error code <-3> with error message: '' EXCEPTION: Traceback (most recent call last):
  File "/Users/rmybld/Library/Application Support/Blender/2.92/scripts/addons/rprblender/engine/viewport_engine.py", line 449, in _do_sync_render
    self._do_render()
  File "/Users/rmybld/Library/Application Support/Blender/2.92/scripts/addons/rprblender/engine/viewport_engine_2.py", line 242, in _do_render
    self.upscale_filter.run()
  File "/Users/rmybld/Library/Application Support/Blender/2.92/scripts/addons/rprblender/engine/image_filter.py", line 109, in run
    self.command_queue.execute()
  File "/Users/rmybld/Library/Application Support/Blender/2.92/scripts/addons/rprblender/pyrprimagefilters.py", line 366, in execute
    ContextExecuteCommandQueue(self.context, self, ffi.NULL, ffi.NULL, ffi.NULL)
  File "/Users/rmybld/Library/Application Support/Blender/2.92/scripts/addons/rprblender/pyrpr.py", line 78, in wrapped
    raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RIF call ContextExecuteCommandQueue(<pyrprimagefilters.Context object at 0x13b91f890>, <pyrprimagefilters.CommandQueue object at 0x13b91f6d0>, <cdata 'void *' NULL>, <cdata 'void *' NULL>, <cdata 'void *' NULL>) returned error code <-3> with error message: ''
```

I wonder if this is not a problem in my RPR configuration.

**Comment by jakubspitzer** [comment]
Hello, I have the same problem. I am new to blender so maybe have wrong settings. Any advices are welcome. I have MB Pro 2016 2,7Ghz i7, 16Gb ram, Radeon Pro 455 + eGPU Blackmagic Radeon Pro 580. I use RPR because cycles does not support my eGPU. Any advice to use another render engine that support eGPU from Blackmagic ? 

When I render just simple general cube when you open blender render is okay, but it crashes when denoising. If I turn off denoising and upscaling at Viewport & Preview Sampling there is no error. So it must be something with denosing or/and upscaling.

<img width="770" alt="Snímek obrazovky 2021-04-13 v 22 17 04" src="https://user-images.githubusercontent.com/77176707/114734802-d7df3a80-9d44-11eb-93dc-70e9b8495820.png">
<img width="482" alt="Snímek obrazovky 2021-04-14 v 17 14 54" src="https://user-images.githubusercontent.com/77176707/114734892-f34a4580-9d44-11eb-80c7-980eb1ddaf2d.png">
<img width="485" alt="Snímek obrazovky 2021-04-14 v 17 14 25" src="https://user-images.githubusercontent.com/77176707/114734897-f47b7280-9d44-11eb-9afd-ffadb92f9364.png">
<img width="770" alt="Snímek obrazovky 2021-04-13 v 22 17 04" src="https://user-images.githubusercontent.com/77176707/114734898-f47b7280-9d44-11eb-9159-8eb48fd6f862.png">

Would be happy to have solution for it :)

**Comment by bsavery** [comment]
Hi guys.  You listed your version you're using as 3.0.1.  Please upgrade to https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.1.0

**Comment by rmybld** [comment]
Hi @bsavery It was a mistake, I use the latest version of RPR 3.1.0

I followed @jakubspitzer suggestion and disabled `Viewport Denoising and upscaling` It works better and I have no errors but the rendering is much slower. 

<img width="1687" alt="Capture d’écran 2021-04-15 à 13 30 30" src="https://user-images.githubusercontent.com/2410380/114862539-f1d55780-9dee-11eb-8ac3-197c09ea0781.png">

When the `Viewport Denoising and upscaling` is activate, at the end of the iteration I have the error 

<img width="1687" alt="Capture d’écran 2021-04-15 à 13 29 37" src="https://user-images.githubusercontent.com/2410380/114862576-fc8fec80-9dee-11eb-967e-66f473e95cbb.png">

**Comment by rmybld** [comment]
Hey @bsavery I would like to know if you have found a solution to solve this problem?

**Comment by jakubspitzer** [comment]
Hey @rmybld, just to let you know I did not find any solution. I just bought mac mini with M1 silicon chip. Works great with both CPU or GPU cycles rendering. Did not test which is faster tho. Hope you will find solution for this issue. Heads up ;)

**Comment by bsavery** [comment]
Hey @rmybld we do have a solution we're working on to enable the upscaling on Mac #260 

@jakubspitzer cycles GPU rendering on mac's is disabled currently, M1 chip or non

**Comment by rmybld** [comment]
Hello 
Thanks for your feedback @bsavery 👍
I see that the modifications have been merged in dev, do you know when is scheduled the next production delivery with this modifications ?

**Comment by bsavery** [comment]
End of may.  You can download a trial build in "releases"
