### ISSUE TITLE
Doesn't Work on R9 M370

### ISSUE THREAD

**Issue by BlackCharon142** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#267]
My laptop is Lenovo Z51-70 and has a Radeon R9 M370
When I go into rendered view and material preview it crashes
these happen when I use the graphic card but it's different for the CPU
CPU crashes in the rendered and material preview and sometimes handles rendering the final image, other times it just gives up halfway and only renders parts of it
![CPU(Default Settings)](https://user-images.githubusercontent.com/59452141/117537690-e8b75f00-b017-11eb-940a-c03c1f33be25.png)
 CPU Rendered Image took 10 min with Default Settings

I really thought this engine is gonna use my GPU since Cycles can't even show it in the System settings but it seems like my GPU doesn't like Rendering at all, tho it has 4G of dedicated memory
I never found any game or engine that could use it

**Comment by bsavery** [comment]
Hi we don't support r9 cards anymore due to OpenCL limitations.  It may work in "legacy" mode.
