### ISSUE TITLE
builds v3.1.6 doesn't work with Blender 2.93b on Mac OS

### ISSUE THREAD

**Issue by Aliprandini** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#270]
Blender 2.93 beta, Mac OS 11.3.1, RPR 3.1.6, RX 5700XT

Couldn't activate RPR in Blender. A lot of errors show up. Smth should be wrong with this build for Blender Mac version. Please, re-check this.

**Comment by bsavery** [comment]
actually @ARozghon.... only on linux does it use system python I think?

**Comment by bsavery** [comment]
Meaning they don't need to update the python unless they are building themselves

**Comment by ARozghon** [comment]
yes, that's true, need to update Python to 3.9 on Linux. and that's good if it not need to do on macOS and Windows

**Comment by Aliprandini** [comment]
3.1.10 DOESN'T WORK again

**Comment by bnagirniak** [comment]
@Aliprandini please provide plugin log.

**Comment by Aliprandini** [comment]
Sorry, the RPR could be activated, but before this everybody should delete "module" folder at ~i/Library/Application Support/Blender/2.93/scripts fore Numpy rebuild. 

But I found another problem. Botocore library is downloading every time while Blender.app start while RPR is activated. 

![123](https://user-images.githubusercontent.com/73755453/119254679-b8032800-bbc8-11eb-88ad-d2fe8a222c49.png)

**Comment by bnagirniak** [comment]
Thank you for log and issue with boto library installation, we'll look it closely and we'll fix it.

**Comment by bnagirniak** [comment]
Should be fixed with #293
