### ISSUE TITLE
Bake all Unsupported Nodes Error / Iteration over deleted objects

### ISSUE THREAD

**Issue by fuzzifikation** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#274]
Baking all unsupported nodes fails on standard .blend file.

1.  Versions:
Blender 2.92
RPR Version 3.1.6 (newest weekly build at time of writing)

2.   a .blend scene to reproduce this simply. 
the new Blender 2.92 .blend from here
https://cloud.blender.org/p/gallery/60337d495677e942564cce76

## Issue
and
## Steps to Reproduce
1. Download and open the blend file from above
2. In the Render Settings, in the Quality panel there is the Node Baking subsection. Here you will find the Bake All Unsupported Nodes button. Press it.
3.
--> Error Message:
Python: Traceback (most recent call last):
  File "C:\Users\diete\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\rprblender\operators\nodes.py", line 135, in execute
    obj.select_set(True)
RuntimeError: Error: Object 'Cube' can't be selected because it is not in View Layer 'View Layer'!

-- My thoughts:
The "Cube" had been deleted a long time ago. You guys are iterating not only over all active view objects but you are instead iterating over all ever existed objects. Then you want to do something to thoses deleted objects, which obviously must fail.
No good.

## System Setup (Environment)

Win 10

Nvidia 2070 super

2.92
RPR 3.1.6.

**Comment by fuzzifikation** [comment]
BTW: To further support my thoughts: Insert Cube Object (it will be labeled "Cube.004". Then rename this to "Cube"
You will then get a new error message, but that Cube.004 cannot be found.

Again.. no good. :-)

**Comment by bsavery** [comment]
Your assumption is correct.  So the question I'd have is do you think we should bake all objects from all layers in the scene or just the current layer?

**Comment by fuzzifikation** [comment]
My idea: Bake everything visible, that would have to be baked for when I press "render" to actually work.
Or you can use the check mark status of the eye icon in the view layer. This way you can give the user some control. So.. Bake all objects from all layers that have the eye icon checked. Maybe like that?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by bnagirniak** [comment]
Fixed in #288
