### ISSUE TITLE
RPR v3.1.2 doesnt works with Blender 2.93 official build

### ISSUE THREAD

**Issue by odil24** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#290]
## System Setup (Environment)
Windows 10, Blender 2.93 (official), MSI GTX 1060 6Gb 
Installed succesfully but just doesn't render any scenes.

**Comment by bsavery** [comment]
They do for us here.  What's the error you have?

**Comment by odil24** [comment]
Hehe...now it works fine ;)
