### ISSUE TITLE
Refraction Absorption Not Working (macOS Big Sur)

### ISSUE THREAD

**Issue by jay-b** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#296]
Creating a Refraction Absorption colour and Distance value doesn't seem to have any effect. 

- New Blend file
- Added a simple diamond object
- Added a 'Jewels Diamond' texture from the MLB.
- Set Refraction Absorption distance to 2.0
- Set Refraction Absorption colour to red

## System Setup (Environment)
macOS 11.4
6800XT
Blender 2.92
GPU Rendering
[RPR-diamond-absorption.blend.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6701638/RPR-diamond-absorption.blend.zip)

**Comment by bsavery** [comment]
Hi Jay-b

This is a known issue (noted in release notes)
"RPR 2.0 has some forthcoming features. If these are needed, please use the Legacy render mode:
Heterogenous volumes."

(absorption is done with a heterogenous volume shader)
