### ISSUE TITLE
HD7730, Not working, errors with compilation.

### ISSUE THREAD

**Issue by 3-1Plus** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#3]
Blender 2.82.7, Windows 10 x64
GPU: HD7730, latest AMD drivers.
CPU: Intel Xeon x3450
Rendering with CPU seems fine, but as long as I choose GPU, the viewport goes black, and the log is:

`Read prefs: C:\Users\irina\AppData\Roaming\Blender Foundation\Blender\2.82\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.82\2.82\python
BlendLuxCore 2.3 registered (with pyluxcore 2.3)
Loading MHX2 importer-runtime v 0.31
build loaded
MHX2 armature loaded
MHX2 successfully (re)loaded
Loading MH community plug-in v 0.6.3
Loading sync plug-in
sync plug-in loaded
Loading kinect Sensor plug-in
kinect Sensor plug-in loaded
MH community plug-in load complete
C:\Users\irina\AppData\Roaming\Blender Foundation\Blender\2.82\makehuman.default.settings.json
2020-05-13 11:28:55,628 INFO rpr.engine.init [80508]:  RPR Core version: 1.35.0 build 0x6a03c5b6
2020-05-13 11:28:55,651 INFO rpr.engine.init [80508]:  Image Filters version 1.5.1 build 0xefd92438
2020-05-13 11:28:55,655 INFO rpr.default [80508]:  rprsdk_bin_path: C:\Users\irina\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\rprblender
Updating OpenCL device list

16 errors detected in the compilation of "C:\Users\irina\AppData\Local\Temp\OCL7604T28.cl".
Frontend phase failed compilation.

"Scene.cl", line 593: error: expression must have pointer-to-struct-or-union
          type
        const float3 minP = make_float3( gMinP->x, gMinP->y, gMinP->z );
                                         ^

"Scene.cl", line 593: error: expression must have pointer-to-struct-or-union
          type
        const float3 minP = make_float3( gMinP->x, gMinP->y, gMinP->z );
                                                   ^

"Scene.cl", line 593: error: expression must have pointer-to-struct-or-union
          type
        const float3 minP = make_float3( gMinP->x, gMinP->y, gMinP->z );
                                                             ^

"Scene.cl", line 593: error: not enough initializer values
        const float3 minP = make_float3( gMinP->x, gMinP->y, gMinP->z );
                                                                      ^

"Scene.cl", line 594: error: expression must have pointer-to-struct-or-union
          type
        const float3 maxP = make_float3( gMaxP->x, gMaxP->y, gMaxP->z );
                                         ^

"Scene.cl", line 594: error: expression must have pointer-to-struct-or-union
          type
        const float3 maxP = make_float3( gMaxP->x, gMaxP->y, gMaxP->z );
                                                   ^

"Scene.cl", line 594: error: expression must have pointer-to-struct-or-union
          type
        const float3 maxP = make_float3( gMaxP->x, gMaxP->y, gMaxP->z );
                                                             ^

"Scene.cl", line 594: error: not enough initializer values
        const float3 maxP = make_float3( gMaxP->x, gMaxP->y, gMaxP->z );
                                                                      ^

"Scene.cl", line 622: error: expression must have pointer-to-struct-or-union
          type
        const float3 minP = make_float3( gMinP->x, gMinP->y, gMinP->z );
                                         ^

"Scene.cl", line 622: error: expression must have pointer-to-struct-or-union
          type
        const float3 minP = make_float3( gMinP->x, gMinP->y, gMinP->z );
                                                   ^

"Scene.cl", line 622: error: expression must have pointer-to-struct-or-union
          type
        const float3 minP = make_float3( gMinP->x, gMinP->y, gMinP->z );
                                                             ^

"Scene.cl", line 622: error: not enough initializer values
        const float3 minP = make_float3( gMinP->x, gMinP->y, gMinP->z );
                                                                      ^

"Scene.cl", line 623: error: expression must have pointer-to-struct-or-union
          type
        const float3 maxP = make_float3( gMaxP->x, gMaxP->y, gMaxP->z );
                                         ^

"Scene.cl", line 623: error: expression must have pointer-to-struct-or-union
          type
        const float3 maxP = make_float3( gMaxP->x, gMaxP->y, gMaxP->z );
                                                   ^

"Scene.cl", line 623: error: expression must have pointer-to-struct-or-union
          type
        const float3 maxP = make_float3( gMaxP->x, gMaxP->y, gMaxP->z );
                                                             ^

"Scene.cl", line 623: error: not enough initializer values
        const float3 maxP = make_float3( gMaxP->x, gMaxP->y, gMaxP->z );
                                                                      ^

16 errors detected in the compilation of "C:\Users\irina\AppData\Local\Temp\OCL7604T29.cl".
Frontend phase failed compilation.

`
Thanks.

**Comment by bsavery** [comment]
Hi there.  Unfortunately that card is not on the list of officially supported cards: https://www.amd.com/en/support/kb/release-notes/rn-prorender-blender-v2-4

Although it officially should support OpenCL 1.2, the older GCN 1 cards like this no longer work with RPR.  
Sorry :( I wish I had a better answer.  CPU rendering should still be supported there though.

**Comment by 3-1Plus** [comment]
Ah, sorry, i'm dumb and i didn't checked that, sorry for the useless issue too!.

**Comment by bsavery** [comment]
Well you get the "honor" of having the first issue ;)
