### ISSUE TITLE
Why so slow synchronizing RPR 3.1.21(5) for Blender 2.93 and 3.0 also too?

### ISSUE THREAD

**Issue by odil24** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#300]
- Blender 2.93 and 3.0;
- RPR 3.1.25 (using 3.1.21 but downloaded latest comitts .py files and replace them as 3.1.25);
- Win 10 x64;
- Msi Gtx 1060 6gb;
- Ram Ddr4 2666mhz 32gb.

Just rendering interior scene with not enough to 1 mln polygons. But when I goto viewport rendering it goes write Syncing... and I wait forever. 
P.s.: cant post blend scene cuz its commercial project.

**Comment by ARozghon** [comment]
hi, could you try to reproduce your issue with this project https://download.blender.org/demo/cycles/flat-archiviz.blend ? that's a free scene from Blender, and, please, collect info from log or System Console. Thank you

**Comment by odil24** [comment]
> 
> 
> hi, could you try to reproduce your issue with this project https://download.blender.org/demo/cycles/flat-archiviz.blend ? that's a free scene from Blender, and, please, collect info from log or System Console. Thank you

Solved! Thanks!
