### ISSUE TITLE
3.1.0 Blender addon is broken

### ISSUE THREAD

**Issue by iyadahmed** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#301]
Unable to install Blender addon

## Issue
cannot enable addon, the latest weekly works, but the one linked from official website doesn't work

## Steps to Reproduce
Download 3.1.0 RPR Blender Addon
Try to install the addon

## System Setup (Environment)
![image](https://user-images.githubusercontent.com/25552173/123447114-c8e4f600-d5d9-11eb-83e1-b0163cdc9a82.png)

## Detailed Description
The addon installation doesn't work

**Comment by bsavery** [comment]
Please include your blender version the 3.1.0 version doesn't work with blender 2.93 if that's what you have.

**Comment by iyadahmed** [comment]
Tested on both 
Blender 2.83.13 and 2.93

But it might be a python version issue, it says it cant find a dll
