### ISSUE TITLE
Node Wrangler 'Shader Viewer' causes crash when Subdivision is on (macOS Big Sur) 

### ISSUE THREAD

**Issue by jay-b** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#306]
When Subdivision is on (RPR Settings) and I use the hotkeys; [Cntl] [Shift] + [left click] on a texture node, Blender unexpectedly quits. Works as expected when Subdivision is off. 

Image texture nodes were connected to an Uber Shader. Displacement node used and connected to the Material Output.

**Steps to Reproduce**
- Ensure Node Wrangler is on
- Switch on Subdivision under RPR settings
- [Cntl] [Shift] + [left click] a texture node

https://docs.blender.org/manual/en/latest/addons/node/node_wrangler.html#shader-viewer

**System Setup** (Environment)
macOS 11.4
6800XT
Blender 2.92
GPU Rendering
RPR 3.1.0
[Abandoned.01.01.crash.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6744062/Abandoned.01.01.crash.txt)

**Comment by jay-b** [comment]
Sure. 

https://drive.google.com/file/d/1NHt4sKm7ChFBCLaUg8QrsOfuB9F5udus/view?usp=sharing

**Comment by wongdi** [comment]
I have had a similar issue, try to remove and install addon or off denoise.😊

**Comment by bsavery** [comment]
@VascoPi can you try the above scene and close if no longer valid?
