### ISSUE TITLE
UV Editing mode - iPR does not show the image texture on model in Edit Mode

### ISSUE THREAD

**Issue by aledbrown** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#31]
1. Open the sample file. Or setup a base colour image texture on a UV unwrapped cube.
2. Open up a UV editor next to a 3D view running RPR iPR. The image texture will be visible, although it might not be positioned as you might like so you need to edit the position via the UVs.
3. Tab into Edit mode so that you can move a UV island (face, etc) to better align the texture to the model - the image texture has now vanished from the iPR preview and you cannot see the texture to correctly align it... it's pure guesswork.

<img width="1792" alt="Screenshot 2020-06-11 at 08 48 40" src="https://user-images.githubusercontent.com/690500/85675631-cc3f5c00-b6bd-11ea-90b3-0a60169d2258.png">

[Basic UV Editing Preview - Broken.blend.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/4829692/Basic.UV.Editing.Preview.-.Broken.blend.zip)

**Comment by bsavery** [comment]
Thanks.  This was next on my list.
