### ISSUE TITLE
Missing Render Modes using 'Full' Render Quality (macOS Big Sur)

### ISSUE THREAD

**Issue by jay-b** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#310]
The following Render modes do not seem to work in the viewport using 'Full':

_Direct Illumination, Direct_Illumination no Shadows, Ambient Occlusion, Diffuse_

Still digging around and testing but an exported .exr file also seems to be missing data for _Ambient Occlusion_, and the _Direct Reflect_ and _Direct Illumination_ passes seem to be the same data (see attached After Effects screenshot, 4th row down, 4th and 5th from left is the _Direct Reflect_ and _Direct Illumination_ pass).

Appologies if this is a known issue, etc. I couldn't seem to find see any info about it.

**System Setup** (Environment)
macOS 11.4
6800XT
Blender 2.92
GPU Rendering
RPR 3.1.0

![Screenshot 2021-07-02 at 10 40 57](https://user-images.githubusercontent.com/900423/124255762-713b1300-db22-11eb-9176-81a34194253d.png)

**Comment by bsavery** [comment]
No that's ok.  The view modes not working is know.  Direct reflect and direct illumination should work.  Can you export those aovs individually?
