### ISSUE TITLE
Cryptomatte pass issue in After Effects (macOS Big Sur)

### ISSUE THREAD

**Issue by jay-b** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#311]
I cannot get the Cryptomatte pass to work in After Effects. Usually with a Cycles .exr file imported into AE, EXtractoR will automatically detect a Cryptomatte pass and add a Cryptomatte effect to provide controls to isolate objects / materials, etc. Have tried adding a Cryptomatte effect to the layer which doesn't work.

If I've missed something please let me know. I hope this can be resolved as it's a critical part of post production work.

Have zipped the following files:

EXR_Test.01.01-Full.exr
RPR_JB_RenderPasses_01.01-BugReport.blend
RPR-exr_tests.aep

https://drive.google.com/file/d/1cWvbuME_lUc9GIK22-uyPmW6gDgHMtDr/view?usp=sharing

**System Setup** (Environment)
macOS 11.4
6800XT
Blender 2.92
GPU Rendering
RPR 3.1.0
After Effects 18.2.1

![Screenshot 2021-07-02 at 10 50 34](https://user-images.githubusercontent.com/900423/124256564-5b7a1d80-db23-11eb-819a-a88a00be2a23.png)

**Comment by bsavery** [comment]
Hi there.  There's an issue in blender that exrs they export do not have the crypto matte meta data attached (this is an issue with external render engines).  I don't really have a good solution here unless you wanted to save the exrs directly from RPR and not go through Blender

The other option is to save a .rpr file and render from the command line with RPRSRender64.exe
