### ISSUE TITLE
ProRender on M1 Macs?

### ISSUE THREAD

**Issue by AlxndrTheWretch** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#317]
More of a request than an issue, but I tried installing the ProRender plugin in the ARM version of Blender now available to run natively on M1 Macs but it gave me an error saying it was the wrong architecture. I tried installing it on the Intel version of Blender and it worked great. Would we be able to get a version of the plugin to run natively on M1 now that Blender can run natively on the M1? :)

**Comment by bsavery** [comment]
We're hoping to have support for ARM in the next major release.  Stay tuned.

**Comment by AlxndrTheWretch** [comment]
Awesome!
