### ISSUE TITLE
Errors enabling 3.2 in Blender 2.931 

### ISSUE THREAD

**Issue by studioEL** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#318]
Hello,

I'm new to both Blender an GitHub, so apologies if this s not the right place to post. I was unable to find anywhere else to ask my question.

I was unable to enable the ProRender add-on in Blender. Blender crashes and I get a lengthy error message. I can post it in its entirely here but I will post what I think i a relevant snippet below. 

I also tried it with an older version of Blender and the 3.1 version and I get the same error.

1.
Mac Pro 5,1  3.33 GHz 6-Core Intel Xeon
Mojave 10.14.6
48 GB 1333 MHz DDR3
Radeon RX 580 8 GB

ProRender 3.2 on Blender 2.93.1 (and older versions too)

2.
Cannot enable ProRender add-on after installing. Blender crashes. 

3. 
Error message (in part)

...
Exception Type:        EXC_CRASH (SIGKILL)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: _objc_opt_new
  Referenced from: /Users/USER/Library/Application Support/Blender/*/libTahoe64.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib

**Comment by studioEL** [comment]
I did some more searching and now see that Mojave may not be supported. 
I just wanted to check since the User Guide says that it supports 10.14+.

**Comment by bsavery** [comment]
Tahoe (legacy mode) should work in Mojave.  Although we do recommend 10.15 or later.
