### ISSUE TITLE
Feature request: Highlight compression for Color mapping

### ISSUE THREAD

**Issue by odil24** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#323]
As you may know in Corona Renderer has this kind of option for high quality exposure intensity compressor which is helps to increase the rendered images. Is it possible to add them?

**Comment by bsavery** [comment]
Again, please post links to their feature, we can't guess

**Comment by odil24** [comment]
> 
> 
> Again, please post links to their feature, we can't guess
maybe this one:
https://github.com/ahester57/compress_and_highlight

or this one:
https://coronarenderer.freshdesk.com/support/solutions/articles/5000515646-what-is-highlight-compression-

and this one too:
http://rawpedia.rawtherapee.com/Exposure#Highlight_Compression

**Comment by bsavery** [comment]
The settings are different of course, but I think you can do something similar with the "Clamp Radiance" setting:  https://radeon-pro.github.io/RadeonProRenderDocs/en/plugins/blender/quality.html

**Comment by odil24** [comment]
> The settings are different of course, but I think you can do something similar with the "Clamp Radiance" setting: https://radeon-pro.github.io/RadeonProRenderDocs/en/plugins/blender/quality.html

I think no because when we're change clamping itself it will give us extra darkness then clamping highlighted areas. Just see how Corona has organised with Highlight compression feature and plus doesnt poor HDRI around the world also than RPR does poor world with Clamping.

**Comment by bsavery** [comment]
I see.  So, I don't think this is something we want to do in the renderer.  Actually Corona kind of explains why in that link you sent:

"Note: always use highlight compression value of 1 when you are saving render elements for later composing or saving 32-bit files for post production."

IMO a better solution is to just do 32 bit rendering (which we do) and then do tone mapping as post if you want to put the render in a 8 bit image to compress the highlights.  Using something like
https://docs.blender.org/manual/en/latest/compositing/types/color/tone_map.html
Gives you much better options than doing this in the renderer itself.

**Comment by odil24** [comment]
ok. thanks
