### ISSUE TITLE
How to render Transparent background?

### ISSUE THREAD

**Issue by odil24** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#326]
I'm still confusing with Transparent background (TB) feature. My steps like this:
1. Setup World
2. Add HDRI 
3. Increase HDRI intensity to something 10 (it gives me lighten effect inside scene
4. Enable TB
5. In my case for example the room with two windows assigned with Glass shader on both
6. HDRI shoot In/Dir lights by the windows
7. After final render/viewport render the windows goes to overexposed 

![IMG_20210714_071845_303](https://user-images.githubusercontent.com/64298012/125550363-af539ff2-38fb-4426-b49c-a024bc87e416.jpg)
 Here you can see how is light overexposed than in real life. Thats why I'd like to cuttoff with TB but without succes.

**Comment by ARozghon** [comment]
![image](https://user-images.githubusercontent.com/68949117/132347326-84c7a907-37b0-44db-81a6-edba3aa7dd59.png)
for transparent BG, please, use Film Settings
for bigger light bounce inside interior use Quality Settings
![image](https://user-images.githubusercontent.com/68949117/132348167-67a3dded-c4f2-4826-9c5e-5ce3904042d9.png)
like Diffuse, and Total Ray Depth
