### ISSUE TITLE
Will it ever work on Macbook Pro '16 with AMD 5500M?

### ISSUE THREAD

**Issue by levybergman** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#327]
Trying to use it on my 
- 2019 Macbook Pro '16 with 
- AMD 5500M 
- in Blender 2.93.1
and somehow it just gives a horrible render in viewport with crazy pixels
![Screen Shot 2021-07-12 at 5 53 37 PM](https://user-images.githubusercontent.com/85265718/125627584-36159970-94c9-40a4-9078-1c4664b852f8.png)
![Screen Shot 2021-07-14 at 9 08 42 AM](https://user-images.githubusercontent.com/85265718/125627588-dd132284-fb7d-4f1d-b978-44abe1b74546.png)
.

Testing the very basic default scene.

Thanks for checking it.
[AMD_Radeon_Pro_test.blend.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6816245/AMD_Radeon_Pro_test.blend.zip)

**Comment by bsavery** [comment]
Hi there.  I see the same thing.  Please disable viewport sampling and denoising in the viewport settings

**Comment by levybergman** [comment]
Thanks a lot @bsavery !!!
It works like a dream now.
