### ISSUE TITLE
Machine learning Denoiser is poor quality with textures

### ISSUE THREAD

**Issue by odil24** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#332]
In any case when i used bump+disp maps with textures it gaves me some poor denoised texture on the surfaces.

**Comment by odil24** [comment]
here hoiw it looks: 
https://i.postimg.cc/W10dXD5v/untitled.png

**Comment by bsavery** [comment]
Can you include a scene please?

**Comment by odil24** [comment]
no, but if the scene objects are assigned shaders with normal maps or bump or displacement so it will gives this kind of issues

**Comment by ARozghon** [comment]
![image](https://user-images.githubusercontent.com/68949117/132346894-cb6f9d10-315b-40ab-9c4d-78b063a1cf53.png)
hi, did you try all ML denoiser settings, for example, deactivated FP16, activated Color AOV only etc?
