### ISSUE TITLE
No compatible devices to create image filter error

### ISSUE THREAD

**Issue by EntityinArray** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#333]
## System Setup (Environment)
GPU: Intel HD Graphics 4400
CPU: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
OS: OpenSUSE Tumbleweed
Blender version 2.93.1

## Issue
When enabling render preview or trying to render anything, renderer gives a blank screen

```
Read prefs: /home/entityinarray/.config/blender/2.93/config/userpref.blend
2021-07-18 12:01:11,285 INFO rpr.engine.init [139753937142016]:  Core version: 2.2.4 build 0x274328c
2021-07-18 12:01:11,290 INFO rpr.engine.init [139753937142016]:  RIF version: 1.7.1 build 0xfe53c43a
2021-07-18 12:01:56,099 ERROR rpr.init [139753937142016]:  No compatible devices to create image filter EXCEPTION: Traceback (most recent call last):
  File "/home/entityinarray/.config/blender/2.93/scripts/addons/rprblender/__init__.py", line 160, in view_update
    self.engine.sync(context, depsgraph)
  File "/home/entityinarray/.config/blender/2.93/scripts/addons/rprblender/engine/viewport_engine_2.py", line 330, in sync
    super().sync(context, depsgraph)
  File "/home/entityinarray/.config/blender/2.93/scripts/addons/rprblender/engine/viewport_engine.py", line 511, in sync
    self.setup_image_filter(self._get_image_filter_settings(scene))
  File "/home/entityinarray/.config/blender/2.93/scripts/addons/rprblender/engine/engine.py", line 122, in setup_image_filter
    self._enable_image_filter(settings)
  File "/home/entityinarray/.config/blender/2.93/scripts/addons/rprblender/engine/engine.py", line 209, in _enable_image_filter
    self.image_filter = image_filter.ImageFilterML(
  File "/home/entityinarray/.config/blender/2.93/scripts/addons/rprblender/engine/image_filter.py", line 46, in __init__
    self.context = rif.Context(rpr_context)
  File "/home/entityinarray/.config/blender/2.93/scripts/addons/rprblender/pyrprimagefilters.py", line 132, in __init__
    raise RuntimeError("No compatible devices to create image filter")
RuntimeError: No compatible devices to create image filter
```

Does that mean that my hardware is incompatible?

## Steps to Reproduce
- Open blender
- Enter rendered view

Thanks for help!

## Update
Everything works fine if i disable Viewport Upscaling and Viewport Denoising

**Comment by odil24** [comment]
> ## System Setup (Environment)
> GPU: Intel HD Graphics 4400
> CPU: Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
> OS: OpenSUSE Tumbleweed
> Blender version 2.93.1
> 
> ## Issue
> When enabling render preview or trying to render anything, renderer gives a blank screen
> 
> ```
> Read prefs: /home/entityinarray/.config/blender/2.93/config/userpref.blend
> 2021-07-18 12:01:11,285 INFO rpr.engine.init [139753937142016]:  Core version: 2.2.4 build 0x274328c
> 2021-07-18 12:01:11,290 INFO rpr.engine.init [139753937142016]:  RIF version: 1.7.1 build 0xfe53c43a
> 2021-07-18 12:01:56,099 ERROR rpr.init [139753937142016]:  No compatible devices to create image filter EXCEPTION: Traceback (most recent call last):
>   File "/home/entityinarray/.config/blender/2.93/scripts/addons/rprblender/__init__.py", line 160, in view_update
>     self.engine.sync(context, depsgraph)
>   File "/home/entityinarray/.config/blender/2.93/scripts/addons/rprblender/engine/viewport_engine_2.py", line 330, in sync
>     super().sync(context, depsgraph)
>   File "/home/entityinarray/.config/blender/2.93/scripts/addons/rprblender/engine/viewport_engine.py", line 511, in sync
>     self.setup_image_filter(self._get_image_filter_settings(scene))
>   File "/home/entityinarray/.config/blender/2.93/scripts/addons/rprblender/engine/engine.py", line 122, in setup_image_filter
>     self._enable_image_filter(settings)
>   File "/home/entityinarray/.config/blender/2.93/scripts/addons/rprblender/engine/engine.py", line 209, in _enable_image_filter
>     self.image_filter = image_filter.ImageFilterML(
>   File "/home/entityinarray/.config/blender/2.93/scripts/addons/rprblender/engine/image_filter.py", line 46, in __init__
>     self.context = rif.Context(rpr_context)
>   File "/home/entityinarray/.config/blender/2.93/scripts/addons/rprblender/pyrprimagefilters.py", line 132, in __init__
>     raise RuntimeError("No compatible devices to create image filter")
> RuntimeError: No compatible devices to create image filter
> ```
> 
> Does that mean that my hardware is incompatible?
> 
> ## Steps to Reproduce
> * Open blender
> * Enter rendered view
> 
> Thanks for help!
> 
> ## Update
> Everything works fine if i disable Viewport Upscaling and Viewport Denoising

I think yes. Your hardware isn't supported and especially error is related with 2.93.1 also. And also I think you are using not latest build like this:
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.2.8

**Comment by bnagirniak** [comment]
Yes, your devices are incompatible for image filter, you can disable it for viewport in Render Properties->Sampling->Viewport & Preview Sampling->[Viewport Denoising , Viewport Upscaling]

**Comment by bsavery** [comment]
My Suggestion would be to use CPU rendering or the denoiser built in to blender.
