### ISSUE TITLE
RAM grows exponentially for no reason

### ISSUE THREAD

**Issue by riouxr** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#347]
Every issue should include 3 things:
1.  System setup (GPU, CPU, OS version, Blender version)
2.  **Most ideally** a .blend scene to reproduce this simply.  **SCREENSHOTS OR RENDERS ARE NOT A SCENE FILE**
3.  What the expected behavior or effect is.  If possible include the error message.  

You can get more information on the error message by opening Window -> Show System Console from blender and copying that text here.  On MacOS launch Blender from the Terminal.

Blender 2.93.3
Mac OS 10.15.7
Radeo Pro Vega 64
addon v3.2.2

I opened Blender with the addon, default scene with just a cube, a camera and a light, and turned on viewport render. The memory jumped to 15 gigs for Blender and still nothing rendered on screen. I had to force quit. I tried again but this time rendering in the render view window. Same thing.

**Comment by bsavery** [comment]
This is probably an issue with kernel compilation.  Investigating...

**Comment by Aliprandini** [comment]
Don't see that issues on the 5700 XT with BigSur and laters Blender+RPR.

I don't think that developers should spent an time for Mac OS 10.15.x and Vega series card. Vega series card are bad for Metal 2 performance.

**Comment by riouxr** [comment]
Oh! Fun! Thanks for the support... They are just the cards in thousands and thousands of iMacPro…

**Comment by Aliprandini** [comment]
I am not from support team. I'm just normal user.
