### ISSUE TITLE
Can't install add-on 

### ISSUE THREAD

**Issue by Molvado** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#354]
System Information
Operating system: MacOs Big sure
Graphics card: Radeon Pro 575X 4 gb

Blender Version
Broken:
(example: 2.92.0 release)
(example: 2.80, edbf15d3c044, blender2.8, 2018-11-28, as found on the splash screen)
Worked: (optional)

**I get an error when trying to install the addon. Tried on Blender versions 2.93.1, 2.93.4, 2.92.0
Traceback (most recent call last):

File "/Applications/Blender.app/Contents/Resources/2.92/scripts/modules/addon_utils.py", line 351, in enable
  mod = __import__(module_name)
File "/Users/antonbobrovskiy/Library/Application Support/Blender/2.92/scripts/addons/rprblender-6/__init__.py", line 36, in <module>
  from .utils import logging, version_updater
File "/Users/antonbobrovskiy/Library/Application Support/Blender/2.92/scripts/addons/rprblender-6/utils/__init__.py", line 27, in <module>
  import rprblender
ModuleNotFoundError: No module named 'rprblender'

Exact steps for others to reproduce the error
Based on the default startup or an attached .blend file (as simple as possible).

**Comment by benjamindahl** [comment]
Maybe you need to install the cffi python module inside blender. I had to fulfill this requirement to be able to install…

/Applications/Blender/[path to python inside blender] -m pip install cffi

*just guessing*

**Comment by bsavery** [comment]
CFFI is installed automatically the first time you enable the plugin. @Molvado did you solve this?

**Comment by maccesch** [comment]
The answer from @benjamindahl did the trick for me

**Comment by MRIO** [comment]
This worked for me as well!
