### ISSUE TITLE
Crashing when trying to render using GPU after macOS update to 11.6 (20G165)

### ISSUE THREAD

**Issue by naidoff** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#363]
## Issue
After the last macOS update (from previous version to 11.6 (20G165)) rendering using GPU come to crash. If i turn off GPU in render setting and render using only CPU - all is ok.

## Steps to Reproduce

Trying to rendering something using GPU.

Also in live rendering when GPU rendering is turned on.

## System Setup (Environment)

macOS Big Sur 11.6 (20G165)

MacBook Pro (16-inch, 2019)
2,4 GHz 8‑core Intel Core i9
16 GB 2667 MHz DDR4
AMD Radeon Pro 5300M 4 GB
Intel UHD Graphics 630 1536 MB

 
Blender 2.93.4
2021.08.31 09:23
Hash: b7205031cec4
Branch: master

If using GPU.

## Detailed Description

I had try to reinstall Blender app (Application Support/Blender/ was cleaned) and RPR, but after Blender reinstall I can't install RPR.
Error text: 
Traceback (most recent call last): File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable mod = _import_(module_name) File "/Users/arsenii/Library/Application Support/Blender2.93/scripts/addons/rprblender/init_.py", line 39, in <module> from .engine.engine import Engine File "/Users/arsenii/Library/Application Support/Blender/2.93/scripts/addons/rprblender/engine/init_.py", line 25, in <module> if utils.IS_DEBUG_MODE: AttributeError: module 'rprblender.utils' has no attribute 'IS_DEBUG_MODE'

**Comment by bnagirniak** [comment]
@naidoff can you please try to remove /Users/arsenii/Library/Application Support/Blender/2.93/scripts/addons/rprblender folder and install RPR plugin again?

**Comment by naidoff** [comment]
@bnagirniak I've already tried it. nothing changes. when I reinstall the addon this folder reappears. tried several times.

**Comment by bnagirniak** [comment]
That's weird, ok, we'll look your issue more closely.

**Comment by hofill** [comment]
I have the same specs, same OS version, and I get the same error. Removing the rprblender folder using sudo does not fix the issue for me.

**Comment by hofill** [comment]
> I have the same specs, same OS version, and I get the same error. Removing the rprblender folder using sudo does not fix the issue for me.

After a bunch of testing, I've updated my python version, restarted blender AFTER installing RPRBlender, and then it enabled and all worked fine. I doubt updating the python version was part of the fix, however.

**Comment by bsavery** [comment]
Out of curiosity what python version did you have on your system?

**Comment by hofill** [comment]
> Out of curiosity what python version did you have on your system?
> 
> 

If that question was for me, iirc 3.9
