### ISSUE TITLE
GPU doesn't render particles w/ motion blur correctly

### ISSUE THREAD

**Issue by kintuX** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#368]
Windows 10, Blender 2.93.5, RPR 3.2.20
AMD TR1950X, 64GB RAM, GTX1070 8GB, Quadro M5000 8GB

CPU result:
![mBlur_rpr(CPU)](https://user-images.githubusercontent.com/61623470/135726424-1a0df842-f72b-4321-b620-9e544a203e34.jpg)

GPU result:
![mBlur_rpr(GPU)](https://user-images.githubusercontent.com/61623470/135726443-e09e810f-74ce-4813-bf6c-d7c46720e553.jpg)

Scene file
[mBlur.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/7271901/mBlur.zip)
:

**Comment by ARozghon** [comment]
this issue was fixed with the fresh core 2.2.9 update, so, waiting for a plugin update with core 2.2.9 or 2.2.10 with the current fix

**Comment by bsavery** [comment]
Please check with latest version and reopen if an issue

**Comment by kintuX** [comment]
Confirming, issue is resolved. Great work!
