### ISSUE TITLE
3.3.2 Not using CPU when both CPU and GPU rendering selected in Blender.

### ISSUE THREAD

**Issue by FireAngelOfLondon** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#386]
Every issue should include 3 things:
1.  System setup (GPU, CPU, OS version, Blender version)
2.  **Most ideally** a .blend scene to reproduce this simply.  **SCREENSHOTS OR RENDERS ARE NOT A SCENE FILE**
3.  What the expected behavior or effect is.  If possible include the error message.  

You can get more information on the error message by opening Window -> Show System Console from blender and copying that text here.  On MacOS launch Blender from the Terminal.

## Issue

CPU rendering works well but of course is slow, GPU rendering is faster, but unlike previous versions when I select both the CPU is not used, so it is no faster than when GPU alone is selected.
## Steps to Reproduce

As far as I can tell any scene seems to produce this behaviour.
## System Setup (Environment)

12 core Mac Pro, 64GB RAM, AMD RX-580 8GB graphics card, Mac OS X Catalina (10.15.7).  Blender 2.93.5.
## Detailed Description

Can we have both CPU and GPU rendering working at the same time again, please?  It was a great feature.

**Comment by bsavery** [comment]
Hi there.  We're fixing this in an upcoming 3.4 release for macOS!   Thanks.
