### ISSUE TITLE
Viewport result is black if both upscaling and denoising are active for preview

### ISSUE THREAD

**Issue by TeaNotes** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#387]
## Issue
As the title says, when both upscaling and denoising are active for viewport preview, the end result will be a black frame. It does render up until that point, this only occurs at the very end of sampling and denoising.

## Steps to Reproduce
Simply have both Viewport Scaling and Denoising active and start previewing the render in viewport. After sampling is done, result should be black (it is in my case). The scene attached is extremely simple, just a plane, sphere and spot.

Disabling either Denoising or Upscaling (or both) fixes the issue.

![image](https://user-images.githubusercontent.com/26819757/138721504-3e7698e3-9fce-4203-a8b2-1d74804eb543.png)

## System Setup (Environment)
Windows 10 2H1 (19043.1288)
RTX 3090, 2990WX, NVIDIA Studio driver 471.41
[2021--10--25-Viewport_UpscaleDenoise_bug.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/7411468/2021--10--25-Viewport_UpscaleDenoise_bug.zip)

Blender 2.93
GPU rendering

If you need further data, please let me know.

**Comment by cgvirus** [comment]
Hi,
I can repro this in:
 
GeForce GTX 950
Linux Mint 20
Blender 2.93.7 and Blender 3

**Comment by VascoPi** [comment]
> ## Issue
> As the title says, when both upscaling and denoising are active for viewport preview, the end result will be a black frame. It does render up until that point, this only occurs at the very end of sampling and denoising.
> 

Cannot reproduce on:
Windows 10, Ubuntu 20.04.
Blender 2.93, 3.00
Radeon Vega56 , 6700XT

**Comment by VascoPi** [comment]
> Hi, I can repro this in:
> 
> GeForce GTX 950 Linux Mint 20 Blender 2.93.7 and Blender 3
> 
> Enabling any of these two:
> 
> * denoise
> * upscale
> 

Have no GeForce GTX 950 to test. Please try a different driver.
