### ISSUE TITLE
Installed Latest Radeon Drivers and Added ProBlenderAddon but Blender Won't Open

### ISSUE THREAD

**Issue by othermornings** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#390]
## Issue
When I open Blender it closes after telling me to install the latest driver for my graphics card.

## Steps to Reproduce

https://gyazo.com/9a7b1ad359ccb1c46d1e79f3ee85ebf8

## System Setup (Environment)
 Windows 10
 GPU: AMD Radeon RX 6700 XT / CPU: Intel(R) Core(TM) i7 - 10700K CPU @ 3.80GHz / DRIVER: 21.30.31.01-211021a-372855E-RadeonSoftware
 Blender 2.93.5

## Detailed Description
After updating my Radeon Driver and copying over the RadeonProRenderBlenderAddon to Blender's addon folders, I was still unable to use Blender. Every time I open the program I receive that same startup and message as shown above with the screenshot. I followed the instruction of this video: https://youtu.be/NgTLzvTWcUI and once those steps failed to change my situation, I was directed here to ask for help. I don't know what else I should do or if I'm missing a step, so any advice or instruction would help a lot. Thank you.

**Comment by bsavery** [comment]
This doesn't appear to be a ProRender related issue.  Should be related to the driver
