### ISSUE TITLE
Orthographic Camera Shift doesn't work with RPR

### ISSUE THREAD

**Issue by Aliprandini** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#394]
RPR 3.3.4, Blender 2.93.6, Mac OS 11.6.1, 5700 XT

While rendering with Orto Camera view RPR doesn't react to any camera XY shift option from editor menu.

**Comment by bsavery** [comment]
Closing.  Follow instructions for attaching a scene please.
