### ISSUE TITLE
Imported VDBs not rendering

### ISSUE THREAD

**Issue by AlexanderThePilgrim** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#397]
System:
Ryzen 3700X
Radeon Pro W6800
Windows 11
Blender 2.93.5

Hi,
When I import VDBs into my scene, they don't render at all. It's just blank where the volume is, renders fine in cycles. I have tried this on a system running Windows 10 with 2x 2080ti's and has the same issue.

**Comment by bsavery** [comment]
Please attach a scene. And perhaps the vdb as well

**Comment by bnagirniak** [comment]
Sorry, VDB isn't supported in plugin for Blender 2.93+ due to library conflicts. We have plans to fix this.

**Comment by bsavery** [comment]
We now support openvdb with 3.2 and the latest plugin
