### ISSUE TITLE
Blender/GPU crash when rendering animation on Radeon VII

### ISSUE THREAD

**Issue by MakramDaou** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#4]
Hi,
I've already reported this issue back in February.
https://community.amd.com/thread/248795
The problem started with RPR 2.2.1 & has not been fixed since then (still in RPR 2.4.11).
Only happens with GPU rendering (no problem when set to CPU only) and on any scene. The more complex it is the less frames are rendered before RAM usage suddenly skyrockets and the system crashes (now it literally reboots by itself). This is on Windows10 1909, i7 6700K, 32GB Ram, NVMe SSDs &  Radeon VII (with any driver released in the past 8 months)
![Annotation 2020-02-08 184733 (2)](https://user-images.githubusercontent.com/46979415/81868242-54d0c580-9572-11ea-86af-b4b2f07b9e33.jpg)

Similar issues are being reported by others:
https://community.amd.com/thread/252437

Cheers

Makram

**Comment by bnagirniak** [comment]
Is it Full render quality?
Also, provide log file rprblender.log with debug info with this issue please. To do that open config.py in plugin folder and change corresponded lines to:
```
logging.limit_log('', level_show_min=logging.DEBUG)
pyrpr_log_calls = True
```

**Comment by MakramDaou** [comment]
It's in Full render quality. 
Log file is attached below.

Cheers
[rprblender.log](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/4637666/rprblender.log)

**Comment by bnagirniak** [comment]
Thank you for provided log and info, we'll be looking it.

**Comment by djtutorials** [comment]
What drivers are you using? I have two Radeon VIIs and I stopped using Adrenalin 2020 gaming since it caused computer crashes and I am using the Pro drivers instead. You can choose this by clicking the dropdown and scrolling to the pro drivers link (usually the 3rd download down the list). I haven't had any crashes using RPR or Cycles since.

**Comment by MakramDaou** [comment]
I'm on the latest Pro drivers release. But this RPR bug happens with every driver released in the past 10+ months & has specifically started with RPR 2.2.1.

**Comment by djtutorials** [comment]
That's odd... are you using Windows? Linux? MacOS? I haven't had any stability issues with RPR in my system as long as I don'tr use AMD's game drivers. I am assuming you have used AMD's cleanup utility to completely remove all drivers before installing the pro drivers?

**Comment by MakramDaou** [comment]
The specs are in the OP. 
It's not a driver related stability issue but an RPR bug when rendering an animation (not single still frames) using GPU compute on the Radeon VII since RPR 2.2.1.

You could try it your self. Open Blender. Don't touch the cube. Select RPR as the renderer. Change last frame to something like 10000. Hit CTRL+F12..wait & see. It usually crashes after 150+ frames on this simple scene. The more complex the scene the less frames are rendered before the crashs.

**Comment by djtutorials** [comment]
Understood- have you tested using CMD prompt rendering?

**Comment by bnagirniak** [comment]
Rendering animation we do in following way:
1. export scene
2. render
3. clear scene and delete all objects
So, we don't recreate context and scene. Probably better would be recreate rendering context.
We are discussing with core team at which side it is better to do and why we have memory leak.

**Comment by bnagirniak** [comment]
Issue is fixed, closing.
