### ISSUE TITLE
often error crush when use blender 3.0 with prorender3.3.9

### ISSUE THREAD

**Issue by devilpie** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#419]
Every issue should include 3 things:
1 System info
GPU AMD Radeon Pro 5500M 4 GB, CPU i9 2.3GHz, macOS 12.0.1, Blender version blender3.0.
2 error info
(1) Collection | Cube
ERROR | IF call ContextExecuteCommandQueue(<pyrprimagefilters.Context object at Ox13182a790>, <pyrprimagefilters.CommandQueue
object at 0x13182a9a0>, <cdata 'void * NULL>, <data 'void *' NULL>,
<data 'void *' NULL>) returned error code <-3>
with error message: " Please see logs for more details.
![001](https://user-images.githubusercontent.com/61256748/145529441-b596a1e6-9ed7-4599-84e4-f99761158034.jpeg)

**Comment by bsavery** [comment]
Try disabling the viewport denoising and upscale in the viewport settings.

**Comment by devilpie** [comment]
it's really a joke that running blender on MacBook Pro (intel)...-_-!
