### ISSUE TITLE
Blender 3x Error - Can't Activate

### ISSUE THREAD

**Issue by brunocalado** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#424]
Blender 3x Error - Can't Activate

## Issue
I can't activate the add on.

## Steps to Reproduce
Click the activate add on button.

## System Setup (Environment)
Radeon™ RX 550, i9 Intel, Win10, Blender 3.

## Detailed Description
![image](https://user-images.githubusercontent.com/4999783/146040882-e7f3a279-f8f9-44da-9ee0-6c46cee8f0d0.png)

**Comment by bsavery** [comment]
Fixed.  Use the weekly build from https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.3.11
