### ISSUE TITLE
Blender RPR black viewport

### ISSUE THREAD

**Issue by PcSolaar** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#431]
CPU: ryzen 3 2200G with 8gb DDR4 on MSI b350 pc mate
GPU: XFX Rx 460 4GB with latest Radeon pro drivers 
OS: Windows 10 pro 21H1
Blender 2.93.1

Issue
Hi everyone, I have received my rx460 a few weeks ago and I am still tinkering with it. I was using the materials for texturing and it was working fine until I tweaked a few materials and then material view or rendering will not rendre, all black. I am new to radeon prorender and started Blender this year as a hobby/potentialy sidejob, so help would be appreciated. 

Will be attached, the crash log from blender, the screen cap of the error code, the system info from blender, but the actual .blend file is apparently not supported so It does not upload.

![crash blender](https://user-images.githubusercontent.com/55066754/147405535-63a3d105-1c28-4774-a84b-3c71b25d4b09.png)
[Monument de l'independance.crash.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/7776854/Monument.de.l.independance.crash.txt)
[system-info.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/7776855/system-info.txt)

**Comment by VascoPi** [comment]
Thanks for sharing the issue. Please find a way to attach either blend file or link.

**Comment by gertkjerslev** [comment]
Hi, I get almost the same error (with the default cube) on my Radeon Pro 580 (iMac). I'm using the mac version 3.0 of Blender.
<img width="859" alt="blender_renderpro_error" src="https://user-images.githubusercontent.com/16758213/149029795-2bacfc5c-0169-44a4-8af5-fb3a4562a5fb.png">

**Comment by VascoPi** [comment]
@gertkjerslev related issue https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/419. Please try a few more tests with viewport denoiser - on/off, upscale - on/off.

**Comment by jiriks74** [comment]
I had the same issue on Linux, as mentioned above, turning off denoiser (and upscaler) solved it for me. Sometimes the denoiser, sometimes the upscaler hanged up my whole system

**Comment by bsavery** [comment]
There is also an option in the viewport settings to use a "4gb gpu".  Please try that.

**Comment by jiriks74** [comment]
@bsavery where's that option? I'll try it, but I don't see how using more vram would fix broken upscaler and denoiser. Why is this closed as resolved without any confirmation that it helped?

**Comment by bsavery** [comment]
It's under the "Render quality" options.  It solves the issue because the denoiser and renderer are competing for memory usage.
