### ISSUE TITLE
Install assistance on Linux

### ISSUE THREAD

**Issue by ag3nt327** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#432]
System setup: NVIDIA RTX 4000 (running driver version 470.86), AMD RYZEN 9 3950x, Rocky Linux 8.5, Blender 2.93.7

## Issue:
Upon trying to activate the RPR add-on (RadeonProRenderForBlender_3.3.15_Ubuntu20.zip), I'm met with the following error in the Blender terminal window:

> Traceback (most recent call last):
>   File "/opt/blender/blender-2.93.7-linux-x64/2.93/scripts/modules/addon_utils.py", line 351, in enable
>     mod = __import__(module_name)
>   File "/home/user/.config/blender/2.93/scripts/addons/rprblender/__init__.py", line 39, in <module>
>     from .engine.engine import Engine
>   File "/home/user/.config/blender/2.93/scripts/addons/rprblender/engine/__init__.py", line 62, in <module>
>     pyrprimagefilters.init(rif_lib_dir, logging.Log(tag='rif'), config.pyrprimagefilters_log_calls)
>   File "/home/user/.config/blender/2.93/scripts/addons/rprblender/pyrprimagefilters.py", line 46, in init
>     ctypes.CDLL(str(lib_dir / lib_name))
>   File "/opt/blender/blender-2.93.7-linux-x64/2.93/python/lib/python3.9/ctypes/__init__.py", line 374, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/user/.config/blender/2.93/scripts/addons/rprblender/libRadeonML.so.0)

I then issue the following command: **strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX**

> GLIBCXX_3.4
> GLIBCXX_3.4.1
> GLIBCXX_3.4.2
> GLIBCXX_3.4.3
> GLIBCXX_3.4.4
> GLIBCXX_3.4.5
> GLIBCXX_3.4.6
> GLIBCXX_3.4.7
> GLIBCXX_3.4.8
> GLIBCXX_3.4.9
> GLIBCXX_3.4.10
> GLIBCXX_3.4.11
> GLIBCXX_3.4.12
> GLIBCXX_3.4.13
> GLIBCXX_3.4.14
> GLIBCXX_3.4.15
> GLIBCXX_3.4.16
> GLIBCXX_3.4.17
> GLIBCXX_3.4.18
> GLIBCXX_3.4.19
> GLIBCXX_3.4.20
> GLIBCXX_3.4.21
> GLIBCXX_3.4.22
> GLIBCXX_3.4.23
> GLIBCXX_3.4.24
> GLIBCXX_3.4.25
> GLIBCXX_DEBUG_MESSAGE_LENGTH

And it appears that **GLIBCXX_3.4.26** is in fact NOT found. Would appreciate the community's help here. 

If it helps a gcc --version outputs the following:

> gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)

However, I did not self compile. I simply download the RPR .zip file from the AMD site.

## Steps to Reproduce
Load Rocky Linux / CentOS 8
Install NVIDIA drivers
Download latest LTS version of Blender
Attempt to enable the latest RPR plugin

## System Setup (Environment)
Rocky Linux 8.5
AMD RYZEN 9 3950x
NVIDIA RTX 4000 (driver version 470.86)
Blender 2.93.7

**Comment by VascoPi** [comment]
I will try on my Ubuntu system.

**Comment by ag3nt327** [comment]
Thanks!

**Comment by bsavery** [comment]
Hello we only officially support centos and redhat
