### ISSUE TITLE
Voronoi and noise textures are not 3D with Geometry "position"

### ISSUE THREAD

**Issue by lenhone** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#436]
## Issue
When using Radeon ProRender and connecting the Geometry "position" output to the "vector" input of a Voronoi or noise texture results in 2D texturing.

The image below shows EEVEE and CYCLES correctly applying the Voronoi texture in 3 dimensions while RPR incorrectly applies the texture in 2 dimensions.
![rpr](https://user-images.githubusercontent.com/96949377/148015436-8feee0c2-43e1-49ac-bf39-243ed05b97c2.png)

## Steps to Reproduce
In attached .blend change from EEVEE to Radeon ProRender while observing "rendered" in view-port.
[rpr.blend.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/7805671/rpr.blend.zip)

## System Setup (Environment)
System setup - GPU: RX 6800, CPU: 5900X, OS: Linux, Blender Version: 3.0.0, RPR Plugin Version: [3.3.15]

**Comment by VascoPi** [comment]
Thanks for the report. Also found the same issue with Noise Texture Node. We will try to fix it.

**Comment by lenhone** [comment]
Thanks for attempting to fix issue. I agree the Noise Texture node suffers from the same issue.

**Comment by lenhone** [comment]
At this point I think the simplest solution is for me to close my logs #440, #436 and #522. RPR is not deigned to be compatible with .blend files developed with Cycles.
