### ISSUE TITLE
Interactive Render Quality Does Not Render Emissive Surfaces Properly

### ISSUE THREAD

**Issue by tedliosu** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#437]
## Issue
As you may see below, the emissive surfaces on the inner edges of the cubes in the demo blend file I'm using (from the Radeon ProRenderer documentation) glow when rendered using "Final" Render Quality, but do not glow at all for some unexpected reason when rendered using "Interactive Render Quality".
#### "Final" Render Quality Result
![lights_final_render](https://user-images.githubusercontent.com/25697946/148159784-6b1dc3aa-be28-48d0-a916-cb7c0a44fa15.png)
#### "Interactive" Render Quality Result
![lights_interactive_render](https://user-images.githubusercontent.com/25697946/148159786-d97c0dd6-0b03-4bed-b2ec-507ae178dbf6.png)

## Steps to Reproduce
1. Download [this demo scene](https://github.com/Radeon-Pro/Doc-Assets/raw/master/scenes/blender/lights.blend).
2. Open the downloaded demo scene in Blender.
3. Open the "Render Properties" Tab in the right-hand pane of the default "Layout" workspace.
4. Expand the "Quality" section of the tab (mentioned in the previous step) and select "Interactive" Render Quality from the first drop-down menu.
5. Render the scene by pressing "F12."
6. If necessary, repeat the last two steps except this time selecting "Final" Render Quality to see what the rendered output is supposed to look like instead of the darkened scene produced by selecting "Interactive" Render Quality.

## System Setup (Environment)
- Ubuntu 20.04.3 LTS, running kernel 5.4.0-91-generic (kernel version necessary to run amdgpu-pro driver stack).
- Ryzen 5 5600x, Reference RX 6800 running amdgpu-dkms version 1:5.11.32.40502-1350682 and vulkan-amdgpu-pro version 21.40.2-1350682 from the latest amdgpu-pro driver stack.
    - Same issue occurs in Windows running AMD Adrenalin 21.10.2 drivers
- Blender 2.93.7 LTS
    - Same issue occurs in Blender 3.0.0
- GPU-only Rendering

**Comment by tedliosu** [comment]
I'll be more than happy to provide any additional info if necessary to resolve this issue.

**Comment by bsavery** [comment]
@ARozghon Can you talk to the Hybrid team and ask about emissive?

**Comment by tedliosu** [comment]
@bsavery @ARozghon Any updates?

**Comment by ARozghon** [comment]
Emissive working with the latest master, but multi-materials not support by interactive mode

![image](https://user-images.githubusercontent.com/68949117/155806573-786cf198-20f1-4dd6-b739-030cb77b08de.png)

**Comment by ARozghon** [comment]
multi-materials setup
![image](https://user-images.githubusercontent.com/68949117/155806880-5a32fa2f-cde2-4345-9884-ec06b535bf08.png)
![image](https://user-images.githubusercontent.com/68949117/155806928-0456b26e-9aea-40ac-bd8c-7f9230e7e48c.png)
and with separate by material
![image](https://user-images.githubusercontent.com/68949117/155807038-bffd906d-c345-48a9-a81c-b7cf6d6f3830.png)

**Comment by ARozghon** [comment]
sorry, not the latest master, latest develop biuld

**Comment by tedliosu** [comment]
> Emissive working with the latest master, but multi-materials not support by interactive mode

So by which RPR release will multi-materials be supported by interactive mode, @ARozghon?

**Comment by tedliosu** [comment]
@bsavery @ARozghon Hello?

**Comment by bsavery** [comment]
Hi Multi-materials is not supported in interactive mode.

**Comment by tedliosu** [comment]
Closing for now as there seems to be no further plans to address this issue.
