### ISSUE TITLE
CPU not loaded in CPU + GPU rendering mode.

### ISSUE THREAD

**Issue by naidoff** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#438]
## Issue

CPU not loaded in CPU + GPU rendering mode:

While rendering using CPU:
![image](https://user-images.githubusercontent.com/32465040/148956523-d7f0c471-7351-4ca6-b25c-a135bc90acf3.png)
Rendering time - 06:03.28

While rendering using GPU:
![image](https://user-images.githubusercontent.com/32465040/148957531-4e6ede05-614c-4cb1-97ce-8fa62b402e5f.png)
Rendering time - 2:15.26

While rendering on GPU and CPU together:
![image](https://user-images.githubusercontent.com/32465040/148957978-c768608f-4026-41df-8d12-204d7e10cd47.png)
Rendering time - 2:18.05

## Steps to Reproduce

You can check this file, but I think that it's doesn't matter.
[11.01.22.blend.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/7847136/11.01.22.blend.zip)

## System Setup (Environment)
OS version:
 System Version:	macOS 12.0.1 (21A559)
  Kernel Version:	Darwin 21.1.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	25 minutes

Hardware:
 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,1
  Processor Name:	8-Core Intel Core i9
  Processor Speed:	2,4 GHz
  Number of Processors:	1
  Total Number of Cores:	8
  L2 Cache (per Core):	256 KB
  L3 Cache:	16 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB

Blender version:
Version 3.0.0 (3.0.0 2021-12-03)

**Comment by bsavery** [comment]
Which version of the plugin do you have?  The latest should have fixed this on macOS

**Comment by naidoff** [comment]
> Which version of the plugin do you have? The latest should have fixed this on macOS

this issue described for version 3.3.15

**Comment by bsavery** [comment]
This should be fixed in 3.4.0
