### ISSUE TITLE
Geometery Nodes "Instance on Points" error

### ISSUE THREAD

**Issue by lenhone** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#441]
## Issue
RPR does not render the "Instance on Points" geometry node correctly.

## Steps to Reproduce

In the below .blend file EEVEE shows the correct geometry. When switched to RPR the incorrect geometry is shown in the rendered view.
[rpr2.blend.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/7868362/rpr2.blend.zip)

## System Setup (Environment)

OS: Linux, GPU: RX 6800, Blender: 3.0.0, Plugin: 3.3.15

## Detailed Description

As shown in the below image EEVEE correctly places the red square that is connected it the instance input at the points generated by "Instance on Points". RPR incorrectly places all geometry present at the output node (yellow cone, green cylinder, blue sphere) at the points generated by "Instance on Points".

![rpr2](https://user-images.githubusercontent.com/96949377/149463606-b37f63ea-ee33-40da-9063-b2d1219453fc.png)

**Comment by VascoPi** [comment]
Thank you, we'll look into the issue.

**Comment by lenhone** [comment]
If anyone else is having this issue while its investigated I have found a possible workaround is to add a "Realize Instances" node before the output.

**Comment by VascoPi** [comment]
Thanks. Added your workaround to the issue description.

**Comment by lenhone** [comment]
Tested with [v3.3.31](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.3.31) RPR is now the same as EEVEE. Thanks!
