### ISSUE TITLE
Decals not working

### ISSUE THREAD

**Issue by Seus981** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#449]
Every issue should include 3 things:
1.  System setup (GPU, CPU, OS version, Blender version)
2.  **Most ideally** a .blend scene to reproduce this simply.  **SCREENSHOTS OR RENDERS ARE NOT A SCENE FILE**
3.  What the expected behavior or effect is.  If possible include the error message.  

You can get more information on the error message by opening Window -> Show System Console from blender and copying that text here.  On MacOS launch Blender from the Terminal.

## Issue
I have tried to use a node setup into the RPR Uber but it didn't work ,then i baked everything to try and use that but it still didn't work even after that.

## Steps to Reproduce

[scene.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/8008476/scene.zip)

## System Setup (Environment)
Windows 10 Pro N OS Build 19043.1466
GPU RX 570 SERIES ,CPU AMD RYZEN 5 1600
Blender 3.1
GPU

**Comment by VascoPi** [comment]
Hi, thanks for the report.
Somehow textures are missed. Could you please provide textures so we investigate the issue? Because now it's "Can't Load Image".

**Comment by Seus981** [comment]
Ah yes,sorry ,my mistake for not adding them into the blend fil
[OVFX_Decal_pack_01.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/8043665/OVFX_Decal_pack_01.zip)

**Comment by VascoPi** [comment]
Curently UV maps not listed in the RPR UV Maps panel cannot be used as an input when a material is rendered.
You can find more info here https://radeon-pro.github.io/RadeonProRenderDocs/en/plugins/blender/shading_notes_and_tips.html

**Comment by Seus981** [comment]
Thank you.
