### ISSUE TITLE
Blender 3.0.1 + RPR 3.3.15  = macOS WindowServer crash

### ISSUE THREAD

**Issue by RPRrill** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#451]
Using standard BMW scene file and either standard settings or modified, RPR brings own the macOS WindowServer immediately after the Render window is opened. Reproduced on roughly 8-10 consecutive attempts with different settings and preferences set (none changed the behavior).Also multiple attempts to re-install Blender, RPR, RPR Materials to ensure was not a corrupted installation - made no difference. Same scene file worked fine in Blender 3.1 beta with Cycles. Tried Pavillion file once as well, also crashed. Crash logs are missing a lot of information but the Spin Reports seem to indicate the Window Server crash is related to CoreAnimation framework.

I can post examples if needed later but should be easily reproduced with any available file from Blender site and system setup similar to the one below.

1. Launch Blender.
2. Select RPR as the renderer. 
3. Leave defaults or change settings as needed. 
4. Select Render > Render Image from the menu. 
5. Immediate system freeze, followed by system crash a minute or two later.

Host: M1 Max MacBook Pro (64 GB RAM)
OS: 12.2
Blender: 3.0.1 (ARM build)
RPR: 3.3.15

**Comment by VascoPi** [comment]
![image](https://user-images.githubusercontent.com/42581166/153442773-966c837c-4c12-4361-baf0-e9c0af3b8f15.png)
I was trying to reproduce on
Mac mini M1 OS11.4
Blender: 3.0.1 (ARM build)
RPR: 3.3.15
Found no issue. Could you please provide log information?

**Comment by bsavery** [comment]
Can you provide log info as requested and reopen?
