### ISSUE TITLE
Color space for images is ignored on Linux

### ISSUE THREAD

**Issue by gkn11** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#453]
Issue: Color space (sRGB) is ignored for images on Linux (both CPU and GPU rendering). Same scene works correctly in the windows version.

Steps to reproduce:
Disable the environment lighting and plug the image directly into an emission shader and compare cycles and prorender. Current workaround is to manually run the image through a Gamma 2.2 node.

System Setup:
GPU: Radeon 6900XT
CPU: Ryzen 5950
OS: Arch Linux
Blender version: 3.0.1 (both Archs build and official package)
ProRender 3.3.15 Blender plugin

**Comment by gkn11** [comment]
Update: Color space work correctly when the Render Quality is set to Low, Medium or High but not on Final.

**Comment by VascoPi** [comment]
Thanks, we will investigate the issue.

**Comment by bsavery** [comment]
Probably an issue with the OCIO config path

**Comment by gkn11** [comment]
Fixed with 3.3.26. Thanks!
