### ISSUE TITLE
Can't Install RPR

### ISSUE THREAD

**Issue by hoodFX** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#461]
My System :
GPU AMD RX 570
Processor Intel i5 4570
OS Windows 10
Blender Version 3.1
![Screenshot 2022-03-10 112316](https://user-images.githubusercontent.com/89303467/157590703-7eedf1a2-4b68-4592-ac78-6b0169507ccd.jpg)

System Log:
`Read prefs: C:\Users\Tatag\AppData\Roaming\Blender Foundation\Blender\3.1\config\userpref.blend
Warning: TypeError('bpy_struct: item.attr = val: POWER_SEQUENCER_OT_speed_up_movie_strip.speed_factor expected an int type, not float')
Warning: TypeError('bpy_struct: item.attr = val: POWER_SEQUENCER_OT_speed_up_movie_strip.speed_factor expected an int type, not float')
Warning: TypeError('bpy_struct: item.attr = val: POWER_SEQUENCER_OT_speed_up_movie_strip.speed_factor expected an int type, not float')
Registered Power Sequencer with 74 modules
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\Tatag\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons\\__main__.py'
addon not loaded: 'rprblender'
cause: cannot import name 'config' from partially initialized module 'rprblender' (most likely due to a circular import) (C:\Users\Tatag\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\__init__.py)
addon not loaded: 'rprblender'
cause: cannot import name 'config' from partially initialized module 'rprblender' (most likely due to a circular import) (C:\Users\Tatag\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\__init__.py)
addon not loaded: 'rprblender'
cause: cannot import name 'config' from partially initialized module 'rprblender' (most likely due to a circular import) (C:\Users\Tatag\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\__init__.py)
addon not loaded: 'rprblender'
cause: cannot import name 'config' from partially initialized module 'rprblender' (most likely due to a circular import) (C:\Users\Tatag\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\__init__.py)
addon not loaded: 'rprblender'
cause: cannot import name 'config' from partially initialized module 'rprblender' (most likely due to a circular import) (C:\Users\Tatag\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\__init__.py)
addon not loaded: 'rprblender'
cause: cannot import name 'config' from partially initialized module 'rprblender' (most likely due to a circular import) (C:\Users\Tatag\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\__init__.py)`

**Comment by wielderWiesel** [comment]
The same issue here: 

System: Windows 10 20H2
CPU: Ryzen 7 5800X 
GPU: Radeon RX 6800 XT

Error message: 
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Joe\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File "C:\Users\Joe\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\engine\__init__.py", line 55, in <module>
    pyrpr.init(rpr_lib_dir, logging.Log(tag='core'), config.pyrpr_log_calls)
  File "C:\Users\Joe\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\pyrpr.py", line 110, in init
    import __rpr
ModuleNotFoundError: No module named '__rpr' 

Szstem-Info: 
[system-info.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/8223521/system-info.txt)

**Comment by bsavery** [comment]
Hello.  This is Blender's fault unfortunately.  With Blender 3.1 they switched to python 3.10 (late in the development cycle) which breaks any add-ons that use python C-extensions.  Frankly this is a bit annoying and adds more work for us to catch up which we haven't gotten to yet.  

See this post:  https://code.blender.org/2022/02/vfx-reference-platform/ Of Blender explaining their position.  And I encourage letting them know this is a problem.

**Comment by hoodFX** [comment]
I use RPR as an alternative when Cycles X is not supported by my vga AMD RX 570.
When there are many obstacles like this, I lose my appetite for learning Blender.
I hope there is a miraculous way out.

**Comment by bsavery** [comment]
We will add support for Blender 3.1 in a bit

**Comment by bsavery** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.3.26
