### ISSUE TITLE
Cannot be enabled in blender 3.1 and cannot be removed

### ISSUE THREAD

**Issue by jiji940** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#463]
Every issue should include 3 things:
1. 1 System setup (GPU：RX590, CPU：AMD 2700, OS version：win10 21H2, Blender3.1)
2.
![微信截图_20220314221237](https://user-images.githubusercontent.com/101574366/158190181-1913ca9e-01be-46ca-a408-5a7507ff2e4e.png)
![微信截图_20220314221338](https://user-images.githubusercontent.com/101574366/158190268-79607c37-4fa1-4162-bedd-a9530dd60c7a.png)

**Comment by bsavery** [comment]
1.  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/461 See this.  Blender broke Python add ons using c-extensions with 3.1
2. That looks like a blender error.
