### ISSUE TITLE
RGB Node Renders Fuchsia

### ISSUE THREAD

**Issue by Cantersoft** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#466]
**System Setup: AMD RX570, Intel Core i7, Windows 10, Blender 3.0.1**

As you can see in the comparison against a Cycles render result, ProRender fails to utilize the RGB node correctly, and as a result the material render completes in an unexpected manner.

**Cycles**
<img width="400" alt="Cycles- trial2" src="https://user-images.githubusercontent.com/46493366/158931904-8ca4c6ad-d3ba-4e0e-a7a9-ff99ff4e7417.png">

**Radeon ProRender**
<img width="400" alt="Radeon ProRender- trial2" src="https://user-images.githubusercontent.com/46493366/158931901-31dc7f8e-a20c-45da-a0b7-84bbbad8b91e.png">

***.blend file:** [cube.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/8300998/cube.zip)

**Comment by ARozghon** [comment]
RPR working with shader nodes only, please, add any shader, like Diffuse or Principled BSDF to see the correct result. Thank you!

**Comment by Cantersoft** [comment]
> RPR working with shader nodes only, please, add any shader, like Diffuse or Principled BSDF to see the correct result. Thank you!

Why can't RPR handle yellow > green socket connections as the native renderers do? I understand this node mapping is not technically correct, but it's inconvenient to add extra nodes in some cases, and probably not good do have functionality discrepancies.

**Comment by ARozghon** [comment]
RPR is Physical Based render and for correct results need to use one of the physical correct shaders, for other needs, please, use Toon Shader to get no Physical based results. thank you

**Comment by bsavery** [comment]
Or you can use the "Passthrough" shader to do just a color like this.

**Comment by poisenbery** [comment]
> Why can't RPR handle yellow > green socket connections as the native renderers do

Because it's not correct.

> I understand this node mapping is not technically correct

What exactly is your issue again?

**Comment by bsavery** [comment]
Just use the RPR Passthrough shader in between the RBG and output.
