### ISSUE TITLE
no named module __rpr

### ISSUE THREAD

**Issue by afhaider** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#477]
why i get this error when enable

**Comment by afhaider** [comment]
already i fresh install blender and delete any plugin have visual studio with sdk why this error happen 3.12

**Comment by ARozghon** [comment]
hi, @afhaider, https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases did you try this weekly build with Blender 3.1+? and pls, add all information and add all steps to reproduce this issue. Thank you

**Comment by afhaider** [comment]
yes i did bro @ARozghon

**Comment by afhaider** [comment]
@ARozghon  if u dont mind can u come on https://remotedesktop.google.com/support/

**Comment by afhaider** [comment]
https://drive.google.com/file/d/1sCsXiraqfqxS1vjvZtF0U2ZEe3Vj4qrj/view?usp=sharing here the bug logs

**Comment by ARozghon** [comment]
Thank you!

**Comment by afhaider** [comment]
@ARozghon  i think this issue is related to rpc 
https://grpc.io/docs/languages/python/quickstart/ should use grpco

**Comment by afhaider** [comment]
@ARozghon  can u tell me what  pip install u usiing for rpr module

**Comment by afhaider** [comment]
Traceback (most recent call last):
  File "X:\BnSModding\blender\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\engine\__init__.py", line 55, in <module>
    pyrpr.init(rpr_lib_dir, logging.Log(tag='core'), config.pyrpr_log_calls)
  File "C:\Users\haide\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\pyrpr.py", line 110, in init
    import __rpr
ModuleNotFoundError: No module named '__rpr'

**Comment by afhaider** [comment]
Weekly Development builds v3.3.26 (04/01/2022)  seems now i can enable it thnx for update bro

**Comment by ARozghon** [comment]
np, happy renders!
