### ISSUE TITLE
Open Vdb file not rendering

### ISSUE THREAD

**Issue by PARTHA313** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#489]
![image](https://user-images.githubusercontent.com/104050993/164151646-b2d28353-9a55-4b25-9e15-752bd6f6a37a.png)
![image](https://user-images.githubusercontent.com/104050993/164151671-305b3a2d-b9c3-4707-a50a-63978d725f58.png)
[OpenVdbCloud.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/8518346/OpenVdbCloud.zip)

Windows 11, Blender 3.1.2, GPU: Rx 570

I thought this will be the only way to render a heterogenous volume as of now. But this is not working too. Please help if I am making any mistake.

**Comment by bsavery** [comment]
Please try with the latest 3.4 release.

**Comment by bsavery** [comment]
And Blender 3.2
