### ISSUE TITLE
Crash on enabling ProRender plugin

### ISSUE THREAD

**Issue by mgdm** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#491]
Every issue should include 3 things:
1.  System setup (GPU, CPU, OS version, Blender version)
2.  **Most ideally** a .blend scene to reproduce this simply.  **SCREENSHOTS OR RENDERS ARE NOT A SCENE FILE**
3.  What the expected behavior or effect is.  If possible include the error message.  

You can get more information on the error message by opening Window -> Show System Console from blender and copying that text here.  On MacOS launch Blender from the Terminal.

## Issue
Enabling the plugin crashes Blender immediately.

## Steps to Reproduce

Install the plugin from the zip, and attempt to click the checkbox to activate it

## System Setup (Environment)
NixOS 21.11
Ryzen 5700G, MSI RX6600XT graphics
Blender 2.93 and 3.1

## Detailed Description
When adding the plugin, blender crashes a few seconds after clicking the checkbox to enable it. The backtrace and the other output I see is attached below. it seems to be a null pointer dereference in `adl::DeviceCL::getNDevices(adl::DeviceUtils::Config::DeviceType, adl::DeviceVendor)` in `libNorthstar64.so`.

I know this Linux version has an unusual layout but I have seen others report success with it.

[backtrace.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/8547586/backtrace.txt)
[blender.crash.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/8547587/blender.crash.txt)
[stdout.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/8547588/stdout.txt)

**Comment by TheSirC** [comment]
I get the exact same crash on NixOS unstable rev. 29a988 with Blender 2.93.5.
CPU: Xeon W-2223
GPU: Radeon Pro WX 5100

**Comment by VascoPi** [comment]
Log shows that two render engines is unregistered. But according to your system specs (RX6600XT) HybridPro should be registered.
While enabling, the addon is trying to identify which render engine more suitable for your GPU in your case it's HybridPro.

For further investigation I would like to ask you to try the latest [weekly build](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.3.36) whether issue still there.

**Comment by bsavery** [comment]
Hello we only officially support Ubuntu and Centos / Redhat it seems there might be some driver issue.
