### ISSUE TITLE
Install error – ModuleNotFoundError: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by Reggie-O** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#499]
CPU: 3.8 GHz 8-Core Intel Core i7
GPU: AMD Radeon Pro 5700 8 GB
OS: MacOS 10.15.7
Blender v: 3.1.2
AddOn v: RadeonProRenderForBlender_3.3.15_MacOS.zip
Expectation: Successfully enable addon

Attempting to install in blender 3.1. Upon checking the box to enable, this error is displayed (screenshot below for full output):

File "/Users/[user_name]/Library/Application Support/Blender/3.1/scripts/addons/rprblender/__rpr.py", line 2, in <module>
   import _cffi_backend
ModuleNotFoundError: No module named '_cffi_backend'

![ModuleNotFoundError](https://user-images.githubusercontent.com/105304158/167671668-6d4a4117-ec16-4d85-ba68-5dea8395bea8.gif)

**Comment by bsavery** [comment]
Use the 3.3.31 build https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.3.31
