### ISSUE TITLE
how do u bake node maps like normal roughness disp and albedo 

### ISSUE THREAD

**Issue by xalteropsx** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#500]
render cycle offer texture bake bake on 4uv maps on pbr images how ur tool bake i cannot understand from ur docs is too less to tell is their any video or their any guide ur render cycle can do 
something like this 
https://drive.google.com/file/d/1mx8c45_CwPPCGlMtQtvdzGy8d9DJ7-47/view?usp=sharing

**Comment by xalteropsx** [comment]
anyone is it possible to bake node maps and how

**Comment by bsavery** [comment]
We don't support baking.  You can use cycles for that.
