### ISSUE TITLE
blender 3.1 still not working with radeon pro addon 3.3.30

### ISSUE THREAD

**Issue by MaxiKitti** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#504]
ive already installed blender 3.1 and even reinstalled blender 3.1 and i installed radeon pro addon 3.3.30 so i have followed all your instructions but this same error pops up im using an rx 6700 xt qick and a i9-9900k and i have a rtx 2070

**Comment by MaxiKitti** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Max\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File "C:\Users\Max\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\engine\__init__.py", line 55, in <module>
    pyrpr.init(rpr_lib_dir, logging.Log(tag='core'), config.pyrpr_log_calls)
  File "C:\Users\Max\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\pyrpr.py", line 110, in init
    import __rpr
ModuleNotFoundError: No module named '__rpr'

**Comment by VascoPi** [comment]
If you have any previous versions of the addon installed it may cause an error.
You may check the path below to whether it contains rprblender folder.
c:\Users\YOUR_USERNAME\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\

**Comment by MaxiKitti** [comment]
oki i uninstalled the previous version but now nothing is showing up when i import the addon into blender 3.1

**Comment by VascoPi** [comment]
Type Radeon in the search field, also Community category must be enabled.

**Comment by nisimjoseph** [comment]
not working also with 3.3.33

**Comment by bsavery** [comment]
If you go to the directory where the plugin is installed:  C:\Users\Max\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender in this user's case.  What is the version number in __init__.py file?

**Comment by nisimjoseph** [comment]
I downloaded today's version 3.3.36 and it loader well now.

**Comment by VascoPi** [comment]
@MaxiKitti  any updates, about the the issue?
You may also try the latest [weekly built](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.3.36)

**Comment by MaxiKitti** [comment]
@VascoPi i had to reinstall my windows and even in windows 11 it doesnt enable and it says this when i try to enable it Traceback (most recent call last):
  File "F:\blender-3.1.2-windows-x64\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\MaxMo\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\__init__.py", line 39, in <module>
    from .engine.engine import Engine
  File "C:\Users\MaxMo\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\engine\__init__.py", line 55, in <module>
    pyrpr.init(rpr_lib_dir, logging.Log(tag='core'), config.pyrpr_log_calls)
  File "C:\Users\MaxMo\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\rprblender\pyrpr.py", line 110, in init
    import __rpr
ModuleNotFoundError: No module named '__rpr'

**Comment by MaxiKitti** [comment]
i was using 3.3.15 and the new weekly build crashed it immeditatly after enabling it

**Comment by VascoPi** [comment]
In description you mentioned two GPUs rx 6700 and  RTX 2070, currently addon doesn't support GPUs of different vendors, it can be the reason of crash. Known issue.
[Weekly build](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.3.37) should work with the GPUs apart.
3.3.15 is unsupported with Blender greater than 3.0.

**Comment by larinius** [comment]
This Pro Render never worked in Blender, every 6 month I test it with current Blender and always get errors. Only once with the first version it worked somehow, but PC freezes or crashed to blue screen, next versions never installed properly.

**Comment by bsavery** [comment]
Please reopen if you have this issue.  We can not mix GPUs right now,
