### ISSUE TITLE
Blender 2.93 crashes when I try to render or go to rendered view

### ISSUE THREAD

**Issue by Kanteer** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#507]
The title says it all, really. I have an NVIDIA 1050 GPU and a Radeon Vega 8. Are these unsupported or something?

I've tried to change the options many times, yet it just refuses to render anything. I can't really provide anything to replicate it since it seems like it's only happening to me.

**Comment by ApplicationCoding** [comment]
Can you upload a crash log? This can help find the cause of the problem.

If you don't know how, please follow the instructions:
1. Go to the installation path of Blender. If you don't know the installation path of your Blender, you can then download a daily build release here depending on your operating system: https://builder.blender.org/download/daily/
2. Once downloaded, extract the zip folder (if you're using Windows).
3. Click `blender_debug_gpu.cmd` and press a key on your keyboard once it's opened.
4. Reproduce the bug.
5. Once Blender crashes again, after reproducing the bug, blender_debug_gpu.cmd will open a new File Explorer window that shows two files: **blender_debug_output.txt** and **blender_system_info.txt**.
6. Upload those files here.

> Blender 2.93 crashes when I try to render or go to rendered view
I also greatly recommend you use the latest Blender version. You can download it here: https://www.blender.org/download/

**Comment by MKilo24** [comment]
Can you upload a crash log? This can help find the cause of the problem.

If you don't know how, please follow the instructions:
1. Go to the installation path of Blender. If you don't know the installation path of your Blender, you can then download a daily build release here depending on your operating system: https://builder.blender.org/download/daily/
2. Once downloaded, extract the zip folder (if you're using Windows).
3. Click `blender_debug_gpu.cmd` and press a key on your keyboard once it's opened.
4. Reproduce the bug.
5. Once Blender crashes again, after reproducing the bug, blender_debug_gpu.cmd will open a new File Explorer window that shows two files: **blender_debug_output.txt** and **blender_system_info.txt**.
6. Upload those files here.

> Blender 2.93 crashes when I try to render or go to rendered view
I also greatly recommend you use the latest Blender version. You can download it here: https://www.blender.org/download/

**Comment by ApplicationCoding** [comment]
Maybe a duplicate of #498.

**Comment by MKilo24** [comment]
Yes. Can you upload a crash log in #498? If the crash log you've uploaded and the crash log that @Kanteer uploads are the same, then this is a duplicate of #498.

**Comment by Kanteer** [comment]
My apologies, I forgot to give you guys the crash log. 

`building_tools updater verbose is enabled
building_tools Updater: Read in JSON settings from file
register_class(...):
Warning: 'BAGAPIE_OT_saveasset_list' does not contain '_UL_' with prefix and suffix
2022-05-19 23:02:16,274 INFO rpr.engine.init [25280]:  Core version: 2.2.10 build 0xe46836cc
2022-05-19 23:02:16,293 INFO rpr.engine.init [25280]:  RIF version: 1.7.1 build 0xfdc139ba
Switching to fully guarded memory allocator.
Blender 3.0.1
Build: 2022-01-26 01:46:57 Windows release
argv[0] = C:\Program Files (x86)\Steam\steamapps\common\Blender\\blender
argv[1] = --debug
argv[2] = --debug-gpu
argv[3] = --debug-cycles
argv[4] = --python-expr
argv[5] = import bpy; bpy.ops.wm.sysinfo(filepath=r'C:\Users\samal\AppData\Local\Temp\blender\debug_logs\blender_system_info.txt')
Read prefs: C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\3.0\config\userpref.blend
Error: Required device extension VK_KHR_deferred_host_operations is not supported.
2022-05-19 23:02:16,395 WARNING rpr.engine.init [25280]:  ('Plugin is not registered', WindowsPath('C:/Users/xxxx/AppData/Roaming/Blender Foundation/Blender/3.0/scripts/addons/rprblender/HybridPro.dll'), '')
2022-05-19 23:02:17,452 INFO rpr.material_library [25280]:  Material library located at C:\ProgramData\RadeonProRender\MaterialLibrary\Xml
I0519 23:02:17.941345 25280 device.cpp:45] CUEW initialization succeeded
I0519 23:02:17.942543 25280 device.cpp:47] Found precompiled kernels
I0519 23:02:17.987462 25280 device.cpp:64] HIPEW initialization failed: Driver version too old, requires AMD Radeon Pro 21.Q4 driver or newer
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FFB6C84B317
Module  : amdocl64.dll
Thread  : 00005f20
Writing: C:\Users\xxxx\AppData\Local\Temp\blender.crash.txt`

**Comment by Kanteer** [comment]
It says something about the addon not being registered.

**Comment by Kanteer** [comment]
I also switched to the latest 3.0 release, same results.

**Comment by Kanteer** [comment]
Oh, here's a .txt of it too.
[blender_debug_output.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/8735659/blender_debug_output.txt)
[blender_system_info.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/8735660/blender_system_info.txt)

**Comment by ARozghon** [comment]
need more information, about Blender 2.93: Is it an LTS version? if LTS - from which resource was downloaded: Blender site, Microsoft Store or Steam? thank you

**Comment by VascoPi** [comment]
MultiGPU setup of different vendors might also be the problem.
Have you tried to turn off/on each of them apart?

**Comment by ApplicationCoding** [comment]
> need more information, about Blender 2.93: Is it an LTS version? 

Blender 2.93 is an LTS version of Blender and will _get continued support and fixes until June 2023_ based [here.](https://www.blender.org/download/lts/2-93/)

About the rest of your questions, they should be answered by @Kanteer.

**Comment by bsavery** [comment]
@Kanteer which GPUs are you using?  Both?

**Comment by bsavery** [comment]
Please try using just one.

**Comment by Kanteer** [comment]
Figured it out! I was using multiple GPUs. I didn't know it until I went into my preferences. Thanks @bsavery!
