### ISSUE TITLE
Voronoi 2D and 3D differs from Cycles

### ISSUE THREAD

**Issue by lenhone** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#522]
## Issue
RPR supports Voronoi however its implementation differs from Cycles.

## Steps to Reproduce
Unzip and run blend file [rpr-voronoi3d.blend.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/8883754/rpr-voronoi3d.blend.zip) change between 2D and 3D and cycles and RPR.

## System Setup (Environment)
System setup - GPU: RX 6800, CPU: 5900X, OS: Linux, Blender Version: 3.2.0, RPR Plugin Version: [3.4.3]

## Detailed Description
As shown in the below image the RPR implementation of Voronoi is not similar to Cycles.
- When set to 2D RPR does not distribute the Voronoi cells on the X-Y 2D plane like cycles by default, instead it projects the 2D Voronoi onto faces. Please note connecting the "Generated" or "Object" output from the "Texture Coordinate" node to the vector input gives similar results to cycles with an incorrect scale.
- When set to 3D RPR does not distribute the Voronoi cells in 3D space like cycles, instead it projects the 2D Voronoi onto faces.
- This log could be related to the cause of #436.

![rpr-3d](https://user-images.githubusercontent.com/96949377/173186205-233927c0-c813-4da8-8846-34527fc3e74d.png)

**Comment by ARozghon** [comment]
for now, RPR supports only 3D/F1/Euclidean Voronoi

**Comment by ARozghon** [comment]
if you need some specific setup with Voronoi - please, use RPR procedural UV
![image](https://user-images.githubusercontent.com/68949117/173766746-fc4bf23c-dec0-4d3c-8d74-cd78b752f036.png)
thank you

**Comment by lenhone** [comment]
> for now, RPR supports only 3D/F1/Euclidean Voronoi

Unfortunately I don't think it can be called "3D" as it does not place the cells in 3D space. Looking through the RPR SDK it appears likely procedural 3D texturing the way cycles does it is not a feature of RPR. Is there any plan to add "3D procedural textures" to RPR?

> if you need some specific setup with Voronoi - please, use RPR procedural UV

Again unfortunately the "RPR procedural UV" performs poorly with most shapes. The torus in the image has distorted cells and a clear seam where Cycles does not have an issues whatever the mesh shape as the cells are placed in 3D space.
![rpr torus](https://user-images.githubusercontent.com/96949377/173835206-08e8ba97-2aac-4faa-b215-6e466f99f958.png)

**Comment by lenhone** [comment]
At this point I think the simplest solution is for me to close my logs #440, #436 and #522. RPR is not deigned to be compatible with .blend files developed with Cycles.
