### ISSUE TITLE
crash on blender 3.2 radeon r9 380x

### ISSUE THREAD

**Issue by helpforsoftware** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#530]
when i install addon default settings,press render on newly created blender project(only cube on the scene) (or in viewport render button)blender crashes. no output render.
it is simple cube
using windows 11,intel i5,blender 3.2, addon version 3.4.5

**Comment by VascoPi** [comment]
Could you please send a log of crash? You can find instructions [here](https://docs.blender.org/manual/en/dev/troubleshooting/crash.html)
Do have GPU within your PC?

**Comment by helpforsoftware** [comment]
no my device is supported: https://www.amd.com/en/technologies/radeon-prorender-blender  

Compatible Windows® and Linux® AMD Graphics Hardware:
AMD Radeon™ Pro Duo (“Fiji”) graphics, Radeon™ R9 Fury series graphics cards, Radeon™ R9 Nano graphics, Radeon™ R9 300 series graphics cards, Radeon™ R9 290X graphics, Radeon™ R9 290 graphics, Radeon™ R9 285 graphics, Radeon™ R9 280X graphics, Radeon™ R9 280 graphics

**Comment by helpforsoftware** [comment]
sending crash report .startup sscene. first activated plugin. selected prorender in render properties then pressed render image.
render screen opened.but closed after a few seconds
[blender.crash.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/9023830/blender.crash.txt)
.

**Comment by helpforsoftware** [comment]
![optionsblender](https://user-images.githubusercontent.com/37977590/176791582-67fe205f-b777-4c26-87df-440573845dd6.jpg)

**Comment by helpforsoftware** [comment]
mydive could be 280x maybe, dont remember:=)

**Comment by bsavery** [comment]
The R9 card is no longer supported by the RPR sdk.

**Comment by helpforsoftware** [comment]
> The R9 card is no longer supported by the RPR sdk.

no it is supported. this is in web site.
https://www.amd.com/en/technologies/radeon-prorender-blender
![Screenshot 2022-07-04 091000](https://user-images.githubusercontent.com/37977590/177111490-e58e86d4-7e19-4afb-80c8-1b030c88f347.jpg)

**Comment by helpforsoftware** [comment]
please reopen this issue .

**Comment by bsavery** [comment]
That website is outdated. I'll see that it gets changed.  Regardless the SDK no longer supports that card.
