### ISSUE TITLE
Missing Emission of RPR Uber

### ISSUE THREAD

**Issue by zincan-images** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#531]
Every issue should include 3 things:
1.  R9 nano(Driver 27.20.14540.4003 [Or 
20.45.40.04-210405a-366334C-RadeonProEnterprise]), Xeon E5 -2670 v1, Windows 10 Pro 21H2 (OS Build 19044.1766), Blender 3.2.0
2. Screenshots

![Screenshot 2022-06-30 071956](https://user-images.githubusercontent.com/98735326/176555673-d4136847-2917-4d7a-ab68-f68302968f38.png)

![Screenshot 2022-06-30 072613](https://user-images.githubusercontent.com/98735326/176556167-438066cf-2d20-400a-8cbb-3bad966fbce2.png)

3.  Launch Blender Application with message  

Read prefs: C:\Users\_My-User-name_\AppData\Roaming\Blender Foundation\Blender\3.2\config\userpref.blend
2022-06-30 07:14:06,819 INFO rpr.engine.init [7428]:  Core version: 2.2.13 build 0xbe24f121
2022-06-30 07:14:06,838 INFO rpr.engine.init [7428]:  RIF version: 1.7.1 build 0xfdc139ba
Error: Required device extension VK_KHR_deferred_host_operations is not supported.
2022-06-30 07:14:06,943 WARNING rpr.engine.init [7428]:  ('Plugin is not registered', WindowsPath('C:/Users/My-User-name/AppData/Roaming/Blender Foundation/Blender/3.2/scripts/addons/rprblender/HybridPro.dll'), '')

## Issue
Missing Emission of RPR Uber

## Steps to Reproduce
I download sample file from [RPR Manual website](https://github.com/Radeon-Pro/Doc-Assets/raw/master/scenes/blender/fsr_modes.blend)
Normally, I open this file. and then get this issue.

## System Setup (Environment)
Windows 10 Pro 21H2 (OS Build 19044.1766)
R9 nano(Driver 27.20.14540.4003 [Or 
20.45.40.04-210405a-366334C-RadeonProEnterprise]), Xeon E5 -2670 v1
Blender 3.2.0
Radeon ProRender for Blender 3.4.0 (core 2.2.13, RIF 1.7.1)
GPU Rendering only.

## Detailed Description
I try change to Blender emission node, Emission correct worked.

**Comment by VascoPi** [comment]
Hi, the thing is the release version of the addon has no backward compatibility for the older scenes that uses Uber Shader with emission option. The fastest way to fix it is to recreate Uber Shaders for particular material where emission is used, and others would be good as well.

**Comment by ARozghon** [comment]
thank you for your request will ask to update scene for download

**Comment by zincan-images** [comment]
I got a clearly result!!

**_Thanks for your work!!_**

![Screenshot 2022-07-01 064036](https://user-images.githubusercontent.com/98735326/176784540-9ecd207a-977f-48b2-81de-1024b18e451f.png)
