### ISSUE TITLE
Support for Blender 3.3 Soon?

### ISSUE THREAD

**Issue by tedliosu** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#542]
Sorry if I'm being bothersome, just that it's almost been a month since blender 3.3 was released and I'm just wondering if support for 3.3 will get officially added soon; this addon may not do everything i wish it can do but it's still a great addon imo :smile:

**Comment by ARozghon** [comment]
now Blender RPR working with Blender 3.3, but has not supported a new Hair system yet.

**Comment by tedliosu** [comment]
> now Blender RPR working with Blender 3.3, but has not supported a new Hair system yet.


Alright I think I'll wait until the new hair system has been added to download the plugin; when do you think **official** support for blender 3.3 will be added in subsequent releases; i.e basically when will the next version or subsequent versions of the addon be released?

**Comment by ARozghon** [comment]
(https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.4.10) enjoy RPR and a new hair system from Blender 3.3. For now, supported only procedural UVs, if you plan to add textures to hair objects. Thank you

**Comment by tedliosu** [comment]
Official support for Blender 3.3 has been released [here](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.5.0); closing this issue as solved.
