### ISSUE TITLE
Specific "fog" scene crashes blender 3.4.0 when rendering with RX6900XT GPU on RedHat Linux 9.1

### ISSUE THREAD

**Issue by joni999** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#567]
## System setup (GPU, CPU, OS version, Blender version)
GPU: RX 6900 XT
CPU: Ryzen 7 5800X
OS version: RedHat Enterprise Linux 9.1 
Blender version: 3.4.0 (downloaded from blender.org)
RadeonProRender Version: 3.5.0

```
[joni@localhost tmp]$ uname -a
Linux localhost.localdomain 5.14.0-162.6.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Sep 30 07:36:03 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```
I'm using the official AMD driver downloaded from the website and installed with "amdgpu-install"

```
[joni@localhost tmp]$ sudo dnf list --installed | grep -i amd
amdgpu-core.noarch                               1:5.4.50401-1518338.el9          @amdgpu                          
amdgpu-dkms.noarch                               1:5.18.13.50401-1520974.el9      @amdgpu                          
amdgpu-dkms-firmware.noarch                      1:5.18.13.50401-1520974.el9      @amdgpu                          
amdgpu-install.noarch                            5.4.50401-1518338.el9            @@commandline                    
amdgpu-lib.x86_64                                1:5.4.50401-1518338.el9          @amdgpu                          
dkms.noarch                                      3.0.3-1.el9                      @amdgpu                          
hip-runtime-amd.x86_64                           5.4.22802.50401-84.el9           @rocm                            
libdrm-amdgpu.x86_64                             1:2.4.113.50401-1518338.el9      @amdgpu                          
libdrm-amdgpu-common.noarch                      1.0.0.50401-1518338.el9          @amdgpu                          
llvm-amdgpu-libs.x86_64                          1:15.0.50401-1518338.el9         @amdgpu                          
mesa-amdgpu-dri-drivers.x86_64                   1:22.3.0.50401-1518338.el9       @amdgpu                          
mesa-amdgpu-filesystem.x86_64                    1:22.3.0.50401-1518338.el9       @amdgpu                          
mesa-amdgpu-libEGL.x86_64                        1:22.3.0.50401-1518338.el9       @amdgpu                          
mesa-amdgpu-libGL.x86_64                         1:22.3.0.50401-1518338.el9       @amdgpu                          
mesa-amdgpu-libgbm.x86_64                        1:22.3.0.50401-1518338.el9       @amdgpu                          
mesa-amdgpu-libglapi.x86_64                      1:22.3.0.50401-1518338.el9       @amdgpu                          
mesa-amdgpu-libxatracker.x86_64                  1:22.3.0.50401-1518338.el9       @amdgpu                          
mesa-amdgpu-vdpau-drivers.x86_64                 1:22.3.0.50401-1518338.el9       @amdgpu                          
teamd.x86_64                                     1.31-14.el9                      @rhel-9-for-x86_64-baseos-rpms   
xorg-x11-amdgpu-drv-amdgpu.x86_64                1:24.1.0-1518338.el9             @amdgpu                          

```

## .blend file to reproduce:
 (I had to zip it, because .blend files are not attachable here):
[blendfile.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/10254745/blendfile.zip)

## What the expected behavior or effect is:

Blender successfully renders the image so it can be viewed.

## What actually happens:

Blender closes without an error when you try to render the scene in the .blend file. There is also no crash report at /tmp/ 

## Steps to Reproduce:

1. Open the attached .blend file
2. Press Render Image while having RadeonProRender and the GPU (RX 6900 XT) selected and it should crash after a few seconds.

## Other relevant info

- The crash only happens when using GPU rendering. With CPU rendering it does not crash. 
- In the attached scene I'm trying to create a foggy street.
- When I tried moving the camera outside of the Cube object(which I use to create the fog) the render was successful and blender didn't crash on GPU rendering.

Footnote:

Thank you for maintaining this software!
Since rendering with Cycles doesn't work at all with RDNA2 and RDNA3 this add-on is the only way to use blender on an AMD-GPU right now.

**Comment by ARozghon** [comment]
hi, looks like this issue was fixed with 3.5.2, please, try this build on your system https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.5.2
was checked this scene with 6800 XT with the drivers 22.5.1 and 22.11.2, Blender 3.4.0, and 3.9 LTS in all cases - working as expected without errors.
Will check with Ubuntu today
