### ISSUE TITLE
any updates on uv map baking texture :( 

### ISSUE THREAD

**Issue by xalteropsx** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#570]
can u plz provide any tutorial where multiple uv map bakes i really love to see how do we do in amd radeon i wonder i saw some notes in recent changes that it has supporting on UV Lookup nodes

**Comment by bsavery** [comment]
No sorry

**Comment by xalteropsx** [comment]
> No sorry

i want to develop game in unreal engine 5 i hope u can do something about baking system i really waiting for so long

**Comment by bnagirniak** [comment]
Thanks for report, we'll investigate what we can do with this issue.

**Comment by xalteropsx** [comment]
> Thanks for report, we'll investigate what we can do with this issue.
nvidia has this blender omniverse which bake all texture in 1min less 
https://github.com/NVIDIA-Omniverse/Blender-Addon-OmniPanel
![image](https://user-images.githubusercontent.com/103671642/217971044-acb9f402-099f-4c76-8b3d-40098f8eec2f.png)

**Comment by bsavery** [comment]
Hi @xalteropsx Can you describe what exactly you want here?  It's very unclear.  

RPR has the ability to bake textures to a node, as that addon you pointed to does about the same thing.  It looks like they have some ability to create new UV layers.  

For the record that one you're pointing to just bakes through cycles though?  If that works why not just use that?

**Comment by bsavery** [comment]
(Cycles on AMD will use the HIP backend to bake.)

**Comment by xalteropsx** [comment]
rx 580 amd dont support HIP in blender i plan to buy after 2-4month to new amd gpu but i want to use two gpu to speed up

the problem with RPR has the ability to bake textures to a node, it bake only 1 single object but their are multiple object inside 1 uv map

**Comment by xalteropsx** [comment]
![image](https://user-images.githubusercontent.com/103671642/218247704-0814abfe-83ce-4df8-bbfa-735b3cf96465.png)
this is how two object go in 1 uv map layer that the problem with rpr it cant do this part

**Comment by xalteropsx** [comment]
that why the cycle are been created to make them bake all together in single click 
which come in form of node
image = get_image_from_tag("displacement", obj name)

**Comment by xalteropsx** [comment]
@bnagirniak 
![image](https://user-images.githubusercontent.com/103671642/218350066-be3f5778-6915-4652-b821-2d257867308a.png)
plz help

**Comment by xalteropsx** [comment]
![image](https://user-images.githubusercontent.com/103671642/218355519-25e87a65-1222-4a32-a5a3-1011bb865065.png)

**Comment by bsavery** [comment]
The baking in RPR is just using Cycles under the hood to do the baking, not with RPR itself on the GPU.

**Comment by xalteropsx** [comment]
> The baking in RPR is just using Cycles under the hood to do the baking, not with RPR itself on the GPU.

but the rpr node bake consume my gpu and bake it in nano second 4k texture like 1-2sec

**Comment by bsavery** [comment]
My guess is the bake is happening fast due to the settings that are used for it.  If you take a look at this code: 
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/blob/cd293f9ce5f160e199db51ffa5c824a345f0d5f9/src/rprblender/operators/nodes.py#L72

This is where the baking function happens.  We switch to Cycles render to perform the bake, and create an emit node, hook up the output of the node, etc.  Then switches back to RPR after.

I think I understand what you want though.  Can you upload that scene you showed above so I can work off that?  It's not a huge priority on our side but we can help perhaps

**Comment by xalteropsx** [comment]
@bsavery  sorry for late reply got high fever 
![xxe](https://user-images.githubusercontent.com/103671642/220107108-bbaf8927-5049-478f-b884-35a24bb13c38.png)
here axe and blade 
i dont know why rpr only showing on axe not on blade but i think it show difference i set the sampling from 200 to 10 in cycle still it cant beat rpr baking speed 
https://drive.google.com/file/d/1kepWqD7mwpw5Ujr_wAEYffl9ZM1sB0Pv/view?usp=sharing

**Comment by bsavery** [comment]
So can you also give the example of what this should look like AFTER baking?  Thanks?

**Comment by xalteropsx** [comment]
@bsavery  https://youtu.be/HoU-CX1ShOk  i made a small video 1st bake on cycle and second bake on rpr  
this is the file for this video https://drive.google.com/file/d/1qbzM--hRNhMeRPQU9iGBdCqNxo9rFYra/view?usp=sharing

**Comment by xalteropsx** [comment]
bought rx 7900 xtx ^>^
