### ISSUE TITLE
Blender crashes after loading up viewport rendering.

### ISSUE THREAD

**Issue by jafwefjauwhf** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#575]
My blender crashes after loading viewport rendering.
## Issue
It crashes.
## Steps to Reproduce
Load up a default file and render.

## System Setup (Environment)
Windows 11 Home Insider Preview Build 25281.rs_prerelease.230113-1248
AMD Radeon RX 5600M Series
Blender 3.4.1
GPU Rendering

## Detailed Description
Here is the error I got: raise CoreError(status, f.__name__, argv, module_name)
pyrpr.CoreError: RIF call ContextExecuteCommandQueue(<pyrprimagefilters.Context object at 0x000001A0DFE2AA40>, <pyrprimagefilters.CommandQueue object at 0x000001A0DFE2ACB0>, <cdata 'void *' NULL>, <cdata 'void *' NULL>, <cdata 'void *' NULL>) returned error code <-21> with error message: ''

**Comment by ARozghon** [comment]
Hi, I need additional information about the steps to reproduce this issue. also, that reproduces with which render mode: Full, interactive, low/med/high?
thank you

**Comment by jafwefjauwhf** [comment]
It happens on all, and its only crashing in viewport rendering. Normal rendering seems fine

**Comment by ARozghon** [comment]
and another question: did you have the same issue with Blender 3.3 LTS? because now we do not have full Blender 3.4 support, and could be issued with materials or other small stuff
thank you

**Comment by jafwefjauwhf** [comment]
ill try it

**Comment by jafwefjauwhf** [comment]
Thank you! Must have been the problem.
