### ISSUE TITLE
MacOS crash on Radeon ProRender 3.6.2 plugin disable

### ISSUE THREAD

**Issue by jeinselenVF** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#627]
## Issue
Blender experiences a fatal crash when attempting to disable the Radeon ProRender add-on.

## Steps to Reproduce
- Install Radeon ProRender
- Enable the add-on
- Disable the add-on
- Instant crash

## System Setup
- 2019 MacBook Pro 16"
- 2.4Ghz Intel Core i9
- AMD Radeon Pro 5600M 6GB
- 64GB ram
- MacOS Ventura 13.3.1(a)
- Blender 3.4.1

## Detailed Description
No project setup needed; this crash occurs regardless of selected render engine in the mostly-empty default scene. See attached crash log for details.

[Blender341-CrashLog.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/11576940/Blender341-CrashLog.txt)

**Comment by bsavery** [comment]
Closing this to track on : https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/626
