### ISSUE TITLE
RPR 2.4.50 WINDOWS - Low, Medium and High Modes not rendering in viewport and errors

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#63]
Hi All,

I'm looking at the weekly build 2.4.50 for Windows. These render settings return an error. Just opened a default cube session and this is what it returned:

ERROR | RPR call LightSetGroup(<pyrpr.PointLight object at 0x00000192B69BF648>, 0) returned error code ,-23. with error message

After some experimenting with some things, this is what I found.

1: After I deleted the point light, Low and Medium render samples but the viewport jumps around and flickers like crazy. 
2: Spotlight returns similar error except replaces error code with SpotLight as object reference.
3: Adding back in a point light brings back error.
4: Area light will allow for render without error in Medium and Low but has same issue as #1
5: High setting will work without screen flickering issues sometimes. 
6: Turning on two GPUs on "Medium" Setting returns following error:
ERROR | RPR call ContextRender(,pyhybrid.Context object at 0x00000192B6AD6D48.) returned error code ,-18. with error message
7: Turning on two GPUS on High settings returns black render in viewport.

CPU: AMD 3960x
GPU: 2X Radeon VII
RAM: 64GB
SSD: 1TB Aurous M.2 NVME

**Comment by bsavery** [comment]
"ERROR | RPR call LightSetGroup(<pyrpr.PointLight object at 0x00000192B69BF648>, 0) returned error code ,-23. with error message"

What view quality setting are you using

**Comment by djtutorials** [comment]
Low, Medium and High

**Comment by ardraeiss** [comment]
In progress
