### ISSUE TITLE
RPR 2.0 Renderer Feedback Query RPR v 2.4.50 Windows

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#64]
Hi all-

I am wondering how I should report issues with the 2.0 Renderer. I know it is in BETA and in development, but I am finding it practically unusable. Are there any tips/tricks to get it working in a way that will render something? Maybe something I am not aware of? I want to provide feedback that is constructive but with the current development build I am using, it just seems simply overall broken and unstable, incredibly slow compared to 1.0 and will not render certain shader settings like volumetrics, at times some image maps, and film->transparent background.

**Comment by bsavery** [comment]
I would post here with scenes of the issues.  Also we'll have a more official build wednesday.

**Comment by djtutorials** [comment]
Thank you @bsavery!

By scenes- do you mean blender files? I am testing basically with the default cube scene.

**Comment by bsavery** [comment]
@djtutorials you mention using volumetrics, image maps, transparent backgrounds.  I'm sure the default cube scene does not have those.  

We do test with of course the default cube scene and other general test scenes like the BMW, etc.  

Here's what I'd suggest adding to a bug report:
1.  HW setup, and what driver you have
2.  What version you have (mentioned here in title)
3.  Attach a scene and describe the issue.  I would say that statements like "practically unusable" is not objectively helpful!

As a quick tip in that build you downloaded, set the "samples per view update" setting to 32 to use RPR 2.0.  We have a forthcoming change that deals with that.

**Comment by bsavery** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/commit/8dfc06b3e41213240fac46233d32e9ce8fcddfa8#diff-d99797e5b435aeab47c3514ce5fb793eR86

**Comment by djtutorials** [comment]
@bsavery Understood- thanks.

I was generalizing a bit since I was not sure what the best way was to handle reporting. For the volumetric I just checked on the environment fog setting and for the image texture, that was specific to a different test. My apologies for causing issues.

Thanks for the tips- will work on communication. This was more so an ask on whether I should be reporting the problems I am having on 2.0 and if there was something like you recommended on the 32 samples issue that might account for it.

**Comment by bsavery** [comment]
Thanks RPR 2.0 is far from finished, but the initial results we see are very promising.  Please do file the issue you find though.

**Comment by djtutorials** [comment]
@bsavery -

I wanted to also address my comment about it being practically unusable- in no way did I mean to belittle your/the team's efforts or be overly critical. I am just having difficulty with testing it as the interface becomes extremely sluggish and sometimes crashes the program or the renders seem to hang. I will try and report what I am seeing in other posts in the way you described.

-DJ

**Comment by bsavery** [comment]
Not at all.  I just like objective comments ;) I can't simply fix "practically unusable"

**Comment by bsavery** [comment]
Hi @djtutorials I'm going to close this, we have a bunch of stuff working much better in RPR 2.0 if you feel it warrants reopening in a few weeks please do so.
