### ISSUE TITLE
Radeon ProRender 3.6.0 crashing Blender 3.6.1 (MacOS Ventura 13.5 / intel)

### ISSUE THREAD

**Issue by sbgraphic** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#641]
### System setup
iMacPro / Radeon Pro Vega 64X 16 Go / Ventura 13.5 / Blender LTS 3.6.1 2023-07-18

### Issues

Make Blender crash in various ways:
– just after ticking the box when installing…
– after restart, instant crash when selecting/activating pro render in the viewport (simple default cube scene) - GPU rendering or CPU or Both…
– Instant crash when trying to disable the extension as well… (had to do it manually)
– impossible to do anything…

### Error message from terminal:

`/Applications/Blender_LTS/Blender_LTS_36x/Blender.app/Contents/MacOS/Blender
Read prefs: "/Users/sbgraphic/Library/Application Support/Blender/3.6/config/userpref.blend"
Device with name AMD Radeon Pro Vega 64X supports metal minimum requirements
METAL API - DETECTED GPU: AMD Radeon Pro Vega 64X
Start generating Libraries...
Generated Icons in 0.005 seconds.
Library Size: 48
WARN (bgl): source/blender/python/generic/bgl.c:2662 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module. In Blender 4.0 'bgl' will be removed.
2023-07-26 14:13:21,533 INFO rpr.engine.init [140704277427968]:  Core version: 3.1.1 build 0x5c28d0d6
2023-07-26 14:13:21,539 INFO rpr.engine.init [140704277427968]:  RIF version: 1.7.1 build 0xfdc139ba
2023-07-26 14:13:21,754 INFO rpr.material_library [140704277427968]:  Material library located at /Users/Shared/RadeonProRender/MaterialLibrary/2.0.0/Xml
WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glGenTextures' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glBindTexture' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glTexParameteri' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glTexParameteri' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glTexParameteri' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glTexParameteri' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glTexImage2D' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glBindTexture' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
Writing: /var/folders/n3/q2hkgrf17hn_r9t_bp2hpjh40000gn/T/blender.crash.txt
zsh: segmentation fault  /Applications/Blender_LTS/Blender_LTS_36x/Blender.app/Contents/MacOS/Blender`

### Report
[blender.crash.txt](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/12172358/blender.crash.txt)

**Comment by Muscobaldi** [comment]
Same problems (and config.) here, dozens of crashes echoing above. Numerous cleansings of Blender from system with reinstalls did anything to solve issues. Have abandoned ProRender for now.

**Comment by bsavery** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/blob/master/Changelog.md#known-issues

Did you see this in the release notes?

**Comment by sbgraphic** [comment]
> https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/blob/master/Changelog.md#known-issues
> 
> Did you see this in the release notes?

Nope I have not, thank you. What does this "GPU backend" mean/do ? As I'am trying to see how Metal "perform" here 
Does it influence the viewport render speed somehow ?

After changing this setting, I can load the extension and it seems to work fine, except that it appears slower than before (maybe ?). Anyway Blender 3.6.4 still crash  when closing any file and then I still cannot disable the extension with usual user preferences...

I'll wait the next compatible update for 3.6x to test it again...
