### ISSUE TITLE
Default open blender file Crashes 

### ISSUE THREAD

**Issue by Snoiteandthesv3ndwarves** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#643]
Every issue should include 3 things:
1.  System setup (GPU, CPU, OS version, Blender version)
2.  **Most ideally** a .blend scene to reproduce this simply.  **SCREENSHOTS OR RENDERS ARE NOT A SCENE FILE**
3.  What the expected behavior or effect is.  If possible include the error message.  

You can get more information on the error message by opening Window -> Show System Console from blender and copying that text here.  On MacOS launch Blender from the Terminal.

## Issue
<Cannot enable disable or remove Cannot use Factory Blender settings. Each results in Blender Crashing.>

## System Setup (Environment)
<13.4.1>

## Detailed Description
<Cannot enable disable or remove Cannot use Factory Blender settings. All results in Blender Crashing.

**Comment by bsavery** [comment]
Closing, no details about hardware, OS, etc provided.
