### ISSUE TITLE
Blender Crashes When Trying to Render Scene Using Radeon ProRender

### ISSUE THREAD

**Issue by Dhaivya** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#652]
System:
1.  AMD Radeon RX 580 8GB
2.  AMD Adrenaline 23.8.2
3.  Radeon ProRender 3.6.0 for Blender
4.  Intel Core i5 6500
5.  Windows 10 22H2
6.  Blender 3.6.0

Expected behaviour:
1. Scene renders.

Actual behaviour:
1. Blender crashes.

Steps to reproduce:
1. Switch render engine to Radeon ProRender
7. Render scene (not viewport render)

Scene file:
1. Default scene/Any scene

Was told to try using ProRender since they removed support for OpenCL. Installed the addon, switched engine to ProRender and rendered default scene to test it and Blender crashed. Tried the same thing again and Blender keeps on crashing. Strange thing is, the scene renders fine in viewport shading, only crashes when trying to final render (F12)

**Comment by bsavery** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/630#issuecomment-1590194039 here is the solution
