### ISSUE TITLE
Unable to activate RPR in blender gets Error

### ISSUE THREAD

**Issue by DaddyPoppe** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#653]
Hello,
My GPU is a Radeon RX580 8 GB
My CPU is Ryzen 5950x
OS is Winbdows 11 Pro, version 22H2
Blender is Version 3.6.2

Every time I try to install/Enable Radeon Pro Render, and even the 3.6.7 version does not work. I always get an error message when trying to enable RPR.

Is it because my GPU is obsolete? 
Can RPR use CPU only? if the GPU isn't supported
Can anyone from the uploaded image see the cause of error!?
![RRPro 3 6 7](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/assets/112268540/b4251e88-be7b-4183-a4e6-ee4d6852869e)

**Comment by bsavery** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/630#issuecomment-1590194039

**Comment by bsavery** [comment]
See this for solution.  You have to use OpenCL mode.

**Comment by DaddyPoppe** [comment]
Hello,
I'm unable to select RPR as render engine, because the Plugin won't be enabled, every time I tick the box the error shows. So I cannot choose OpenCL
Cycles eve says My GPU isn't compatible, it has to be Vega or RDNA architecture. (Under System/Cycles Render Devices and HIP
My RX580 is the old Ellesmere XT architecture, so I guess my GPU is to old.

**Comment by bsavery** [comment]
Cycles and EEVEE settings are not related to RPR.
