### ISSUE TITLE
How to use 4.0 patch?

### ISSUE THREAD

**Issue by PsykologyZA** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#666]
hey guys hope the holidays were good,
Im new to using github and ive downloaded the zip for the 4.0 patch but what do i do from here?

I

**Comment by PsykologyZA** [comment]
Figured it out, i think, just copied the source - rpr folder contents into my addons install directory and overwrote the files

**Comment by PsykologyZA** [comment]
Reopening, thought id come right but i hadnt.

**Comment by CrJolin0783** [comment]
I'm also waiting for the new version to be released

**Comment by bsavery** [comment]
We're transitioning build system so I don't have any to upload at the moment.

You can build yourself,  just follow the instruction https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon in the readme

**Comment by PsykologyZA** [comment]
shweet i'll give it a shot
