### ISSUE TITLE
Triplanar doesn't work

### ISSUE THREAD

**Issue by framkant** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#7]
Have logged this many times over the years so I guess you know this yourselves by now. I Put it up here since it was asked for on discord.

Best would be native support of the cycles/eevee BOX sampling on the image texture node projection drop down. Next best thing would be if the RPR projectionUV node to work instead of producing what it does right now. (n.b it has never worked )
<img width="866" alt="image" src="https://user-images.githubusercontent.com/480029/81982285-dd626b00-9631-11ea-94ff-1d5badf60aff.png">
If for some reason the issue is not clear per earlier reports in other reporting systems that has been used over the years, please ask away :)

**Comment by bsavery** [comment]
Thanks for logging it (again).  We want to be able to track everything in one place so appreciate you moving it.  

And yes we're aware!

**Comment by framkant** [comment]
Btw, it would be many times more useful if the native BOX projection in the image node worked since it would then be possible to do some basic lookdev in EEVEE and then switch to RPR once that is done and one is trying to get a final shot. The RPR projection UV node just makes things more cumbersome but it would be a lot better than nothing.

**Comment by framkant** [comment]
This is a very useful example of a good implementation: https://www.3delight.com/documentation/display/3DfH/Triplanar
Maybe it doesn't fit the RPR workflow, but from a user perspective this is super handy. As I am sure you know, concept art and anything that uses procedurally generated content or landscapes/natural formations would greatly benefit from having a solid triplanaar implementation.

**Comment by bsavery** [comment]
Yep.  Part of the issue we're struggling with is that currently GPU on Mac these projections don't work at all.  At one point you posted a node setup with math nodes to try and do this, can you attach that scene if you still have it?

**Comment by framkant** [comment]
> Yep. Part of the issue we're struggling with is that currently GPU on Mac these projections don't work at all. At one point you posted a node setup with math nodes to try and do this, can you attach that scene if you still have it?

I sent a simple example implementation using RPR math nodes to you on discord earlier this year so I think it might be still there. It is very basic though and seems to crash RPR/Blender so maybe mostly useful as a "conversation" thing? If you cannot find it I can send you another copy if you want to.

**Comment by iaian7** [comment]
Triplanar is still unusable in version 3.0.1.
![Triplanar](https://user-images.githubusercontent.com/142759/99825673-54b71100-2b25-11eb-8431-57a3797c86e8.png)

**Comment by bsavery** [comment]
Closed!  See latest release.
