### ISSUE TITLE
RPR call error - I cannot render or view my scene in the viewport in any scene

### ISSUE THREAD

**Issue by t81959362** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#703]
![Screenshot 2024-12-17 212252](https://github.com/user-attachments/assets/7a2f4360-ac3c-4bf0-b241-f6e9743fcb86)
Every issue should include 3 things:
1.  System setup (GPU, CPU, OS version, Blender version)
2.  **Most ideally** a .blend scene to reproduce this simply.  **SCREENSHOTS OR RENDERS ARE NOT A SCENE FILE**
3.  What the expected behavior or effect is.  If possible include the error message.  

You can get more information on the error message by opening Window -> Show System Console from blender and copying that text here.  On MacOS launch Blender from the Terminal.

**Comment by takahiroharada** [comment]
Try with "quality > quality > accurate". I think we need to remove the fast mode.

**Comment by t81959362** [comment]
It also seems far more system resource heavy than even Cycles pathtracing? Surely this shouldn't be the case given it is optimised for AMD Hardware?

**Comment by takahiroharada** [comment]
It depends on the config. Some config tries to use resources aggressively.

**Comment by t81959362** [comment]
Sorry but Radeon ProRender is absolutely unusable. It is causing Blender to crash, run incredibly slowly compared to Cycles on a fresh Blender 4.3 install. Even Ultra Performance upscaling with Denoise on it makes it run like I have a 10 year old laptop compared to Cycles using the same GPU that loads my scene instantly and I can work in real time.
