### ISSUE TITLE
RPR 2.5.1 Renderer 2.0 Film -> Transparent Background Not Working

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#72]
Hi All, 

I noticed that in hte 2.0 renderer the background transparency setting is not working (Render Properties->Film->Transparent Background).

Steps to reproduce:
1: Go to Render Properties->Film->Transparent Background and select the Transparent Background check box.
2: Check between 1.0 and 2.0 renderer.

Issue is seen on both CPU and GPU render devices.

Software and Computer info:
Windows 10
Newest Pro AMD GPU Drivers
Blender 2.83
Prorender v 2.5.1
AMD Threadripper 3960x
AMD Radeon VII (x2)
1TB Aurous M.2 NVME SSD
64GB RAM
ASRock Creator TRX40

**Comment by bsavery** [comment]
@ardraeiss  is this addressed?

**Comment by ardraeiss** [comment]
Yes, it's in progress
