### ISSUE TITLE
RPR 2.5.1 Low and Medium render flickering issue

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#73]
Hi all,

I noticed that on the new version of Prorender (2.5.1) that when looking through the low and medium render settings, there is a lot of flickering as if every sample is jumping around all over. I have placed a screen shot in this submission. I have noticed that this is observed on both my GPUs when switching between render devices.

Software and Computer info:
Windows 10
Newest Pro AMD GPU Drivers
Blender 2.83
Prorender v 2.5.1
AMD Threadripper 3960x
AMD Radeon VII (x2)
1TB Aurous M.2 NVME SSD
64GB RAM
ASRock Creator TRX40

![image](https://user-images.githubusercontent.com/65964807/90822554-7d8ef680-e2e9-11ea-80d3-9b4ed7d91884.png)
![image](https://user-images.githubusercontent.com/65964807/90822697-afa05880-e2e9-11ea-9eba-3995c43a3cb0.png)

**Comment by bnagirniak** [comment]
Such bug was introduced to hybrid team 3 weeks ago. Discussing with them.

**Comment by bnagirniak** [comment]
This bug was fixed earlier, closing it.
