### ISSUE TITLE
Displacement & Bump are not working corectly 

### ISSUE THREAD

**Issue by kintuX** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#74]
specs:

**S/W:** Win10, Blender 2.83.4, RPR for Blender 2.5.1
**H/W:** **CPU** AMD TR 1950WX, 64GB RAM // **GPU** NVidia Quadro M5000 8GB & GTX 1070 8GB, (Driver v451.77) 

**Cycles Displacement (reference)**
![DisplaceBumpBug_Cycles-displace](https://user-images.githubusercontent.com/61623470/90850127-2896c300-e371-11ea-8619-bb81dd4545f1.jpg)

RPR 2 (Beta) Displacement
![DisplaceBumpBug_RPR-2Beta-displace](https://user-images.githubusercontent.com/61623470/90850288-8aefc380-e371-11ea-9b02-a2d327a12b62.jpg)

RPR Full Displacement
![DisplaceBumpBug_RPR-Full-displace](https://user-images.githubusercontent.com/61623470/90850292-90e5a480-e371-11ea-9455-c4cc6aa2c3bc.jpg)

**Cycles Bump (reference)**
![DisplaceBumpBug_Cycles-bump](https://user-images.githubusercontent.com/61623470/90850336-b4a8ea80-e371-11ea-84b3-a8f4e7e06233.jpg)

RPR 2 (Beta) Bump
![DisplaceBumpBug_RPR-2Beta-bump](https://user-images.githubusercontent.com/61623470/90850372-d0ac8c00-e371-11ea-96ff-3692dc94621d.jpg)

RPR Full Bump
![DisplaceBumpBug_RPR-Full-bump](https://user-images.githubusercontent.com/61623470/90850384-d6a26d00-e371-11ea-9ed3-c0a777336eaf.jpg)

**Scene file:**  
[DisplaceBumpBug_RPR251.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/5106692/DisplaceBumpBug_RPR251.zip)

**Comment by bsavery** [comment]
Displacement I think is listed in the known issues of "TODOs" in rpr 2.0?  But those should be working in RPR 1.x (full mode).  I'll take a look

**Comment by bsavery** [comment]
Hi there. Let me give an update:

1.  Differences in textures - this is somewhat due to the "noise" node having less support in Bump and displacement.  This is not a bump and displacement issue.  If you plug in a checker texture it looks more similar.  Also you can use the new "bake texture" system to bake the noise node.
2.  RPR 2.0 bump is not supported yet.  (coming soon).  

Please reply with thoughts

**Comment by kintuX** [comment]
Hi, finally got some time to check the aforementioned...

1. Looks like there are a few duplicated categories :D and **Texture** is among them. 
_(Name prefix should resolve the confusion.)_ 

1st (Blender's list) Noise, Musgrave, Brick, Magic, Voronoi... Texture Nodes aren't supported at all (except Checker :). 
 
2nd Texture category (RPR's I presume) & Image Textures work OK. 
 
Further on,  when utilizing **Bake All Unsupported Nodes to Texture** all Nodes _driving_  the shader get deleted. Only Principled BSDF is left.
> 

2. Noted ;)
