### ISSUE TITLE
RPR2.0 Beta (2.5.2) redenring bug 

### ISSUE THREAD

**Issue by MakramDaou** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#78]
This may or may not be related to this issue:
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/69#issuecomment-680421573

RPR2.0 rendering is actually totally messed up. It doesn't really show up at first glance by when facing the right direction the meshes (any mesh, I tested with several models a reproduced the same thing) exhibits artifacts (which in some cases look like shadows )

Lighting setup is simple environmental lighting set to grey color.

RPR Full:
![rpr1](https://user-images.githubusercontent.com/46979415/91775912-9b633200-ebec-11ea-9636-85aa909471ec.png)

RPR 2.0:
![rpr2](https://user-images.githubusercontent.com/46979415/91775923-a1591300-ebec-11ea-904c-80f668956bc2.png)

RPR Full:
![rpr1](https://user-images.githubusercontent.com/46979415/91775939-ad44d500-ebec-11ea-8007-312eb4e955cf.png)

RPR 2.0:
![rpr2](https://user-images.githubusercontent.com/46979415/91775949-b3d34c80-ebec-11ea-8292-3d2ec5287adc.png)

Specs:
Windows 10 2004
i7 6700K
32GB
Radeon VII (latest Pro drivers)
Blender 2.8.3

Mak

**Comment by bsavery** [comment]
So I did a little digging here.  I think there is some difference in the way RPR 2 vs 1 is handling ray epsilon.  If you have the default 0.02 (in "Quality" tab of settings) the equivalent I've found in RPR 2 is 0.001.  We'll find a better way to handle this.

**Comment by bsavery** [comment]
(Comment withdrawn still investigating.

**Comment by MakramDaou** [comment]
Just tried 0.001 and got exactly the same result :(

**Comment by bsavery** [comment]
Yes, I can reproduce (in the future please attach a scene if possible) sorry the comment about ray epsilon was wrong.  I don't think this is related to the other material issue.

**Comment by bsavery** [comment]
Fixed in latest
