### ISSUE TITLE
ProRender 2.5.2 Render Bug Blender 2.83.4 macOS Catalina

### ISSUE THREAD

**Issue by myreauks** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#80]
I have a scene with a large array of objects.
When setting the subdivision modifier level to anything up to 5 for all these objects, the scene renders fine. However, if I set the subdivision level to 6, the scene no more renders with the following error in the render window:

ERROR | RPR call ContextRender(<pyrpr.Context object at 0x12cb83990>) returned error core <-3> with error message: ".Please see log for more details.

Unfortunately, I have no idea how to access the log. If you can tell me how to access it, I can provide further information.

Specs:
macOS Catalina 10.15.6
Blender 2.83.4
Radeon ProRender 2.5.2
32GB RAM
i7-10700K
5700 XT

Best,
Miro

**Comment by bsavery** [comment]
That error is an Out of memory error.  So assuming that the subdiv level is making the memory explode.  

One thing to note is RPR 2 will handle out of core memory for geometry.  Another suggestion would be to use adaptive subdivision for this, which will limit to 1 pixel size (you rarely need subdivision less than a pixel).

**Comment by myreauks** [comment]
Ah, thanks for the reminder on adaptive subdivision. I had some problems with it the last time I used it on my old Macbook Pro. Maybe it has improved now or performs better on my new computer.

Does the out of core memory handling for RPR 2 mean that it is extending the GPU memory to RAM and even that is filling up?

Best,
Miro

**Comment by bsavery** [comment]
To enable RPR 2 you have set the "Render Mode" in the quality section of the render settings.  Default is RPR 1 or "Full"

**Comment by myreauks** [comment]
Setting my object to adaptive subdivision with RPR 2.0 selected as render mode leads to instant crash when changing to rendered view in viewport. In RPR1 render mode adaptive subdivision also seems to work much slower than using the subdivision modifier.

-Miro

**Comment by bsavery** [comment]
I should have mentioned that adaptive subdivision does not work in RPR 2 yet ;)
