### ISSUE TITLE
ProRender for Blender Windows 10  V 2.5.2 UV Mapping/Scaling not working in High setting

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#81]
Issue: in High setting, UV mapping and scaling does not appear to be working.

Steps to reproduce:
Set up node structure for image/UV mapping (can use prorender materials library)
Change scaling through Mapping node or RPR normal map node, etc.

Software and Computer info:
Windows 10
Newest Pro AMD GPU Drivers
Blender 2.9
Prorender v 2.5.2
AMD Threadripper 3960x
AMD Radeon VII (x2)
1TB Aurous M.2 NVME SSD
64GB RAM
ASRock Creator TRX40

![image](https://user-images.githubusercontent.com/65964807/92038332-167d3300-ed28-11ea-8b78-b55edd1e372e.png)
![image](https://user-images.githubusercontent.com/65964807/92038380-23018b80-ed28-11ea-81ec-e100561ea2cc.png)
![image](https://user-images.githubusercontent.com/65964807/92038416-314fa780-ed28-11ea-95d3-0f59796c20c8.png)

**Comment by bsavery** [comment]
Thanks!  We actually just added some support for the UV mapping and scaling to hybrid modes (including high) but haven't exposed them in the Blender plugin yet.  So this is a good reminder of the TODO.

**Comment by djtutorials** [comment]
> Thanks! We actually just added some support for the UV mapping and scaling to hybrid modes (including high) but haven't exposed them in the Blender plugin yet. So this is a good reminder of the TODO.

Glad to hear it- I am really excited for this engine once everything is put together. Don't know if you have seen it, but I did a quick video on my YT channel on the 2.0 renderer. 

https://youtu.be/hR7hMNtaA6A

There is a lot of excitement for this engine. Thanks so much for what you all are doing.

**Comment by bsavery** [comment]
Closed!  See the latest version
