### ISSUE TITLE
Distorted Texture UV Mapping

### ISSUE THREAD

**Issue by myreauks** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#82]
UV mapping of my object gets distorted in filleted areas despite the UV map being correct. I have verified this by checking the same mapping with the same texture in cycles. In Cycles everything is fine. Attached are comparison screenshots. Do you have any ideas what might be happening here?

Cycles
<img width="620" alt="image" src="https://user-images.githubusercontent.com/46165331/92222049-135c8100-eea7-11ea-863d-4368980042ea.png">

RPR 1
<img width="620" alt="image" src="https://user-images.githubusercontent.com/46165331/92222230-561e5900-eea7-11ea-8a84-359d0fd61186.png">

Best,
Miro

**Comment by ARozghon** [comment]
Hi! That's Noise node or Texture map?

**Comment by myreauks** [comment]
It happens when using noise texture node and also when using a noise.jpg file with the RPR Image Texture node.

Best,
Miro

**Comment by bsavery** [comment]
Please attach a scene.  It's a bit hard to recreate from screenshots

**Comment by ardraeiss** [comment]
What UV type are you using? It would be good to have issue scene to see what exactly happens.

**Comment by bsavery** [comment]
Closing because no scene attached.
