### ISSUE TITLE
Windows Prorender for Blender Addon V2.5.3 - 2.0 Renderer Anisotropy Not Working

### ISSUE THREAD

**Issue by djtutorials** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#89]
Hi All,

I noticed that in the 2.0 renderer the Anistropy setting with Metalness is not working

Steps to reproduce:
1: Shade with Metalness at 1.0
2: Set roughness to anything but 0 (0.2 is good)
3: Increase Anisotropy to 1.0

Issue is seen on both CPU and GPU render devices. Images provided below showing renderer 1.0 vs 2.0.

Software and Computer info:
Windows 10
Newest Pro AMD GPU Drivers
Blender 2.9
Prorender v 2.5.3
AMD Threadripper 3960x
AMD Radeon VII (x2)
1TB Aurous M.2 NVME SSD
64GB RAM
ASRock Creator TRX40

**1.0 Renderer:**
![image](https://user-images.githubusercontent.com/65964807/93123625-49ef8400-f67d-11ea-8580-b546defb8b85.png)

**2.0 Renderer:**
![image](https://user-images.githubusercontent.com/65964807/93123698-64c1f880-f67d-11ea-99d9-f76f54bc5f88.png)

**Comment by bsavery** [comment]
Thanks.  I think we have this as a known issue with RPR 2.0 currently.

**Comment by bsavery** [comment]
I claim this is fixed now.  Please reopen if you still see.

**Comment by djtutorials** [comment]
Hi there-

I was using the newest build (2.5.30) with a simple UV sphere and this is what I'm getting- any advice on how to resolve?
![image](https://user-images.githubusercontent.com/65964807/99162408-5cecf780-26b2-11eb-94d5-a7e97f1cec10.png)

**Comment by bsavery** [comment]
So generally speaking I'm seeing anisotropy there.  Maybe add subdivision to get smoothness or smooth normals?

**Comment by ARozghon** [comment]
that does not help from my side and create more artefacts with anisotropy
![image](https://user-images.githubusercontent.com/68949117/99280437-00b4df80-283a-11eb-97cf-cffed8028657.png)

**Comment by djtutorials** [comment]
@bsavery these issues were not present in the 1.0/Legacy build until rather recently. In cycles, it doesn't really have to do be subdivided to show a smoothed normals surface using anisotropy.

Here is a screen grab of a more subdivided rounded cube with smooth shading and a sub-surface multiplier with the 2.0 renderer.

![image](https://user-images.githubusercontent.com/65964807/99317504-08b15700-281b-11eb-80ad-e50469b57d37.png)

Here is the Legacy renderer which shows a similar issue just less obvious. It is acting different than how it previously worked.

![image](https://user-images.githubusercontent.com/65964807/99317636-39918c00-281b-11eb-97ca-9da3d4ee9718.png)

Here is Cycles with similar kind of subdivision and settings:
![image](https://user-images.githubusercontent.com/65964807/99317796-78bfdd00-281b-11eb-95ed-739b1d6f8211.png)

**Comment by djtutorials** [comment]
I would also like to add that it appears the anisotropic effect is being applied via the UV mapping which I dont think is particularly ideal for shading and I haven't seen that in other engines including I believe previous versions of Prorender. Not sure how this can be adjusted of course but you can tell based on the differences in the visible creases between Prorender and Cycles that the anisotropic effect is not being applied in the same way.
