### ISSUE TITLE
Normal mapping bug in RPR2 [Beta] 2.5.7

### ISSUE THREAD

**Issue by MakramDaou** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#91]
This one is hard to catch so I had to boost the strength of the normal map but as you can see the RPR 2.0 render doesn't look right (we can see the UV seems for example as if it was inverted) Sorry don't have the scene to share right now but this can be easily reproduced.

RPR 2.0 Beta:
![Normal_RPR2png](https://user-images.githubusercontent.com/46979415/93724775-65d9b500-fbaa-11ea-97ee-d29505e35e22.png)
![InkedNormal_RPR2png_LI](https://user-images.githubusercontent.com/46979415/94054640-2f837c00-fddc-11ea-9cd5-f7c11ba68a69.jpg)

Full:
![Normal_RPR1](https://user-images.githubusercontent.com/46979415/93724778-6c682c80-fbaa-11ea-90f2-c0b8c1124579.png)

Cycles:
![Normal_Cycles](https://user-images.githubusercontent.com/46979415/93724974-d3d2ac00-fbab-11ea-95cf-89b2ba9f5983.png)

Specs:
Windows 10 2004
i7 6700K
32GB
Radeon VII (latest Pro drivers)
Blender 2.9

Mak

**Comment by bsavery** [comment]
Can you retry with latest builds?  This should be fixed.

**Comment by MakramDaou** [comment]
@bsavery Issue is still present in 2.5.22

**Comment by ARozghon** [comment]
hello, @MakramDaou , one question: did you use "Non-Color" Color space for Normal map texture?

**Comment by MakramDaou** [comment]
@ARozghon Yes. As I described & showed above it looks fine in RPR1 (Legacy) & Cycles. Only RPR2 isn't rendering correctly.

**Comment by ARozghon** [comment]
thank you

**Comment by MakramDaou** [comment]
@ARozghon I'm on the latest build: 2.5.22 

![Screenshot 2020-11-03 123000](https://user-images.githubusercontent.com/46979415/97979987-616f0180-1dd0-11eb-8de6-c10589e56681.jpg)

**Comment by ardraeiss** [comment]
The polygons along that line are disconnected. This line is in fact the nearly invisible hole.

**Comment by ardraeiss** [comment]
In fact, normals issue on that line is present in Cycles as well, it's just less noticeable.
To get smoothed polygons should be connected. If they are simply placed next to each other it won't happen.

**Comment by MakramDaou** [comment]
The mesh is perfectly fine:
![Screenshot 2020-11-14 232615](https://user-images.githubusercontent.com/46979415/99158316-aef14580-26d1-11eb-934a-98f693d1ab83.jpg)


![Screenshot 2020-11-14 232641](https://user-images.githubusercontent.com/46979415/99158311-a7ca3780-26d1-11eb-8572-3e7ea6be1197.jpg)

The UV seams (which is what we are clearly seeing in the RPR2 render):
![Screenshot 2020-11-14 233422](https://user-images.githubusercontent.com/46979415/99158337-f4157780-26d1-11eb-9985-a989a28a155f.jpg)

Cycles:
![Screenshot 2020-11-14 233739](https://user-images.githubusercontent.com/46979415/99158417-e1e80900-26d2-11eb-84e3-6bd5e44376d9.jpg)

RPR2:
![Screenshot 2020-11-14 233938](https://user-images.githubusercontent.com/46979415/99158425-f3c9ac00-26d2-11eb-9fc9-59737583f16d.jpg)

**Comment by ardraeiss** [comment]
![image](https://user-images.githubusercontent.com/2946319/99159022-f388db00-26e9-11eb-8d9c-88f4694ef2b1.png)
Here is this part selected via "Select more". It can be moved freely since it doesn't welded with other parts. Same goes for other segments. They are put near each other, but they weren't joined.

That also seems to be something wrong with normals map as well.

**Comment by MakramDaou** [comment]
I just double checked to make sure and the "disconnected faces" oddity isn't the cause of the normal map rendering issue (this mesh issue is apparently caused by Marmoset Toolbag when exporting an .OBJ from ther and importing it in Blender).  

Here's another example on an other mesh:

Cycles:
![Screenshot 2020-11-15 020728](https://user-images.githubusercontent.com/46979415/99160495-4f526480-26e8-11eb-8803-0dc3ba9fe444.jpg)

RPR2 (note the clear distinction between UV seems and pixelated normal map):
![Screenshot 2020-11-15 020647](https://user-images.githubusercontent.com/46979415/99160505-62653480-26e8-11eb-892b-0977e0db6159.jpg)

UV:
![Screenshot 2020-11-15 021728](https://user-images.githubusercontent.com/46979415/99160557-ecad9880-26e8-11eb-8d09-709a21524b51.jpg)

This mesh is perfectly fine...
![Screenshot 2020-11-15 021637](https://user-images.githubusercontent.com/46979415/99160559-f46d3d00-26e8-11eb-8790-eb264a714abd.jpg)

**Comment by bnagirniak** [comment]
I looked more closely to this issue also. I found that issue is in Normal map and UVs assigned to the mesh - they aren't corresponded to each other. Therefore we see such edge between submeshes corresponded to different UVs areas.

In the picture below area of triangles selected on mesh corresponds to 2 different areas on normal map. 
![image](https://user-images.githubusercontent.com/33626169/100542658-02c46880-3254-11eb-99bb-96baa4de1135.png)
Such 2 areas aren't smooth if we place them closely to each other.

BTW, I looked closely this issue in cycles and see same artifacts there but less visible then in RPR.

**Comment by MakramDaou** [comment]
I mean here's how it looks in Cycles & then in RPR2. 

Cycles:

![Screenshot 2020-11-30 133705](https://user-images.githubusercontent.com/46979415/100616959-205c0580-331a-11eb-8214-9d627b081d72.jpg)


RPR2:
![Screenshot 2020-11-30 134851](https://user-images.githubusercontent.com/46979415/100616980-27831380-331a-11eb-8249-788bec087c18.jpg)

It's relatively obvious that there's either a tangent space issue in RPR2 (alongside the pixelated artifacts I showed you on the shots of the other model I posted in my previous post) or this is related to this other RPR rendering issue: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/67

The normal map generated in MikkTSpace is perfectly fine and renders without any issue in anything but RPR.

Here's another example on an other model:

Cycles:
![Screenshot 2020-11-30 140504](https://user-images.githubusercontent.com/46979415/100617100-4f727700-331a-11eb-8c66-a0a960e9ad26.jpg)


RPR2:
![Screenshot 2020-11-30 140625](https://user-images.githubusercontent.com/46979415/100617119-55685800-331a-11eb-9657-d0ffb3d499e2.jpg)


Here's a Quixel Megascans asset:

Cycles:

![Screenshot 2020-11-30 143711](https://user-images.githubusercontent.com/46979415/100617227-80eb4280-331a-11eb-942f-f565229d61d7.jpg)

RPR2:
![Screenshot 2020-11-30 143442](https://user-images.githubusercontent.com/46979415/100617258-8ba5d780-331a-11eb-98d6-5ad5c97aba0a.jpg)

You can clearly see in each case that one UV island is fine while the other it totally messed up (low-res).

**Comment by ardraeiss** [comment]
@MakramDaou could you check your boot scene with this setup?
![image](https://user-images.githubusercontent.com/2946319/100707109-31108800-33bb-11eb-8e3a-d7555479874d.png)
Turn off all lights/environment and other objects.

This is what I get with tiger scene with such setup.
Cycles CPU
![Cycles_CPU](https://user-images.githubusercontent.com/2946319/100707348-9795a600-33bb-11eb-9400-638245d74a38.png)

RPR2 CPU
![RPR2_CPU](https://user-images.githubusercontent.com/2946319/100707383-a54b2b80-33bb-11eb-878f-413f281b143e.png)

RPR2 GPU
![RPR2_GPU](https://user-images.githubusercontent.com/2946319/100707421-b136ed80-33bb-11eb-8a89-a5dc1c133e8c.png)

RPR1 CPU
![RPR1_CPU](https://user-images.githubusercontent.com/2946319/100707434-b5fba180-33bb-11eb-865b-8440497e005e.png)

There are 3 things:
- small issue on unwelded edges in all render engines. If you check images next to each it's easier to find;
- noticeable issue with Normal Map node result in RPR2 mode. You are correct, it is wrong.

**Comment by MakramDaou** [comment]
@ardraeiss Yes this is what I get.

**Comment by ardraeiss** [comment]
It seems that the fix would be available in the next release.
Cycles
![tiger_cycles](https://user-images.githubusercontent.com/2946319/100792139-41f8e200-342b-11eb-85fe-55cad9cd4ba8.png)

RPR2 (note - a slightly different world color was used)
![tiger_rpr2](https://user-images.githubusercontent.com/2946319/100792150-43c2a580-342b-11eb-9b4f-d991ca316727.png)

Is that the result you are looking for?

**Comment by MakramDaou** [comment]
@ardraeiss Yes this looks like its fixed :)

**Comment by MakramDaou** [comment]
Next step would be to "fix" this https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/issues/67:
![Screenshot 2020-12-02 152143](https://user-images.githubusercontent.com/46979415/100884873-4b795d00-34b2-11eb-887b-a4b1b48347f6.jpg)

**Comment by ardraeiss** [comment]
Closed as fixed
